### ISSUE TITLE
editor : multiple provision activity lost when editing a document

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#1003]
**Describe the issue**
When editing a document with multiple provision activity, only the last one will be appears into the editor; this cause a metadata lost.

**To Reproduce**
1. Log as librarian
1. Import or create a document with multiple provision activity (ex : import EAN 9782298133103)
1. Correct editor (removing "place" part of provisionActivity[@type=Manufacture])
1. Save it
1. The created document should have 3 provisions activities : two "bf:Publication" parts and one "bf:Manufacture" part
1. Edit this document : both "bf:Publication" parts are disappear.

**Expected behavior**
All existing provisionActivity parts should be displayed.

**Software version**
Tell us which version you're using:

  * rero-ils : fe0a8c3
  * rero-ils-ui : e3248a9

**Comment by AoNoOokami** [comment]
I saw the same with subjects while working on the UX of editor.

**Comment by zannkukai** [comment]
Note to solve (to myself or anybody): 

The problem seems to be present into the `array_type.component.ts`. When a "hidden" change is detected on a field, then all children of this field will be removed (except the lastOne if `minItems=1` into JSON Schema). 
https://github.com/rero/ng-core/blob/dev/projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.ts#L58
The question is now : "Why an 'hide' event is send for these elements"
