### ISSUE TITLE
Author search in document creation display wrong date.

### ISSUE THREAD

**Issue by rerowep** [rero/rero-ils#1038]
**Describe the issue**
In the document editor the search for an author displays a wrong date.

**To Reproduce**
1. Go to https://ilsdev.test.rero.ch/professional/records/documents/new
1. Log in as librarian
1. Click on Author-Name
1. Search for `Clastres`
1. See `Clastres, Pierre, 2019 ..` is displayed

**Expected behavior**
`Clastres, Pierre, 19..`schould be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/31234355/84563364-56510180-ad5b-11ea-9825-1c4f9b2cacd5.png)

**Comment by rerowep** [comment]
We should use `authorized_access_point_representing_a_person` in `reroils-ui:projects/admin/src/app/record/editor/remote-autocomplete/remote-autocomplete.component.ts` for the functions: `getNameSource` and `getName`

**Comment by iGormilhit** [comment]
@rerowep Please, for future issues, use the rero-ils project, as the issue template suggest. Thanks.
