### ISSUE TITLE
Autocomplete doesn't work if your search contains diactrictics

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils#1042]
**Describe the issue**
Autocomplete doesn't work if your search contains diactrictics (try: réalité and realite)

**To Reproduce**
1. Go to homepage
2. Search with 'realite' keyword
3. There is no autocomplete, no suggestions of result

**Expected behavior**
Autocomplete should work with diactrictics in the search

**Software version**
ilsdev.test.rero.ch
https://github.com/rero/rero-ils/commit/647a7f3a003ad6bd8318324233a82c4bab3db889
https://github.com/rero/rero-ils-ui/commit/30e8cdd119f8b3184553d73a34442e3b32a03859

**Comment by zannkukai** [comment]
Search with diacritics seems works well.
I had some issues with `L'` prefix before diacritics words.
Search with `école` return no result, search with `l'école` return 1 result. 
Search with `tête` return 1 result (as expected)
Maybe the "apostrophe" isn't yet considered at a word separator into ES analyzer ?

**Comment by zannkukai** [comment]
Is a search on `tete` should return `tête` results ?

**Comment by pronguen** [comment]
Seems to be solved: the suggestions include the diacritics. But the highlighted text in each suggestion does not.
