### ISSUE TITLE
Message missing from the acquisition order line editor

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1053]
**Describe the issue**
The following message is missing from the acquisition order line editor : _Should be in the following format: https://ils.rero.ch/api/documents/<PID>_

**To Reproduce**
1. Login as a librarian or system librarian.
2. Go to Acquisitions.
3. Add a new order.
4. Add a new order line.
5. Try to fill the Document URI field.

**Expected behavior**
The message 'Should be in the following format: https://ils.rero.ch/api/documents/<PID>' should appear below the Document URI field.

**Context**
https://ilsdev.test.rero.ch
v.0.9.1
rero-ils version 83a9f1f7
rero-ils-ui version 11bed85b

**Screenshots**
![image](https://user-images.githubusercontent.com/12396034/85138009-56ad3900-b242-11ea-9281-aa5163298b1a.png)

**Comment by iGormilhit** [comment]
I could reproduce it locally on 3bc31ca. The validation message does not show up.

![order-line-validation-message](https://user-images.githubusercontent.com/1557213/85258550-34d8cf80-b457-11ea-8934-788428891c12.png)

**Comment by zannkukai** [comment]
The message appears when you begin to enter some value into the field.
![image](https://user-images.githubusercontent.com/10031585/85852003-1274e800-b7b0-11ea-8ad5-ef350bf456f5.png)

This field behavior must be changed in next PR. Instead use an input text field, we should use a typeahead with suggestions.

**Comment by iGormilhit** [comment]
So, I'm closing this. Thanks.
