### ISSUE TITLE
The non required fields of the document editor should support default values.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1119]
**How it works**

Currently in the document editor, only required fields (displayed by default when opening the editor) integrate default values. When another field is added manually, it does not have default values.

**Improvement suggestion**

When a field is added manually, it should be able to integrate default values.

**Comment by jma** [comment]
Other editor bugs improvements:
- support for hidden sub properties for multischema (oneOf)
- remove value for hiddenExpression = true when a field becomes hidden
- populate the field with default value when the field is show
- head support for simple type of first level
