### ISSUE TITLE
maximum number of results 

### ISSUE THREAD

**Issue by rerowep** [rero/rero-ils#112]
Maximum number of results set to 20000 in json mapping.
Value must be sa same in config.py and higher for production.
Attention maybe heap will not be sufficient and elasticsearch scrolling has to be implemented.

**Comment by iGormilhit** [comment]
@rerowep What is the status of this issue? And, is it a bug or an enhancement?

**Comment by iGormilhit** [comment]
@rerowep What is the status of this issue?

**Comment by rerowep** [comment]
Maybe we have to reopen this if we will implement full api export!
