### ISSUE TITLE
Public patron profile view raises an error 500

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils#1145]
**Describe the bug**
This is a translation issue. Lines 57 to 61 makes the app crash when a patron has renewed or request loan.
https://github.com/rero/rero-ils/blob/0d7cc7988b7bffbd0807d3eb33697c74da8e9357/rero_ils/modules/patrons/templates/rero_ils/_patron_profile_loans.html#L57

**To Reproduce**
Request an item as patron. Go to patron profile view.

**Expected behavior**

**Context**
dev @ https://github.com/rero/rero-ils/commit/0d7cc7988b7bffbd0807d3eb33697c74da8e9357

**Screenshots**

**Additional context**

**Comment by iGormilhit** [comment]
@AoNoOokami This is interesting. As I told @Garfield-fr two days ago, this part of the patron profile template generates a weird string to be translated after the message extraction.

This exact line: https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/patrons/templates/rero_ils/_patron_profile_loans.html#L57

results in this extracted string: https://github.com/rero/rero-ils/blob/dev/rero_ils/translations/fr/LC_MESSAGES/messages.po#L7017

ending in weblate like this: https://hosted.weblate.org/translate/rero_plus/rero-ils/fr/?checksum=4c29991da68163d6.

**Comment by iGormilhit** [comment]
This has been fixed by a translation PR (weblate).
