### ISSUE TITLE
There is no information on the item when a checkin without action is performed

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils#1168]
**Describe the bug**
When an item of library A, in transit to library C, is checked-in in library B, there are no information to show the status and the destination of the item.

**To Reproduce**
1. Create an item in library A
2. Make a request for a patron to be picked-up in library C
3. Checkin the item in library A. The item is in transit to library C.
4. Checkin the item in library B. There is no information displayed about the transit.

**Expected behavior**
A line is displayed with the mention that no action has been realised, the item status and the pickup library.

**Context**
dev of rero-ils: https://github.com/rero/rero-ils/commit/c12a4dff3f8b460e8a695e7e70e8ee635f5f36d8
dev of rero-ils-ui: https://github.com/rero/rero-ils-ui/commit/78cc6e5742b9ffdfbddf27d33f0d77710f9885c4
ng-core v0.8.0

**Screenshots**

**Additional context**

**Comment by iGormilhit** [comment]
@AoNoOokami Is it still relevant? If not you can close it.

**Comment by AoNoOokami** [comment]
This is still relevant, but not urgent according to a discussion I had with @pronguen
