### ISSUE TITLE
Too much api calls when switching from checkin view to patron loan view

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils#1179]
**Describe the bug**
When going to patron loan view from checkin view, there are a lot of api calls to `/api/patrons/` (see screenshot below).

**To Reproduce**
1. Go to checkin view and open network tool
2. Type patron barcode, for example 'kad001' to go to patron loan view
3. Check the network window and see the api calls

**Expected behavior**
Only one api call is enough.
This may mean that there are missing `unsubscribe` in the process.

**Context**
Tell us on what server did you spotted the issue, using with browser.

* dev of rero-ils @ https://github.com/rero/rero-ils/commit/2c6df787a81c94e21860c0555408b9b8518707d6
* dev of rero-ils-ui @ https://github.com/rero/rero-ils-ui/commit/94ea8e65accb727470def876fda6ddd87d5720f1
* ng-core v0.8.0

**Screenshots**

![api](https://user-images.githubusercontent.com/28982829/91159935-14ccc300-e6c9-11ea-9321-86b9ac6234d7.png)

**Additional context**

**Comment by iGormilhit** [comment]
@AoNoOokami Is this the cause of toast messages with unexpected information in the circulation module interface?

**Comment by AoNoOokami** [comment]
> @AoNoOokami Is this the cause of toast messages with unexpected information in the circulation module interface?

It may be linked. @zannkukai and @sebastiendeleze said that there are too much API calls when we were working around this bug and that should be improved.

**Comment by PascalRepond** [comment]
Cannot reproduce on `v1.9.0`. Has probably been fixed since then.
