### ISSUE TITLE
Person search brief view: some information missing

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#118]
Some information (dates, biographical infos) is missing in the brief view of the person search, for specific examples:
* [Genty de Bonqueval, J](https://ils.test.rero.ch/editor/search/pers?page=1&size=20&q=genty)
* [Carelli, Francesco](https://ils.test.rero.ch/editor/search/pers?page=1&size=20&q=carelli)
* [Bernard, Bayle](https://ils.test.rero.ch/editor/search/pers?page=1&size=20&q=bernard%20bayle)
* etc.

However, in most of the cases, this info is present in the brief view.

**Comment by iGormilhit** [comment]
@pronguen I think this is not anymore relevant, but I'm not positively sure...

**Comment by pronguen** [comment]
It seems to be resolved, but the above mentioned examples are not in the sample anymore. Let's close this issue (and reopen another one later if necessary)!
