### ISSUE TITLE
Network protection and "any later version" removed from license

### ISSUE THREAD

**Issue by comradekingu** [rero/rero-ils#1186]
**How it works**

It isn't possible to effectively remove these protections without the consent of the copyright holders as was done in https://github.com/rero/rero-ils/commit/b7752a1e4a4b980a9e8122d53209df9e23b48623

**How it should works**

The network parts and "any later version" should not have been removed. Ideally the full license would be reinstated.

**Comment by iGormilhit** [comment]
Hi @comradekingu,

Thanks for your comment, but in my understanding, the part removed in https://github.com/rero/rero-ils/commit/b7752a1e4a4b980a9e8122d53209df9e23b48623 is only an explanation on how to use the license (header template, for instance). This text comes after the *END OF TERMS AND CONDITIONS* part. So, I think this commit removes nothing of the protections provided by the license.

I'm open to further explanation from your side, of course.

**Comment by comradekingu** [comment]
@iGormilhit You are correct, my bad.
I was looking to see whether the license on translations should indeed be "AGPLv3-only", as it is now, or if the project is "or later".
My confusion arose from section 14. https://www.gnu.org/licenses/agpl-3.0.html

>Each version is given a distinguishing version number. If the Program specifies that a certain numbered version of the GNU Affero General Public License "or any later version" applies to it, you have the option of following the terms and conditions either of that numbered version or of any later version published by the Free Software Foundation.

So if it isn't that

>This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

is to be found in what is effectively not part of the license, then how is anything "or later", short of marking up every file (like it suggests, but is often not done)?

Be that as it may, I think maybe source code needs to have "only" stated specifically (?), it is the case that
on https://hosted.weblate.org/projects/rero_plus/#information "rero-ils" is "only", whereas everything else is "or later". That doesn't seem to match, and the problem comes into question by having anything "only". Should it be all "or later"?

**Comment by iGormilhit** [comment]
@comradekingu Ok, I think I got it. You are right, the licence of the `rero-ils` component on weblate should be *GNU Affero General Public License v3.0 or later*, as it is for all the other components. I think it was a setting error from my part. I changed it on https://hosted.weblate.org/projects/rero_plus/#information.

But for the text of the license itself, I'm not sure it's actually possible to find a difference between AGPLv3-only and "or later".

**Comment by comradekingu** [comment]
@iGormilhit The only specifically "only" i've seen actually states "only", like the Linux kernel. However the license seems to want everyone to mark up every file, which isn't always the case to say the least.
My issue is fixed though, thanks :)
