### ISSUE TITLE
The date in the data should be better checked.

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#1187]
**How it works**

All the date use the same regular expression but this is not robust as it allows date such as 2020-67-74.

**Improvement suggestion**
The idea is to replace the existing regex in the JSONSchema with something similar to:
`"pattern": "^[0-9]{4}(-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01]))?$",`

This has been used by SONAR.

Even better, we can use a date validator in the editor.

**Comment by zannkukai** [comment]
the `datepicker` field type already validate if entered date is valid.
Otherwise I found something like this, but needs I should ask some help to add it into the editor (I tried but it's very concluant)
```typescript
export function dateExistsValidator(control: FormControl, field: FormlyFieldConfig, options): ValidationErrors {
    const defaultOptions = {
        formats: ['YYYY-MM-DD']
    };
    options = {...defaultOptions, ...options};
    return (moment(control.value, options.formats, true).isValid())
      ? null  // input date is valid
      : {'date-exists': `"${control.value}" isn't a valid date`};
}
```
