### ISSUE TITLE
Record deletion without checking the attached records

### ISSUE THREAD

**Issue by NicolasLabat** [rero/rero-ils#12]
When deleting a record to which other records are attached, eg : organisation with members, bib records with items. The attached records are automatically deleted with the main record without any warning message.

**Comment by NicolasLabat** [comment]
We get an "Internal server error"when trying to delete a bib record to which one or several items are attached.

**Comment by rerowep** [comment]
solved with: 2809cfcfa3028764fe8a53c578e4711f5b981ab8
