### ISSUE TITLE
circulation: enhance notifications in order to group emails sent to patrons

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#1236]
**How it works**

Today, RERO-ILS (0.12) sends one notification for each item borrowed by a patron. 
If he borrows 10 books, the system will send 10 emails.  

**Improvement suggestion**
In order to avoid email spamming :-) , try to group items of the same library into ONE notification, by type, every day.

**Comment by iGormilhit** [comment]
Is a user story: https://tree.taiga.io/project/rero21-reroils/us/1745
