### ISSUE TITLE
Same field "partOf" generated twice

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1242]
**Describe the bug**
In some cases, the same field "partOf" is generated twice.
It is the case with document with 2 MARC fields 800.

**To Reproduce**
Example: https://ilspilot.test.rero.ch/api/documents/783145
Example in MARC/Virtua: http://data.rero.ch/01-R004799448/marchtml

**Expected behavior**
Field is only generated once, if the content (`document`, `numbering`) is exactly the same

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

**Comment by iGormilhit** [comment]
@reropag Is it still relevant? If not you can close it.
