### ISSUE TITLE
circulation: need a better response time for the patron account (public/pro interface)

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#1246]
In the public view, the display of a patron account with 20 loans takes around 5 sec.
and it can be more if the patron has additional requests. (jinja view: the system loads all information, then it renders the page)

In the prof. view, for the same patron, it takes between 5 and 10 sec to get the loans page.
and the content is reloaded each time you click on the Tab "Checkout/Checkin" (again, 5-10 sec)

In a production environment, we need a better response time. 

You can view a small demo here : https://bib.uclouvain.be/RERO/REROILSv012-Perf-PatronAccount.m4v

**Improvement suggestion**
Try to improve the response time when :
- the patron wants to display its account in the public view (using a pager f.i. ?)
- a staff wants to access the loan page of the patron in the professional view.

**Comment by zannkukai** [comment]
No problem to solve this problem in the professional interface. But for public interface, to do something similar and asynchronous we need to use a lot of jQuery at this time... it seems not really appropriate.
