### ISSUE TITLE
Holdings for journals have various problems

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1252]
**Describe the bug**
Sometimes, the
* hidden issues cannot be expanded
* tab "Description" is empty
* issue reception is not possible (due to holdings import from Virtua with type "standard" instead of "serial")
* mousehover on the trash does not display any message (same reason than previous point)
* library is not always displayed in the holdings; there is an empty string before the location

**To Reproduce**
* Log in as a librarian in organisation Valais (ex: reroilspilot+vs1950s@gmail.com)
* Open https://ilspilot.test.rero.ch/professional/records/documents/detail/12664
* Try to display the hidden issues (impossible)
* Try to display the tab "Description" (impossible)
* Try to receive an issue for the first displayed holdings
* Try to mousehover the trash for the first displayed holdings
* See that the library is not always displayed in the holdings (before the location)

**Expected behavior**
* hidden issues can be expanded
* tab "Description" is displayed
* issue reception is possible for serial holdings; the button is not displayed for standard holdings
* mousehover on the trash always displays a message if the button is disabled
* the library is always displayed in the holdings, just before the location

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

![image](https://user-images.githubusercontent.com/8154915/94794507-42014500-03dc-11eb-9d93-a503d1e59a8b.png)

**Comment by BadrAly** [comment]
For the problem: `issue reception is not possible (due to holdings import from Virtua with type "standard" instead of "serial")`: 
This is a data problem will be corrected with the next loading of pilot holdings/items.
