### ISSUE TITLE
brief view for logged user not reliable

### ISSUE THREAD

**Issue by rerowep** [rero/rero-ils#129]
Brief view for logged user shows only `}}` as result!

Following error could be found on navigator console:
`rero_ils.search.0d66a7ce.js:1 Uncaught TypeError: $(...).bootstrapAutoHideNavbar is not a function`

* Login as user
* navigate to different resources
* repeat until you hit the bug

**Comment by iGormilhit** [comment]
@rerowep Could you detailed how to reproduce this bug? Thanks.
