### ISSUE TITLE
The error message in the prediction preview is not for end users.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1290]
**Describe the bug**
In the prediction preview, it happens that the error message "Template 500" appears.

**To Reproduce**
* Click to create a new serial holding
* Just select a frequency (nothing else)
* See the message in the prediction preview

**Expected behavior**
A default value for the field "The expected date for the next issue" should be added to avoid this message. The error message should be specific understandable for a user of the editor.

**Context**
* server: ils.test.rero.ch
* version: v0.12.0

Proposed by the pilot libraries

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/95823666-4c9dd180-0d2e-11eb-95a2-0284c4873c57.png)

**Comment by iGormilhit** [comment]
Issue closed because not able to reproduce.
