### ISSUE TITLE
Spinner should be everywhere

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1298]
**Improvement suggestion**

For the moment, a spinner is available for the document search, document editor, display of vendors/orders/budgets, inventory list etc,
It would be nice to have a spinner for other transactions (f.i. circulation desk)
Examples:
* checkin/checkout form + checkout form in patron account (when doing a transaction; it would avoid a librarian to scan twice a barcode)
* display of the requests (user services)
* [for later because it is ginga] submission of an ILL request (public interface)

Evaluate this module: https://aitboudad.github.io/ngx-loading-bar/

**Comment by AoNoOokami** [comment]
Suggestion: https://aitboudad.github.io/ngx-loading-bar/
