### ISSUE TITLE
No notification generation for some loans

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1308]
La BPU Neuchâtel signale un problème sur les notifications:

- le patron suivant a fait un loan qui aurait dû générer la notif, mais il n'y a rien dans la boîte e-mail: https://ilspilot.test.rero.ch/api/patrons/10955
- l'item concerné est: https://ilspilot.test.rero.ch/api/items/611719

@ UCL : les notifications de rappel

**Comment by ManaDeweerdt** [comment]
At UCL we didn't receive the 'overdue' notification. It works for the 'due soon' notification.

**Comment by BadrAly** [comment]
The problem in the `ilspilot` instance that the scheduler was not running. Once started the scheduler, the notifications sent to the patrons. The notification for the transaction listed above is https://ilspilot.test.rero.ch/api/notifications/7
So this is not a bug, just server config issue

**Comment by BadrAly** [comment]
> At UCL we didn't receive the 'overdue' notification. It works for the 'due soon' notification.

@ManaDeweerdt In which instance? could you please provide an example to look at?

**Comment by ManaDeweerdt** [comment]
It is on our instance https://ils.bibtest.uclouvain.be/uclouvain/ Ex: bc  10999945 ; 10987160

**Comment by ManaDeweerdt** [comment]
> It is on our instance https://ils.bibtest.uclouvain.be/uclouvain/ Ex: bc 10999945 ; 10987160

![image](https://user-images.githubusercontent.com/12396034/96454469-2f7c6d80-121c-11eb-9780-d05b14b032ee.png)

**Comment by BadrAly** [comment]
> > It is on our instance https://ils.bibtest.uclouvain.be/uclouvain/ Ex: bc 10999945 ; 10987160
> 
> ![image](https://user-images.githubusercontent.com/12396034/96454469-2f7c6d80-121c-11eb-9780-d05b14b032ee.png)

The notifications are well generated in the system, problem they are not sent. On the server side, try to run `Notification.api.process_notifications` manually to see why they are not sent to patrons

**Comment by iGormilhit** [comment]
We need to track this kind of issue in Sentry or in an alert system like Zabbix.
