### ISSUE TITLE
Fields name and birth date should not be editable by a user/patron

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1318]
**How it works**

The user can modify all his/her data following a link "RERO ID".

**Improvement suggestion**

He/She should not be able to modify the first name, last name and birth date.

**Context**

Suggested by pilot libraries

**Comment by iGormilhit** [comment]
Will be fixed by [US 1889][1] *Patron: edit personal data + simplify RERO ID link*.

[1]: https://tree.taiga.io/project/rero21-reroils/us/1889
