### ISSUE TITLE
Form for ILL requests is not translated

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1320]
**Describe the bug**

The form for ILL requests, accessible from the public interface by the end user, is not translated, even if all string are translated in Weblate.

Only the 2 section titles and the error messages are translated (see screenshot).

**To Reproduce**

1. Open the form

**Expected behavior**

Should be translated

**Context**

* server: ils.test.rero.ch
* version: v0.13.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/96688036-f6a9d900-1380-11eb-839c-b3f0ff455563.png)

**Comment by iGormilhit** [comment]
Most of the editor labels are translated in `v0.14.1`, but there is still issues on some strings.

This string is not extracted: *Caution! A well detailed request is more likely to be satisfied*: `rero_ils/modules/ill_requests/templates/ill_request_form.html#L25`

:warning: Change `Caution !` to `Caution!`.

Loan and Copy are, but not yet translated on weblate.
