### ISSUE TITLE
Bulle items with item type of other organisation

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1326]
**How it works**

Some items of Bulle have an item type not accessible in the Bulle organisation.

**To reproduce**

1. See https://ilspilot.test.rero.ch/api/items/2107321 or see it in the user interface https://ilspilot.test.rero.ch/professional/records/items/detail/2107321

**How it should works**

Should have an item type of the organisation.

**Context**

Proposed by pilot libraries

![image](https://user-images.githubusercontent.com/8154915/96897229-ade04600-148e-11eb-9c52-b97ca37cfb82.png)
![image](https://user-images.githubusercontent.com/8154915/96897340-c8b2ba80-148e-11eb-8324-791421a21e38.png)

**Comment by BadrAly** [comment]
Fixed in version `v0.14` of the migration script
