### ISSUE TITLE
A lot of document country codes have not been imported.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1328]
**Describe the bug**
A lot of document country codes have not been imported, although they exist without error in Virtua.

**To Reproduce**
1. See R003406646 (https://ilspilot.test.rero.ch/api/documents/494519) or R008384083 (https://ilspilot.test.rero.ch/api/documents/1343169)

**Expected behavior**
All codes are imported.

**Context**
Tell us on what server did you spotted the issue, using with browser.

* server: ilspilot.test.rero.ch
* version: 0.12.0

**Comment by rerowep** [comment]
I lot of notices have wrong data. 
Example R003406646:
There is no 044 and the country from 008[15-17] is |||. 
The same with R008384083.
It is very difficult to guess the country in this cases.

**Comment by rerowep** [comment]
rero_ils/dojson/utils.py line 915 `self.country = self.field_008_data[15:18].rstrip()`-> `self.country = self.field_008_data[15:17]`

**Comment by pronguen** [comment]
@reropag @rerowep The problem exists also for the language. Did you address it?
See examples: https://ilspilot.test.rero.ch/rbnj/search/documents?q=que%20sais-je&page=1&size=10&subject=France&language=und (facet language)
Tell me if I should open another issue.

**Comment by iGormilhit** [comment]
Not a RERO ILS issue, but an issue from the legacy system data extraction.

**Comment by iGormilhit** [comment]
Closed by changes outside of RERO ILS.
