### ISSUE TITLE
Save as a template does not always create a template

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1331]
**Describe the bug**
As a librarian, I edit a document and save it as a template, but it does not create a template. It seems to always work with patrons, items and holdings, but not with documents.

**To Reproduce**

1. Open https://ils.test.rero.ch/professional/records/documents/edit/349
2. Click on "save as a template"
3. Choose a name like "video test"
4. Save
5. See that no template has been saved

Sometimes it works fine, sometimes it does not.

**Expected behavior**
It always create a template.

**Context**
* server: ils.test.rero.ch
* version: 0.13.0
* Bug observed on Firefox and Chrome

**Additional context**
Proposed by pilot libraries

**Comment by iGormilhit** [comment]
@pronguen I cannot reproduce it with `v0.14.1` or on ilsdev (rero-ils version ce5a47d2 ; rero-ils-ui version dfe2a0e3). I think it's resolved.

**Comment by pronguen** [comment]
@iGormilhit I cannot reproduce it neither. I close the issue.
