### ISSUE TITLE
Zabix should capture when the schedular does not execute the tasks 

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1339]
For the dockerprod2 (ils_pilot instance), the schedular is up but does not execute the tasks at all. This is a deployment problem. Unable to duplicate in the other rero instances (test, dev..)
Make sure that Sentry will be able to capture this problem if it happens again.

**Comment by rerowep** [comment]
Solved after restarting scheduler pods.

**Comment by BadrAly** [comment]
I am re-opening the issue: In the description of the issue, still need to make sure that Sentry can capture this problem when it happens again

**Comment by iGormilhit** [comment]
Related to https://github.com/rero/rero-ils/issues/1308.

**Comment by iGormilhit** [comment]
I need to get confirmation that this scheduler is monitored through Zabbix.
