### ISSUE TITLE
A due_soon notification should not have "Not renewable"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1342]
**Describe the bug**
A due_soon notification has been sent with mention "Not renewable" for an item that has no other requests and is renewable.

**To Reproduce**
See logs.

Email sent to patron https://ilspilot.test.rero.ch/professional/records/patrons/detail/13053
Concerned item: https://ilspilot.test.rero.ch/professional/records/items/detail/2414861

> De : reroilspilot+310510000@gmail.com <reroilspilot+310510000@gmail.com>
> Envoyé : jeudi, 29 octobre 2020 00:01
> Objet : Avis d'échéance
> 
> Chère lectrice, cher lecteur,
> 
> Le délai de prêt des documents mentionnés ci-dessous arrive à échéance :
> Titre : Fragilité blanche : ce racisme que les blancs ne voient pas / Robin Diangelo Echéance : 29.10.2020 Note : Non prolongeable
> Vous pouvez consulter votre compte et prolonger la durée de prêt de vos documents à l'adresse : https://ils.rero.ch/rbnj/patrons/profile
> Avec nos compliments
> 
> BM Delémont - adultes
> Rue de l'Hôpital 47, 2800 Delémont

**Expected behavior**
The mention "Not renewable" should not be present.

**Context**
Tell us on what server did you spotted the issue, using with browser.

* server: ilspilot.test.rero.ch
* version: v0.12.0

**Additional context**
Proposed by pilot libraries

**Comment by BadrAly** [comment]
this is a `due_soon` notification not a `recall` notification, all seems normal here.

**Comment by BadrAly** [comment]
Problem is fixed in version `v.013`, see https://github.com/rero/rero-ils/commit/290dfd63c59b769dba48707c502c00b494c0c531
