### ISSUE TITLE
ILSPILOT: Add a subscription for patron

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1349]
Problem reported by Sentry:

`Add a subscription for patron#13076 ... it shouldn't happen !!`

ref: https://sentrydev.test.rero.ch:8443/organizations/sentry/issues/60703/?project=4&query=is%3Aunresolved&statsPeriod=14d

**Comment by zannkukai** [comment]
same as https://github.com/rero/rero-ils/issues/1317
