### ISSUE TITLE
Unable to create ebooks records when importing through OAI PMH

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1350]
When executing the scheduler task `invenio_oaiharvester.tasks.list_records_from_dates` to create ebooks records, Sentry report this error for some records:

`One of the parameters 'document_pid' or 'location_pid' or 'item_type_pid' is required`

An example of a record with error:

```
EBOOKS CREATE RECORDS: One of the parameters 'document_pid' or 'location_pid' or 'item_type_pid' is required. {'issuance': {'main_type': 'rdami:1001', 'subtype': 'materialUnit'}, 'identifiedBy': [{'type': 'bf:Isbn', 'value': 
'9782221251478'}, {'type': 'bf:Local', 'value': 'cantook-EDEN660274'}, {'type': 'bf:Local', 'source': 'cantook', 'value': 
'oai:ebooks.rero.ch:cantook-EDEN660274'}], 'type': 'ebook', 'language': [{'type': 'bf:Language', 'value': 'fre'}], 
'translatedFrom': ['dan'], 'title': [{'mainTitl...
```
ref: 
https://sentrydev.test.rero.ch:8443/organizations/sentry/issues/60752/?query=is%3Aunresolved

**Comment by iGormilhit** [comment]
@BadrAly We need to identify what is the exactly the error and document it a little bit.
