### ISSUE TITLE
serial pattern preview type error

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1351]
When a librarian or a system librarian pulls the holdings editor and tries to edit or create a new holdings patterns, Sentry reports this problem:

``` 
TypeError api_holding.pattern_preview
strptime() argument 1 must be str, not None
```

So it seems that  the `next_expected_date` is not sent to the backend at some point:

```
rero_ils/modules/holdings/api.py in _increment_next_prediction at line 401
patterns.get('next_expected_date'), '%Y-%m-%d')
```
ref: https://sentrydev.test.rero.ch:8443/organizations/sentry/issues/8983/?query=is%3Aunresolved

This could be related to the Taiga task: https://tree.taiga.io/project/rero21-reroils/task/1820?kanban-status=1224893 (editor sends many calls to the backend)

**Comment by iGormilhit** [comment]
@BadrAly We need to know what is exactly this error and document it a little bit.

**Comment by iGormilhit** [comment]
@BadrAly Is it still relevant. If not, you can close the issue, thanks.

**Comment by BadrAly** [comment]
Not a problem anymore. closing
