### ISSUE TITLE
The link to patron profil in the notification is not correct

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1353]
**Describe the bug**
In all notifications sent, there is a link to the patron profile. This link is wrong: for instance ilspilot, it is as follows: `https://ils.rero.ch/[org]/patrons/profile`

**To Reproduce**
See notifications sent.

**Expected behavior**
The link should be build according to the instance. For ilspilot: `https://ilspilot.test.rero.ch/[org]/patrons/profile`

**Context**

* server: ilspilot.test.rero.ch
* version: v0.12.0

**Additional context**
Proposed by pilot libraries

**Comment by rerowep** [comment]
Could be solved by setting env variable: INVENIO_RERO_ILS_APP_URL: 'https://ilspilot.test.rero.ch'
