### ISSUE TITLE
The patron loan transaction history does not always display the item and the document title.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1369]
**Describe the bug**

In the professional patron account, the fee tab does not always display the item link and the document title.

**To Reproduce**
1. Observed on this user: https://ilspilot.test.rero.ch/professional/circulation/patron/2050173843/fees

**Expected behavior**
* Item barcode/link should always be displayed.
* Document title/link should always be displayed

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

Proposed by the pilot libraries

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/98130472-935c9280-1eba-11eb-9edd-e7455e787f5b.png)

**Comment by benerken** [comment]
Checked in release 0.14.1
It's fixed.
