### ISSUE TITLE
In the pro patron account, the message for item in transit is not translated.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1376]
**Describe the bug**

In the pro patron account, the message for item in transit is not translated: "**Retour** The item is in_transit".

**To Reproduce**
1. Check-in an item that goes in transit

**Expected behavior**
Should be translated

**Context**
* server: ilspilot.test.rero.ch (version: v0.12.0) AND ilsdev.test.rero.ch (rero-ils version b43d054c, rero-ils-ui version 3f0237f9)

Proposed by the pilot libraries

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/98137610-79bf4900-1ec2-11eb-9d53-9979c3b04c54.png)

**Comment by AoNoOokami** [comment]
I reproduced the scenario and the item status is correctly translated.
