### ISSUE TITLE
CHECKOUT_4 or CHECKOUT_5 does not work as expected.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1379]
**Describe the bug**

I have an item in transit. It is requested by patron A. It is checked out for this patron *without reception at desk*. This situation leads to a problem:
1. either the request seems not to have been validated (if it was in transit to house). Consequence: it still appears in the requests.
1. or I have an red error message (see screenshot)

**To Reproduce**

Case 1
1. Take an item in transit to house
1. Add a request on it for patron A
1. Check out the item for patron A
1. See tab "Requests" of patron A
1. See item detailed view

Case 2
1. Take an item on loan by patron X
1. Add a request on it for patron A
1. Checkin the item so that it goes in transit for pickup
1. Check out the item for patron A
1. See error message

**Expected behavior**

At the checkout, the loan is automatically validated and received, so that it does not appear as a request anymore.

**Context**

* server: ils.test.rero.ch
* version: v0.13.0
* See [checkout form actions][1]

[1]: https://github.com/rero/rero-ils/blob/dev/doc/circulation/actions.md#checkout-form

Proposed by pilot libraries

**Screenshots**

Case 1: there are now 2 loans for the same patron:
![image](https://user-images.githubusercontent.com/8154915/98139849-f4896380-1ec4-11eb-9ed7-6fc23fd741ca.png)

Case 2: error message
![image](https://user-images.githubusercontent.com/8154915/98140367-a759c180-1ec5-11eb-896c-8676c772542d.png)

**Comment by BadrAly** [comment]
No longer a problem
