### ISSUE TITLE
Search terms in public view should not disappear when opening a detailed view

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1390]
**How it works**

In the public interface, the search terms are present in the main search bar in the brief view. When we click on a detailed view, they disappear.

**Improvement suggestion**

Search terms stay, even when we land on a detailed view, so that we can modify the search.

In the pro interface, this is already the case.

**Context**
Tested on ils.test.rero.ch (v0.12.0)

Proposed by pilot libraries

**Comment by iGormilhit** [comment]
The document detailed view of the public interface is not as dynamic as the professional interface is (Angular). I think that the query should be stored in some way…
