### ISSUE TITLE
"Enter" key in the main search bar confuses autocomplete suggestions with text entered.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1392]
**How it works**

When we type a search, a list of suggestions is displayed and our mouse by chance is on the list (without us clicking), a suggestion is highlighted and if we continue typing our search and then press the "enter" key, it launches the search with the selected suggestion unintentionally.

**Improvement suggestion**

"Enter" button should launch the search with the text inserted.

**Comment by PascalRepond** [comment]
This is standard behavior, closing as wontfix.
