### ISSUE TITLE
Clickable arrows enable to navigate to the next or previous detailed view

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1393]
**How it works**

On a document detailed view (public or professional), it is currently impossible to go the next result (detailed view) in one click.

**Improvement suggestion**

On a detailed view (public or professional), clickable arrows are present to navigate to the next/previous result.

This applies to documents.

Ideally, this applies also to all resources: import, late issues, vendors, ...

**Context**

Proposed by pilot libraries

**Comment by iGormilhit** [comment]
If this is actually doable, I would prefer a shortcut like `n` for next result, and `p` for previous result, as the arrows are useful to navigate in the page.

**Comment by pronguen** [comment]
> If this is actually doable, I would prefer a shortcut like `n` for next result, and `p` for previous result, as the arrows are useful to navigate in the page.

I complete with "clickable arrows". An interface element is needed.
