### ISSUE TITLE
The tab displayed when opening a detailed view seems to be random.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1394]
**How it works**

In the public view, when opening a detailed view, we don't understand why a tab is opened rather than another.

**Improvement suggestion**

We should always land on the tab "Get".

**Context**

Proposed by pilot libraries
Tested on ils.test.rero.ch (v0.13.0)

**Comment by iGormilhit** [comment]
I suspect that for an obscure reason, the last opened tab is stored somewhere. Maybe @Garfield-fr or @AoNoOokami have something to say.

**Comment by AoNoOokami** [comment]
It should be stored, but as far as tested, the javascript function that does that disturbs the display of cover thumbnail. At least, when I comment the function, the cover thumbnail is displayed. That's why I think this issue is related to https://github.com/rero/rero-ils/issues/1396
