### ISSUE TITLE
Two result counts are not understandable by end users

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1395]
**How it works**

In the public interface, two result counts are not understandable by end users. See screenshot.

**Improvement suggestion**

Display the real result count only in the tab. 
If we display it below, hide the result count of the tab, even if we then have no result count for the other tabs (Persons, ...).

**Context**
Proposed by pilot libraries
Tested on ils.test.rero.ch (v0.12.0)

**Screenshot**

![image](https://user-images.githubusercontent.com/8154915/98247462-f2321280-1f73-11eb-84c7-754549ff1a1b.png)

**Comment by iGormilhit** [comment]
I think that the number of results displayed in the tab title is wrong: it's the total records count, which makes no sense here.
