### ISSUE TITLE
Thumbnails and document types are not displayed in the public detailed view.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1396]
**Describe the bug**

Thumbnails are not displayed in the public detailed view.

**To Reproduce**

1. Open a public detailed view.

**Expected behavior**

They are displayed, as in the brief view, with the document type below.

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

AND ils.test.rero.ch (v0.13.0)

Proposed by the pilot libraries

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/98248399-28bc5d00-1f75-11eb-866f-ef5b12fe97c7.png)

**Comment by iGormilhit** [comment]
Seems fixed in `v0.14.0`
