### ISSUE TITLE
"Show more" button displayed wrongly and problematic counter

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1400]
**Describe the bug**

For documents with many items, like mangas (ex: R005112192), the counter is not displayed correctly and the "Show more" button does not work (professional view).

**To Reproduce**

1. Open the document R005112192 in ilspilot.test.rero.ch

**Expected behavior**

The five first items are displayed (sorted by field enumerationAndChronology). We can click on "Show more" to display other items.
The counter is correct.

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

Proposed by the pilot libraries

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/98268064-5d87de80-1f8c-11eb-9a93-1dfa245e7782.png)

**Comment by zannkukai** [comment]
I think it's solved in `v0.13.1`.

**Comment by iGormilhit** [comment]
To be verified when https://ilspilot.test.rero.ch will be in RERO ILS `v0.14.0`.

**Comment by iGormilhit** [comment]
@zannkukai @pronguen 
This is only partially fixed in `v0.14.1`. Clicking on the *show more* link works. But the counter doesn't display anything else than the variable.

![ksnip_20201210-072419](https://user-images.githubusercontent.com/1557213/101729648-75351400-3ab0-11eb-85fd-77287e50e753.png)

**Comment by zannkukai** [comment]
problem with : https://ilspilot.test.rero.ch/professional/records/documents/detail/877565
No problem with : https://ilspilot.test.rero.ch/professional/records/documents/detail/617709
