### ISSUE TITLE
Prevent the enter key to submit the form in some fields that may be filled though a scanning device

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1421]
**How it works**

When editing a resource in a form, using the "enter" key saves the form. This is not the case for text area input fields.
The user does not expect this behaviour.

When entering an ISBN with a scan device configured for checkout; the device automatically sends an "enter" to the system. When this happen in a document editor form, the form is submitted but should not.

**Improvement suggestion**

Disable the default enter key behavior in specific fields such as identifiers, or barcodes:
* document: `identifiedBy.value`
* item: `barcode`
* patron: `barcode`
* ill request (pro interface): *Identifier*

Disable the enter key for the whole ILL request form in the public interface (the ideal enhancement, for later, is described here: https://github.com/rero/rero-ils/issues/1771)

**Comment by jma** [comment]
I disagree. This is a default behaviour and a best practice to submit a web form using the enter key. This is the case for example on every google form (login, etc.). Moreover since the submitting the form display the validation error it still useful. We needs to fix this wrong behaviour for scan device if it is needed.

**Comment by pronguen** [comment]
@iGormilhit What is your opinion? Should we close this issue, considering that this is a setting to do in the scan device?

**Comment by iGormilhit** [comment]
@pronguen I'm pretty sure that at least once I've encounter the issue of hitting the enter key to do something and was surprised to see the form being submitted.

@jma is right, but I think we need to identify in which situation hitting the enter key does not what the user is expecting. I'm going to make some tests and verify about a barcode scanner.

**Comment by pronguen** [comment]
@jma @iGormilhit I know that it could be a default behaviour in a standard environment. But in libraries, there are barcodes and scanning devices everywhere.
It is important for the checkin/checkout that the device automatically sends an "enter", so that the librarian doesn't have to do for each transaction: scan (with device) + enter (with keyboard).
So imagine a library desk where the librarian catalogues books and do checkin/checkout in parallel. It is an issue.

**Comment by iGormilhit** [comment]
@pronguen I agree. I think that at least in the forms like documents, we could at least *try* to prevent the enter key to submit the form **in specific fields** such as Identifiers.

Thus we will keep:

1. The standard behavior, except for specific fields.
1. The standard behavior in the circulation form, where it's needed.

I propose to transform this issue in "Prevent the enter key to submit the form in some fields". And then to provide a list in the description of the issue.
