### ISSUE TITLE
Agent is difficult to understand in the provision activity of the document editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1423]
**How it works**

Agent is difficult to understand in the provision activity of the document editor.

**Improvement suggestion**
The value stays `bf:Agent` but the label in the editor is replaced by "Publisher, printer, etc."

**Screenshot**

![image](https://user-images.githubusercontent.com/8154915/98565682-2aa45a00-22ae-11eb-9095-346a289676d2.png)

**Comment by iGormilhit** [comment]
The document JSON schema is wrong : https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json#L155

```
"form": {
                  "type": "selectWithSort",
                  "options": [
                    {
                      "label": "Place",
                      "value": "bf:Place"
                    },
                    {
                      "label": "Agent",
                      "value": "bf:Agent"
                    },
                    {
                      "label": "Date",
                      "value": "Date"
                    }
                  ],
```
should be:
```
"form": {
                  "type": "selectWithSort",
                  "options": [
                    {
                      "label": "bf:Place",
                      "value": "bf:Place"
                    },
                    {
                      "label": "bf:Agent",
                      "value": "bf:Agent"
                    },
                    {
                      "label": "bf:Date",
                      "value": "Date"
                    }
                  ],
```
And then in weblate, we can translate `bf:Agent` as we want. This is the case for many enumeration in the document JSON schema, and maybe elsewhere.

See https://github.com/rero/developer-resources/blob/master/data/jsonschema.md#enum
