### ISSUE TITLE
Display a hyper text link when adding a $ref link to another resource in the editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1425]
**How it works**

When establishing a $ref link to another resource in the editor (for instance a contribution link from a document to an author), we cannot click on the link.

**Improvement suggestion**

When the link is created, it would be useful to be able:
* to click on the $ref in order to check if the linked resource is the right one;
* [nice to have] to hover the $ref and have a brief description of the linked resource in a tooltip.

**Comment by jma** [comment]
Can you provide and example?
