### ISSUE TITLE
Item location and category update when parents holdings is changed.

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1436]
When I change the location or circulation category of the holdings, this same data is not changed in the item/issues. It should. Rather: the location should be removed from the issue/item.

* version: `v0.14.0`

**Comment by BadrAly** [comment]
This requires spec. For the `standard` holdings, when the `holding.location` is changed, a new holding is created and the items are attached to the new holding

**Comment by iGormilhit** [comment]
@BadrAly @pronguen I have two questions:

1. What is the priority of this issue? Low, medium, high?
1. How the specifications will be documented? Here or in a user story?

Thanks.

**Comment by zannkukai** [comment]
@BadrAly I think it's a bad idea to remove the "location" field from the item. If we remove this field from the `Item` resource JSON schema, the the editor will not present it for the user (create/update). It seems an huge work to dynamically add a field in the form if this one isn't present into the schema :: complex for add the field, populate the form, save the form, ...

I suggest this solution : When an holding is updated, detect if the location field change. If it changes, then update the related items (without updating the parent holding - itself). After all items are updated, then continue the normal process of any resource update.

**Comment by pronguen** [comment]
Issue updated to include also the field "circulation category", with the same problem.

**Comment by BadrAly** [comment]
Problem in production database related to this. 
First action is to correct the holdings/items concerned by this bug in production.

**Comment by pronguen** [comment]
Grooming 22.02.22:
* identify if this is solved in bib.rero.ch (regular task)
* evaluate a solution of live batch corrections with alternative and efficient tools
