### ISSUE TITLE
Wrong display of some fields on the circulation interface

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1447]
**Describe the bug**
The fields location and notification are not correctly aligned/displayed in the circulation interface.
It seems to be related to the resolution of the screen.

**To Reproduce**
1. Log in as a librarian.
2. Find a user.
3. Check his loans

**Expected behavior**
The display should be the same for any resolution.

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]
* version: 0.14*

![image](https://user-images.githubusercontent.com/12396034/99379921-90559f00-28c9-11eb-8b6f-f047d6cc8455.png)

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by iGormilhit** [comment]
@ManaDeweerdt May I ask what browser do you use, if your browser window is extended or not, the resolution of your screen? I cannot reproduce it with my configuration.

**Comment by ManaDeweerdt** [comment]
> @ManaDeweerdt May I ask what browser do you use, if your browser window is extended or not, the resolution of your screen? I cannot reproduce it with my configuration.

I use Chrome. Resolution 1920 x 1080.
I've just checked the behaviour in firefox and it works. Actually, the text size is smaller than Chrome... The zoom is the same : 100%
In Chrome, I need to zoom to 90% to see correctly the fields aligned.

**Comment by iGormilhit** [comment]
@ManaDeweerdt Thanks. On my side, using Firefox, the issue appears from a screen width of `992 px` to `1336 px` approximatively.

![rero-ils-circulation-display-issue](https://user-images.githubusercontent.com/1557213/100712883-61502a80-33ab-11eb-98a2-ab5d35475a3e.gif)

**Comment by ManaDeweerdt** [comment]
It works fine in 1.0.0.
It was related to my browser parameters.
