### ISSUE TITLE
Waiting time for CSV export (inventory list)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1456]
**How it works**

The CSV export of the inventory list has an important waiting time, leading very often to a server time-out, even for less than 10'000 items.

**Improvement suggestion**

* Solve performance issue if possible.
  * If possible, extent the waiting time of the server (let more time for the server to respond).
* Put a confirmation message, with a warning "Export of more than XXX items can lead to a server time-out."
* Put a spinner after the launch of the export.

**Comment by iGormilhit** [comment]
Related to https://github.com/rero/rero-ils/issues/1329.
