### ISSUE TITLE
Language menu in the public interface should not be in "Menu"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1466]
**How it works**

Changing language in the public interface is done through the menu "Menu". This is not logical for the end user.

**Improvement suggestion**

In the public interface, the menu "Menu" is renamed into "Language" (or ideally the current language is displayed). See image below. All other options are available in the menu "Tools" or in the footer.
![image](https://user-images.githubusercontent.com/8154915/99656792-a1371980-2a5d-11eb-97b3-5fb673e90ae4.png)

In the pro interface: to be decided.
* Ideally: language is a setting in the user profile, accessible via the user account
* Where to place the "Help"? In the user profile, in the first level?

**Comment by iGormilhit** [comment]
@pronguen My 2 cents:

- Professional interface, the user menu should contains:
    - Switch to public interface
    - Access to the RERO ID
    - Log Out
    - Access to help (shortcut `h`)
- The professional interface language setting could indeed be in a settings section of the RERO ID. But then in the user menu, the entry to the RERO ID should be clearer (my account?), or we could add an entry to access the settings directly.

For the language switch of the public interface, I find your screenshot very good.

**Comment by zannkukai** [comment]
Job done for public interface.
For pro-interface, it will be linked to a "mini US" to refactoring the menu (adding new entry will cause spaces problem for medium screen). Maybe this US could be schedule last works week of December (during days used to fix issues) ? @Garfield-fr and myself are open to implement this refactoring :-)
