### ISSUE TITLE
Creating a patron with a username and an email corresponding to two different invenio user cause unpredictable errors

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#1467]
**Describe the bug**
When a patron record is created by a librarian the system try to link an existing invenio user account to this patron record. If the username and the email correspond to two different invenio users, the system create the link with only one invenio user account.

**To Reproduce**
1. Register a new rero user with a username.
2. Register a second rero user with an email address.
3. Log in with a librarian.
4. Create a new patron with the username and email used to register the two previous rero users.
5. No errors is notified.

**Expected behaviour**
The librarian should link explicitly a patron to a invenio user account.

**Comment by iGormilhit** [comment]
Will be addressed by [US 1467][1].

[1]: https://github.com/rero/rero-ils/issues/1467
