### ISSUE TITLE
When creating a user from the admin interface, a "reset password" e-mail should not be sent.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1468]
**How it works**

When creating a user from the admin interface, an e-mail is sent to this user to reset his/her password.

**How it should works**

* If the user is saved with the password field empty, the password is automatically set with the birth date. An e-mail is sent to the patron to reset his/her password.
* If the user is saved with a specific password in the field, no e-mail is sent to the patron to reset his/her password.

**Context**

Version 0.14.0

**Comment by jma** [comment]
Can you validate this with UCL?

**Comment by pronguen** [comment]
Decision of the PO: if the field is not empty, no e-mail is sent to the patron
