### ISSUE TITLE
Cannot save a prediction pattern for an existing holding

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1471]
**Describe the bug**
When I load a prediction pattern on an existing holding and try to save, it spins forever.
It works for a new holding.

![image](https://user-images.githubusercontent.com/12396034/99685255-ab1f4380-2a82-11eb-8e68-2e8f9dc48383.png)

**To Reproduce**
1.  Find a serial.
2. Edit the holding and load a prediction pattern. Ex : https://ils.test.rero.ch/professional/records/holdings/edit/2012?source=templates&pid=31
3. Try to save.

**Expected behavior**
We should have a reason why it doesn't save. Fields missing?

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v0.14.0` 

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by BadrAly** [comment]
After analysis with @jma:

1. The template does erase the link with the parent record. This problem normally can be duplicated for other resource like `item`
2. Maybe it is wise not to allow using template on existing records.

**Comment by pronguen** [comment]
@BadrAly I would disable template for existing records. If it is possible and if it is the easiest way.

**Comment by JoelleDosimont** [comment]
In the life of a serial, it's common to have a change in prediction when frequency changes. In this case, the use of template should help to create a new prediction (frequency and predictions patterns). But it should not change the other informations : Available collection, notes, vendor, number of claimed, ...
Don't know what is possible here...

**Comment by zannkukai** [comment]
> In the life of a serial, it's common to have a change in prediction when frequency changes. In this case, the use of template should help to create a new prediction (frequency and predictions patterns). But it should not change the other informations : Available collection, notes, vendor, number of claimed, ...
> Don't know what is possible here...

The logic for template is now to load in the editor the data from the template (all previous values are lost). In this case, you suggest to "override" only the data provided by template (but keep possible existing other values). 
1) This behavior introduces a lot of changes about template implementation
2) Is this behavior should be implemented for all resources or only holding resource ?

**Comment by JoelleDosimont** [comment]
> The logic for template is now to load in the editor the data from the template (all previous values are lost). In this case, you suggest to "override" only the data provided by template (but keep possible existing other values).
> 
>     1. This behavior introduces a lot of changes about template implementation
>     2. Is this behavior should be implemented for all resources or only holding resource ?
I guess what I'm looking for is something that allows : 
1. to create a new record with a template (that's what is possible now).
2. to merge a record (bib, item, holding... don't know for the patron) with a template. It would add the fields in the template, but keep the existing values in the record...  It would be usefull, but it's more a "nice to have", we can work without it for now.
