### ISSUE TITLE
Why a search request "ânes" without quotes does return a document with "ans"?

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1475]
**Describe your question**

See screenshot. Why a document with "ans" in the abstract is returned? Why another document with "ans" in the title is not returned by the same query "ânes"? Is there a way to improve this?

In general, it seems that diacritics are taken into consideration ("vélo" returns different/less results than "velo"). Why?

**Context**
ils.test.rero.ch, v0.14.0

**Screenshots**
The search and its results (with filter "Books")
![image](https://user-images.githubusercontent.com/8154915/99703251-2c80d100-2a97-11eb-90aa-30503cac2daa.png)

One result of each
![image](https://user-images.githubusercontent.com/8154915/99703465-6ce04f00-2a97-11eb-85f5-886e3c8167c8.png)

**Comment by iGormilhit** [comment]
Related to https://github.com/rero/rero-ils/issues/1474.
