### ISSUE TITLE
The counter of the tab 'to pickup' is not refreshed automatically

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1482]
**Describe the bug**
In the circulation interface, the counter of the tab 'to pickup' is not refreshed instantly.
It is not the case for the other tabs like CI/CO, pending.
![image](https://user-images.githubusercontent.com/12396034/99812861-40840b80-2b47-11eb-83fc-d2655c37e71e.png)

**To Reproduce**
1. Log in as a librarian or system librarian.
2. Go to the requests main page and validate some requests.
3. Click on the user who made the request.
4. Make checkouts of the items from the 'to pickup' tab.
5. See if it refreshes the tab.

**Expected behavior**
The count must be refreshed instantly.

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]
* version: `v0.14.0`*.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by iGormilhit** [comment]
This concerns only *this* counter, or all of them?

**Comment by ManaDeweerdt** [comment]
Yes it seems to be just the 'to pick up' tab.
