### ISSUE TITLE
document: index both ISBN 10 and 13 format

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#1486]
Today, a librarian creates a new document and indicates an ISBN-10, then save it.
Another librarian or a patron looks for the same document using the ISBN-13, he gets no result ! 

**Improvement suggestion**
the system should index ISBN both in 10 and 13 position, to be able to retrieve the document using both format. 

Ex: 
ISBN-10 : 0740748475
ISBN-13 : 9780740748479

**Comment by rerowep** [comment]
It would be nice if we have a format check for the different identifiers. The editor should use this checks.
