### ISSUE TITLE
Series statement, color content, mode of issuance should be translated on professional interface

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1488]
**Describe the bug**

On professional interface, document detailed view (description tab), followings strings should be translated:
* Series statement (the label)
* Color content (the content, it is a code)
* Mode of issuance (the content, it is a code)

**To Reproduce**
Open a document detailed view and add a series statement, a color content, a mode of issuance.

**Expected behavior**
They are translated.

**Context**

* server: ils.test.rero.ch (v0.14.0)

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/99989709-3cf4bc80-2db3-11eb-9c6f-9b9fddc68b3e.png)

**Additional information**

- Serie statement [translated in French][1].

[1]: https://github.com/rero/rero-ils/blob/5d9ba23e06c5bae9d879784a1c7c9591c2f00d46/rero_ils/translations/fr/LC_MESSAGES/messages.po#L6479

**Comment by zannkukai** [comment]
The document JSON schema allows 2 values for color content : `rdacc:1002`, `rdacc:1003`. These string are not yet extracted for translation process. The PR https://github.com/rero/rero-ils/pull/1494 correct this problem. Both terms will be available for extraction with `v0.15`
