### ISSUE TITLE
Fields completed are marked with a specific icon or color in the document editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1489]
**How it works**

It is difficult to navigate in the document editor. There are a lot of fields.

**Improvement suggestion**

Proposal 1 (rejected):
Fields of first level that are already completed could be marked in a different color, in the right navigation panel. In that way, the librarian oversee quickly what field must still be catalogued.
-> Is not useful since the fields are usually filled in as they are added

Proposal 2:
In the right navigation panel, mark
* the name of the field where the mouse cursor is active (for instance the name is preceded by a small pen icon)
* the name of the field where the scroll is (for instance the name is blue)

**Comment by jma** [comment]
Is this still valid as now when the submit button is pressed we see all the field to be filled.

**Comment by pronguen** [comment]
@jma The right panel is almost unusable; it does not really help to navigate. Various things can be done:
1. mark in the right panel with a highlight or a bold script the current displayed field, so that the user knows where he is vertically.
2. mark the fields that are still empty.
3. other?
