### ISSUE TITLE
No feedback is given to the user if the email is not confirmed

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#1490]
**Describe the bug**

On the login page if the email is not confirmed no warning or error message is given to the user.

**To Reproduce**

1. Create a fresh RERO ID account
2. Logout
3. Try to login without having confirmed the email address

**Expected behavior**

An error message should be displayed to inform the user that he has to confirm his email address.

Version `v.014.1`

**Comment by iGormilhit** [comment]
@jma I've used the `P: Low` label to set the priority. What do you think ? Is it low, medium or high?
