### ISSUE TITLE
Add a pager to the brief view of the import from BnF

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1491]
**Is your feature request related to a problem? Please describe.**

Currently, when there are more than 10 results from the import, we see only the 10 first. The only way to see the others is to change the number of results displayed.

**Describe the solution you'd like**

A pager

**Describe alternatives you've considered**
Scroll down and it loads more results. But a pager would be coherent with the other brief views.

**Comment by iGormilhit** [comment]
This should be better documented on the professional help.

**Comment by pronguen** [comment]
Due to technical challenges, we won't do this enhancement in the middle-term. We documented the import feature and explain how to deal with it: https://ils.test.rero.ch/help/catalogage/#importer-un-document
