### ISSUE TITLE
Cancel button does not work on the account profile RERO_ID

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1498]
**Describe the bug**
If you visit the `My account` section of the new `RERO_ID` menu available for patron users, the `cancel` button does not work. Is it supposed to take you to the previous page? or cancel changes?  

Even if you click on the button `Update profile`, the record is updated but the editor remains open.

**To Reproduce**
1. Go to 'https://ilsdev.test.rero.ch/'
2. Click on 'Account' then `Login'
3. Login as a patron for example `reroilstest+simonetta@gmail.com`
4. click on the patron initials `SC` then `RERO ID`
5. Try to `Cancel` or `Update profile` buttons, the editor remains open.

* server: [ils.test.rero.ch][1] and [ilsdev.test.rero.ch][2]
* version:`v0.14.0`
* browser: all

**Screenshots**

<img width="821" alt="Screenshot 2020-11-24 at 16 29 25" src="https://user-images.githubusercontent.com/26998238/100114946-3ed18500-2e72-11eb-9ac7-51023111685c.png">

**Comment by iGormilhit** [comment]
@BadrAly I think it works as expected. It reload the form without the unsaved changes, which is what I expect.

**Comment by BadrAly** [comment]
Not valid anymore. closing
