### ISSUE TITLE
The canceled request is displayed in the history tab of the professional patron account

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1516]
**Describe the bug**

The canceled request is displayed in the history tab of the professional patron account. In the public patron account, it is not. 

Actually it says checkin/checkout but it is not correct because it is just a request. [LATER? we should be able to differenciate the transactions : request, checkin, checkout ...] This problem is linked to https://github.com/rero/rero-ils/issues/1227.

public interface:
![image](https://user-images.githubusercontent.com/12396034/100464497-0201ca00-30ce-11eb-9c2e-355ead4e4aa2.png)

professional interface:
![image](https://user-images.githubusercontent.com/12396034/100464460-f1515400-30cd-11eb-84d9-fd99e913c1a2.png)

**To Reproduce**

1. Log in as a patron and check your profile. Ex: Katie.
2. Cancel a pending request.
3. Compare the history tab of the public & professional interface.

**Expected behavior**

We should have the same information both side: no display of the cancelled requests in the history tab.

**Context**

* server: [ils.test.rero.ch]
* version: `v0.14.1`

**Comment by iGormilhit** [comment]
I think there are three points:

- What should be displayed in the history tab (pro/public).
- How to display request information and cancelled request information.
- Quicky identify transaction type.

**Comment by ManaDeweerdt** [comment]
Tested on V1.14.0: seems not to be the case anymore. The canceled requests are not displayed in the history tab.
