### ISSUE TITLE
circulation: block checkout/renew/request when patron has unpaid subscription

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1530]
**How it works**

In case of a subscription, there is no blocking.

**Improvement suggestion**

A patron with unpaid subscription fees is blocked (checkout/renew/request). The corresponding message is displayed in the public patron account, circulation UI after trying to do a transaction, pro patron account.

To clarify: have a setting in the patron type to choose to block or not the patrons with an unpaid subscription?

*Note: the end of the subscription is not linked to the expiration date.*

**Comment by iGormilhit** [comment]
I my opinion:

- X days after the end of the subscription, circulation should be blocked. This should be set in a circulation policy.
- When a patron account reach the expiry date, the account will be reactivate
    - maybe the next time the patron interact with the online acount
    - or when the patron goes to the circulation desk.
    - X months after the deactivation of the patron account, if the patron didn't do anything, the account is deleted.

Of course some notifications should be sent.

**Comment by zannkukai** [comment]
@pronguen is this new restrictions should be activated by default or not ?

**Comment by pronguen** [comment]
@zannkukai I would say yes: it is activated by default when creating a patron type.
