### ISSUE TITLE
Fees : a librarian shouldn't be able to resolve fees of item not belonging to the login location

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1533]
**How it works**

Currently, we can resolve a fee for all locations of the organisation.

**Improvement suggestion**

Add a dropdown in the 'pay all' button : 'pay all for my library'. 

Additionally (public and pro interface): 
Add a new column 'library' between the category and the total fee amount.

**Comment by zannkukai** [comment]
> Additionally (public and pro interface) :
> Add a new column 'location' with the library code.

Where ? how ?
