### ISSUE TITLE
Notifications field not in chronological order

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1549]
**Describe the bug**

Sometimes, the content of the notifications field in the circulation interface is not in chronological order.

![image](https://user-images.githubusercontent.com/12396034/101488793-56276c80-3960-11eb-92f9-57b6fe8f5904.png)

**To Reproduce**

1. Find a user with multiple fines. Ex Casalini, Simonetta
2. See the notifications field in the checkout/checkin tab/

**Expected behavior**

Notifications should be in the chronological order.

* server: ils.test.rero.ch
* version: `v0.14.1`

**Comment by iGormilhit** [comment]
Are we sure that in that specific case, the date are different? Maybe @BadrAly or @zannkukai can tell.

**Comment by zannkukai** [comment]
Currently it seems notifications are sorted on 'bestmatch'. I will investigate to sort on most recent

**Comment by ManaDeweerdt** [comment]
Example on the UCL instance:
![image](https://user-images.githubusercontent.com/12396034/101609559-634b6680-3a07-11eb-9698-900c184843a5.png)
