### ISSUE TITLE
Date exceptions : repeat

### ISSUE THREAD

**Issue by NicolasLabat** [rero/rero-ils#155]
As an example, to add the 25.12.2018 as a closed day each year, the librarian has to activate the "Repeat" button and chose "Yearly" and then the value "1".
It's seems a bit confusing. The librarian can expect that the number "1" means the number of years the rule applies.
The display should be clearer. For example : 
Repeat every [number] day(s)/week(s)/month(s)/year(s)

**Comment by pronguen** [comment]
Simplify the UX based on:
![image](https://user-images.githubusercontent.com/8154915/54533517-a8ee1300-498a-11e9-9bba-272d7eed7a05.png)

Or just abandon the option to set the repetition frequence
