### ISSUE TITLE
Display items/holdings on top according to the login library in the professional view

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1563]
**How it works**

Currently, items and holdings are sorted according to their pid.

**Improvement suggestion**

In the pro interface, holdings of the librarian login library are displayed first.

Concerning the public interface, the enhancement is in https://github.com/rero/rero-ils/issues/1740.

**Comment by iGormilhit** [comment]
In `v1.0.0` the holdings sorting is not as this issue described it.
