### ISSUE TITLE
Local fields shouldn't be displayed in the 'import from the web' document view

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#1564]
When a document detailed view is shown from the "import from the web" search page. The local fields are presents, but it does not make sense as the document is not yet created.

**To Reproduce**

- go to the professional view
- go to the import from the web page
- put a random search
- pick one results
- the local fields are presents

**Expected behavior**

The local fields should not be present in the import detailed view.

**Context**

* [ilsdev.test.rero.ch][2]
* version: `v0.15.0`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/127249/102221753-ceeb7300-3ee2-11eb-8b2e-f39527908711.png)

**Comment by iGormilhit** [comment]
Fixed in future `v1.2.0` release.
