### ISSUE TITLE
Resolve weblate issues

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#1566]
**How it works**

On weblate, many strings have been commented and need to be fixed:

- `rero-ils`: https://hosted.weblate.org/translate/rero_plus/rero-ils/fr/?q=label:%22Source%20needs%20review%22
- `rero-ils-ui`: https://hosted.weblate.org/translate/rero_plus/rero-ils-admin/fr/?q=label:%22Source%20needs%20review%22

**How it should works**

Fix this issues in the source code.

**Comment by comradekingu** [comment]
I had a go in #1592 and https://github.com/rero/rero-ils-ui/pull/482
