### ISSUE TITLE
Checkout at fixed date doesn't allow to choose the current date

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#1574]
**To Reproduce**

Go to a circulation tab for any patron in the professional interface.
In the "circulation settings" button, try to selected a checkout fixed date with the current date as value.
The system will notify that the current date is a past date 

![image](https://user-images.githubusercontent.com/10031585/102489872-5f09f380-406e-11eb-8d6b-f1bb34f174fe.png)
 
**Expected behavior**

A fixed date checkout should be possible on the current date

**Comment by BadrAly** [comment]
The problem can also be reproduced also when:
1. a checkout of an item for a patron when the `cipo` is set for same-day
2. the system sends incorrect information (or calculate wrongly)  for the `loan_start_date`
![image](https://user-images.githubusercontent.com/26998238/109504023-4faa1c00-7a9b-11eb-8468-5f1c80cad070.png)
