### ISSUE TITLE
Help: add a link to home page (or ideally a table of content)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1578]
**How it works**

After having solved this issue (https://github.com/rero/rero-ils/issues/1289), it is not possible anymore to return to the help home page.

**Improvement suggestion**

* add a link to home page
* or ideally add a table of content of the help (and not only of the page). See the Github wiki for instance.

**Context**

In this issue (https://github.com/rero/rero-ils/issues/1289), the grey navigation bar was removed for all roles except "editor". If a table of contents is too complex, we can reintroduce the navigation bar only for librarian/system librarian, ideally without the "Files" button.

**Comment by iGormilhit** [comment]
Fixed by https://github.com/rero/flask-wiki/pull/26.
