### ISSUE TITLE
Improve person detailed views (professional interface)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1597]
**How it works**

* In the corporate bodies' detailed view, a field "id" with a link to the external authority file exists. This is not the case for persons.
* The variant name is displayed before the authorised access point.

**Improvement suggestion**

*Note: mockup is necessary for this US*

* Display the person ID with a link to external authority file
* Display the authorised access point just before the variant name(s)
* Add the biographical information
* Make the source tables expandable/reduceable
* Shorten the variant name list, and add a "Show more" option

**Comment by JoelleDosimont** [comment]
Maybe it's also usefull to add the "Biographical information" in the professional interface ?

**Comment by PascalRepond** [comment]
Not enough precision in the specs and is low priority, closing as not planned.
