### ISSUE TITLE
Add authority link to contributor suggestions in the document editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1598]
**How it works**

In field `contribution`, the autocomplete is difficult to use, for instance with homonyms. The user does not know which person to select.

**Improvement suggestion**

A link (that opens in a new tab) to the person detailed view (in RERO ILS or in external authority file) exists for each suggestion, so that the user can open it, check if it is the right authority, come back and validate his/her choice.

**Comment by iGormilhit** [comment]
I think this should be discussed with developpers in order to choose the best solution.

**Comment by iGormilhit** [comment]
After a discussion with @jma, the @pronguen proposition is indeed the easiest. At least when the contributor record already exists in RERO ILS. Otherwise we either need a public view on MEF or to point to the original record on IdRef or GND.
