### ISSUE TITLE
Github actions test stops with an error related to test_document_boosting

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1603]
This is a random problem, reported at least by two persons, @BadrAly  and @rerowep .

The github actions test fails with the following error when executing the test `test_document_boosting`:

```
AssertionError: assert ebook4 == ebook1
```

See screen capture for the exact error.

If you ask to re-run all the tests again, all goes well.

**To Reproduce**

1. Push a pull request to the rero-ils project
2. Sometimes the Github action fails with the error above

* version: `v0.15.0` 

**Screenshots**

![](https://files.gitter.im/5b1fb68fd73408ce4f9d0e08/JiIe/Screenshot-2021-01-12-at-16.49.54.png)

**Comment by zannkukai** [comment]
resolved
