### ISSUE TITLE
Provision activity has no country for articles

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1617]
**How it works**

The field `provisionActivity.place` has no country and canton for articles and maybe other document types.

Observed JSON (ex: R004193446)
```json
"provisionActivity": [
      {
        "_text": [
          {
            "language": "default",
            "value": ""
          }
        ],
        "startDate": 1998,
        "type": "bf:Publication"
      }
    ]
```

**How it should works**

It contains country and cantons. Check it for all documents.

**Context**

Tested on ilspilot.test.rero.ch (v.0.14.1).

**Comment by iGormilhit** [comment]
Added to [RERO migration: final load][us].

[us]: https://tree.taiga.io/project/rero21-reroils/us/2107
