### ISSUE TITLE
Ease the process to add several short item in the editor

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#1623]
**How it works**

In the editor, when I have to add items in a list, for the second and the following items, I have to click on the icon to add a field, type the value, click on the icon again, and so on. It can be cumbersome in some case, for instance to add several subjects to a document, or to had items in a collection. There must be many cases like this.

https://user-images.githubusercontent.com/1557213/105333013-27421e80-5bcd-11eb-8e48-d0e715391eb7.mp4

**Improvement suggestion**

There are several solutions, either to add a new field with the "enter" key, or to separate items by coma (or another character).

https://user-images.githubusercontent.com/1557213/105333053-30cb8680-5bcd-11eb-91c7-f03e1a01c2d0.mp4

https://user-images.githubusercontent.com/1557213/105333070-33c67700-5bcd-11eb-9a0b-efaf417ea8bd.mp4

**Comment by jma** [comment]
How to choose the right separator?
