### ISSUE TITLE
Enhance the holdings editor and display

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1642]
After implementing the first version of the complete holdings record. Some enhancement to the data model and editor are given by the group PO.

Enhancement requests are detailed in the PR: https://github.com/rero/rero-ils-ui/pull/501

1. Display exactly the same holdings fields in the document detailed view than in the top section of the holdings detailed view. Currently, the missing issues for ex. should be displayed in the top section of the holdings detailed view (see image).

![](https://user-images.githubusercontent.com/8154915/105847792-5e09a180-5fde-11eb-8eb7-ed5cd4fa2f56.png)

2. For these 4 fields (Collection disponible, Contenu supplémentaire, Index, Fascicules manquants)
   * Group them in the holdings editor
   * Put them in text-area so that line breaks are allowed
   * Display line breaks in the public and pro interface

3. When a holding is masked, I should see the masked information in the professional interface (the only way to see this is currently to edit the holding).

4. the order of the fields can be sort differently (maybe to group certain type of information together : collection, acquisition, reclamation, prediction, binding, …).

5. The holdings' notes have to be more visible when recieving issues: the Notes fields should be displayed in the main tab of the holdings' detailed professionnal view. 

![ilcpkjpeljcjnjaj](https://user-images.githubusercontent.com/50177009/122172815-72f9ab00-ce81-11eb-8275-cbf0cd911580.png)

**Comment by JoelleDosimont** [comment]
With this enhancemet, we could also take the opportunity to transform the following areas into a "text area" (to allow line breaks) : Available collection, Supplementary content, Indexes, Missing issues.

**Comment by PascalRepond** [comment]
Following a question from a librarian about holding notes, most of these notes have to be more visible when recieving issues wihtout having to switch tab. I would suggest to display them in the first tab of the holdings detailed view (see image below), as well as in the "details" tab. 

![ilcpkjpeljcjnjaj](https://user-images.githubusercontent.com/50177009/122172815-72f9ab00-ce81-11eb-8275-cbf0cd911580.png)
