### ISSUE TITLE
Receive an issue: confusion between the status date and the date of receipt

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#1654]
**Describe the bug**
When you manually change a status with "Receive and edit this issue", the status date is not shown. A "date of receipt" is indicated, but this if the status is "late", this issue is not yet received (it's the status date, not the date of receipt).

**To Reproduce**
1. Find a serial with expected issues.
2. Click on 'Receive and edit this issue'.
3. Change the status to "late" and save.

**Expected behavior**
The status date should shown even when the status is changed manually (it's ok with "quick receive").
The date of receipt should only be used for the "received" status. If the issue is late or claimed, the date of receipt should be "Not yet received".

**Context**
server: [ils.test.rero.ch][1] (v. 0.15.0) and [ilsdev.test.rero.ch][2]

**Screenshots**
![image](https://user-images.githubusercontent.com/55576980/106249663-f38d7700-6212-11eb-9402-bec919a5fe5e.png)

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by zannkukai** [comment]
@JoelleDosimont @pronguen 
Are you agree with the fact that `issue.received_date` field should only be required if the `issue.status` is "received" ; otherwise this field shouldn't be present into data ?

**Comment by zannkukai** [comment]
@BadrAly @pronguen 
Now, it exists fields `issue.status_date` and `issue.status` ; both are not repetitive. Using the following example :
* 2021/05/01 :: detect about a late issue --> status=late, status_date=2021/05/01
* 2021/05/23 :: receive the issue --> status=received, status_date=2021/05/23

May 23th, there is no way to know that this issue was late.
Does we need to store the history of status ? OperationLog ? Versionning ?

**Comment by pronguen** [comment]
@zannkukai 

> Are you agree with the fact that `issue.received_date` field should only be required if the `issue.status` is "received" ; otherwise this field shouldn't be present into data ?

Yes, I think. A little doubt about the status "Deleted": it would mean that we lose the `received_date`... to confirm by Joëlle.

About operation log or versioning to store the status history, I think it is too complex for this issue. But we will probably need it in the future. Let's stay for now with a unique status and its date.

**Comment by JoelleDosimont** [comment]
@zannkukai @pronguen 

> About operation log or versioning to store the status history, I think it is too complex for this issue. But we will probably need it in the future. Let's stay for now with a unique status and its date.

Ok : a unique status and its date.

>     Are you agree with the fact that issue.received_date field should only be required if the issue.status is "received" ; otherwise this field shouldn't be present into data ?
> 
> Yes, I think. A little doubt about the status "Deleted": it would mean that we lose the received_date... to confirm by Joëlle.

I think we can go with that... Maybe later we will want to keep a history if it's usefull, but I think it's ok for now.
