### ISSUE TITLE
Holdings of serial type should be displayed on document detailed view of all kind of document type (public interface)

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#1660]
**How it works**

After the holdings refactoring of the document detailed view **and** the correction allowing to attach a serial holdings to a non journal document, the holdings of serial type are not displayed.

**How it should works**

Holdings of serial type should always be displayed, either if they are attached to a document of journal type or of a non journal type. On the public interface, if the document is a non journal type, the holdings is not displayed, only the items are. But if the holdings is of serial type, then the holdings should be displayed.

On the professional interface, holdings are always displayed.

**Comment by zannkukai** [comment]
Do you have any URL where this problem is present ? With a fresh `setup` on localhost, I didn't find any holdings related to a non-periodical document.
