### ISSUE TITLE
ILL requests: 'copy' field is not correctly saved

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1671]
**Describe the bug**

In the user profile of the public interface, the scope of the ILL requests is always set to 'loan' even if we have chosen 'copy'.
Additionaly, there is no pagination information.
We have the same issue in the professional interface.

**To Reproduce**

1.  Login as a user.
2. Create an ILL request and chose the scope 'copy'. Add pagination.
2. Check the scope of the ILL request in the profile.

**Expected behavior**

The right scope should be displayed.

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v0.15.0`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by iGormilhit** [comment]
This is fixed in `v1.2.0` (tested on ilsdev).

**Comment by PascalRepond** [comment]
This is still the case `v1.15.0`
