### ISSUE TITLE
"collection" is replaced by "exhibition/seminar"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1672]
**How it works**

Currently, the name of the resource "Collection" is not very clear for the end user.

**How it should works**

"collection" is replaced by "exhibition/seminar".

**Context**

This string cannot be corrected only in Weblate, as it is also used in SONAR.

**Comment by iGormilhit** [comment]
We could have something like `ils_collection` and `sonar_collection` to identify the two kind of collection.

Are this collection, in the ILS, something like virtual or temporary location?
