### ISSUE TITLE
Some expected issues don't get the "late" status

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1674]
**Describe the bug**

Some issues not received don't get the "late" status after the field `days_before_first_claim` is achieved.

**To Reproduce**

1. Create a holdings with an expected issue for the same day and 
2. Set the field `days_before_first_claim` to 1
3. Wait a few days
4. See that the issue does not get the "late" status

**Expected behavior**

All issues get the "late" status when they are expected and when they achieved the number of days before first claim.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v0.15.0`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**
Screenshot taken on Febr. 4, 2021 on [this holdings](https://ils.test.rero.ch/professional/records/holdings/detail/12371)
![image](https://user-images.githubusercontent.com/8154915/106862120-f7b00d80-66c6-11eb-9c19-92d021eaa4fd.png)

**Comment by zannkukai** [comment]
* create https://ilsdev.test.rero.ch/professional/records/holdings/detail/21055 (2021/06/04)

![image](https://user-images.githubusercontent.com/10031585/120800973-df4ee300-c540-11eb-8527-b2863d218e5e.png)

**Comment by zannkukai** [comment]
Situation at 2021/06/08 on same URL

![image](https://user-images.githubusercontent.com/10031585/121139533-2686ed80-c839-11eb-97bb-791451ec5d3b.png)

Seems work. I think that the scheduled job generating late & claim was not working when the issue was created.
When the job run, all seems ok.
