### ISSUE TITLE
Add a second filter to the organisation facet filter has no effect

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#1684]
**Describe the bug**

When an organisation filter is selected the number of results are filtered but when a second is selected it has no effect. This appears on the public and professional view. Other facets can be impacted.

**To Reproduce**

1. Go to the search result on the public global view.
2. Click on an organisation filter.
3. See the number of results changes.
4. Click an other organisation filter.
5. Errror: the number of results does not change.

**Expected behavior**

Multiple facet filters should works.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.0.0` or the commit hash (see frontpage).

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by rerowep** [comment]
Maybe related to https://github.com/rero/rero-ils/issues/962
