### ISSUE TITLE
Missing string translation on holdings/items screen

### ISSUE THREAD

**Issue by Garfield-fr** [rero/rero-ils#1687]
Add these strings for translation
```
'{{ counter }} hidden items'
'{{ counter }} hidden item'
'{{ counter }} hidden holdings'
'{{ counter }} hidden holding'
```

**Comment by zannkukai** [comment]
@iGormilhit : these four strings are already into 'manual_translations.ts' file from rero_ils_UI `Admin` project and also into weblate. Is there any other things to do to solve this issue ?

**Comment by iGormilhit** [comment]
Translated on v1.0.1. I'm closing this.
