### ISSUE TITLE
items attached to holdings are not shown in the organisational public view

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1688]
In the global public interface, for documents with serials holdings the attached items are well displayed. You do not see the same items when displaying the same document in the organisational public view.

**To Reproduce**

https://ils.test.rero.ch/global/documents/1117
<img width="1224" alt="Screenshot 2021-02-10 at 12 11 08" src="https://user-images.githubusercontent.com/26998238/107502536-10be3000-6b99-11eb-8468-e892043de5a6.png">

For the same document -> https://ils.test.rero.ch/aoste/documents/1117
<img width="1281" alt="Screenshot 2021-02-10 at 12 11 48" src="https://user-images.githubusercontent.com/26998238/107502596-2895b400-6b99-11eb-90f5-99ff048b76c3.png">

**Expected behavior**

The items should always displayed in all views.

* server: [ils.test.rero.ch]
* version: `v0.1.0.0`

**Comment by iGormilhit** [comment]
Cloed by https://github.com/rero/rero-ils/pull/1699.
