### ISSUE TITLE
2nd-level values of hierarchical facets are not always sorted according to their parent value

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1697]
**Describe the bug**

A document can have a repetitive document type (main type + subtype). In this case, if it has 2 different main types, this generates a problem in the facet (see screenshot).

Example: a document has the following main types/subtypes: `a/1` + `b/2`. If the main type `a` is selected in the facet, `1` is then proposed as sub-facet, but `2` is also proposed.

**To Reproduce**

1. Create a document with two different main type, and two different subtypes
2. Save it
3. Do a search using the document type facet, and selecting one of the main type of this document.
4. See the subtypes proposed

**Expected behavior**

`2` should not be proposed as subfacet of `a`.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.0.0`

[1]: https://ils.test.rero.ch

**Screenshots**

"CD-Rom, DVD-Rom" belongs to the main type "Support électronique".
![image](https://user-images.githubusercontent.com/8154915/107758054-a3d8a080-6d26-11eb-9755-e0c1d2413396.png)

**Comment by rerowep** [comment]
This is not a bug, this is how it works in Elastic search.
