### ISSUE TITLE
Request date shouldn't be updated after validation

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1704]
**Describe the bug**

When a request is validated, the request date of the item detail view changes to the validated date.
Ex: Katie made a request the 16th. 
![image](https://user-images.githubusercontent.com/12396034/108208003-c43e9b80-7128-11eb-8736-d603b12de597.png)
I validated the request of Katie on the 17th. The request date changed to 17th.
![image](https://user-images.githubusercontent.com/12396034/108209650-d6b9d480-712a-11eb-9ce7-64097fa67c5e.png)

 

**To Reproduce**

1. Go to the request section.
2. Click on a barcode and add several new requests on the same item.
3. On the request section, validate the request.
4. See the item detail view.

**Expected behavior**

The request date shouldn't change to the transaction date. Otherwise, the staff will have difficulties to follow the request queue.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.0.0`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by zannkukai** [comment]
Seems inked to https://github.com/rero/rero-ils/issues/1227

**Comment by iGormilhit** [comment]
> Seems linked to #1227

@zannkukai Indeed.

**Comment by ManaDeweerdt** [comment]
I've tested on https://ilsdev.test.rero.ch/ and I still have the same issue.
