### ISSUE TITLE
The expected issues are difficult to read, the grey is to light.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1717]
**How it works**

![image](https://user-images.githubusercontent.com/8154915/108813010-6f7ba480-75b0-11eb-8ada-6e34d5054642.png)

**Improvement suggestion**

Use a darker grey

**Comment by zannkukai** [comment]
With the PR, I now use the bootstrap "text-muted" gray. This could be customized when we setup the final theme of rero_ils
