### ISSUE TITLE
An issue with status "deleted" is displayed in the public interface

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1719]
**How it works**

An issue with status "deleted" is displayed in the public interface.

**How it should works**

It should not be displayed.

**Comment by zannkukai** [comment]
@pronguen 
Should be resolved with this PR : https://github.com/rero/rero-ils-ui/pull/520
Already integrated into `dev` but not yet deployed for testing.

This PR allow to list only "received" issue into the public interface (hide all other status : deleted, claimed, late)

**Comment by pronguen** [comment]
Thank you @zannkukai 
I didn't see the other issue... Duplicate of #1661
