### ISSUE TITLE
Missing Online access for bibliographic records with "Uniform Resource Locator" 

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#1722]
**Describe the bug**
Online access to records with a "Uniform Resource Locator" field does not appear in the public interface.

**To Reproduce**
1. Go to the public interface
2. Find a record with "Uniform resource Locator" (ex. : Lettres d'un François)
3. Look at the "Get" tabs
3. See that there is no online holding and the full text link is missing.

**Expected behavior**

* The tab "Online access" is removed.
* The field `electronicLocator` is displayed in the public and professional interface, document detailed view, on top of the page:
  * an icon "fa-link" is displayed before each link
   * links of type "resource" are always displayed on top of the list
   * Link text: concatenation of `type`: `content`. Translations for `type`:
     * "resource": Online access
     * "versionOfResource": Other online version
     * "relatedResource": Related resource
     * "hiddenUrl": Hidden URL
     * "noInfo": Related resource
  * `note` is always displayed in parenthesis after the link
  * `url` is not displayed but used to set the link
  * "hiddenUrl" are only displayed in the professional interface

Examples (orange: type; green: content; red: note):
![image](https://user-images.githubusercontent.com/8154915/110436459-8e9c2b00-80b4-11eb-9e96-b8998f00999a.png)

**Context**
* server: [ils.test.rero.ch][1] and [ilsdev.test.rero.ch][2]
* version: `v1.0.0`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/110436266-51379d80-80b4-11eb-9213-d4300419baf0.png)

**Comment by pronguen** [comment]
Decision of PO group: display on top of document detailed view, in public and pro interface.
