### ISSUE TITLE
Place should be required in document field "Provision activity"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1739]
**How it works**

Currently, it is not required to enter a country of publication in a document

**How it should works**

* If `provisionActivity.type`="bf:Publication", `place` is required.
* Inside of place, `country` is always required.

**Comment by zannkukai** [comment]
@pronguen 
There are two 'place' field for a provision activity : 
 * the first one is a direct child of 'provision_activity' field and contains a select with the country
 * the second one is a child of 'statement' field, itself a child of 'provision' activity. This is a free text (probably for 'city' information ?).
 
 Assuming of you want that the first one is required, this field is only display if a 'statement' exists. 
 So do you need also that "statement" is required for `provisionActivity.type="bf:Publication"` and for this statement that a `bf:Place` is required too ?

**Comment by zannkukai** [comment]
@pronguen OK for me, the PR was already ready for this implementation. It sounds just strange (for me and myself) to have some data (country, start_date) for a provision_activity but theses data are never shown if you don't enter any statement for the same provision_activity.

So you can have 
```json
"provisionActivity": [{
    "place": [{
        "country": "be",
        "type": "bf:Place"
    }],
    "startDate": 2001,
    "type": "bf:Publication"
}]
```
These infirmation never appears nor in pro, nor in public interface.
But if you add a simple statement :
```json
"provisionActivity": [{
    "place": [{
        "country": "be",
        "type": "bf:Place"
    }],
    "startDate": 2001, 
    "type": "bf:Publication"
    "statement": [{
        "label": [{
            "value": "Louvain"
        }],
       "type": "bf:Place"
    }],
}]
```
You will only see "**Publication** : Louvain" into GUI interface

**Comment by pronguen** [comment]
@zannkukai Yes, indeed. This might be improved in the future.
* `startDate` is entered only for the facet and sort options, but the date we want to display is entered in the statement.
* `country` is entered because it is part of the standard, but it is not of high importance for the user (it could be displayed in the "Description" tab).
