### ISSUE TITLE
Edition: performance

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1747]
**How it works**

When we edit/create a record or import a new record, it takes a few seconds before the page loads.

**Improvement suggestion**

The load of the editor should be faster.

**Comment by JoelleDosimont** [comment]
Some examples when editing a record :
https://ils.test.rero.ch/professional/records/documents/edit/1600589
https://ils.test.rero.ch/professional/records/documents/edit/134
https://ils.test.rero.ch/professional/records/documents/edit/835
