### ISSUE TITLE
Fees: transaction history not sorted by date/time

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1766]
**Describe the bug**

The transaction history of the fees on the user profile is not ordered by date/time.
Note: the order is correct in the professional interface.

**To Reproduce**

1. Go to the loan interface.
2. Add a dispute to a user.
3. Pay a part of the fees.
4. Login as the user.
5. See the fees in the profile

**Expected behavior**

The transactions must be ordered chronologicaly.

**Context**

* server:  [ilsdev.test.rero.ch][2]
* version: `v1.0.1` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[2]: https://ilsdev.test.rero.ch

**Screenshots**

Example of dispute:
![image](https://user-images.githubusercontent.com/12396034/110952350-688db980-8346-11eb-97bc-218328af52cb.png)

Example of payment
![image](https://user-images.githubusercontent.com/12396034/110953006-2add6080-8347-11eb-8635-de22c4f14f17.png)

**Additional context**

**Comment by zannkukai** [comment]
@ManaDeweerdt Please check with other PO members to know if the transaction history is required into the public interface.

**Comment by ManaDeweerdt** [comment]
@zannkukai We confirm that we want to keep the fees transaction history.

**Comment by iGormilhit** [comment]
Seems to be fixed on ilsdev (a few days before v1.2.0) and on ils.test.rero.ch (v1.1.0). Needs to be checked on UCL instance.

**Comment by ManaDeweerdt** [comment]
It works as expected in the v1.1.0.
