### ISSUE TITLE
Confirmation before submitting an ILL request

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1771]
**How it works**

Currently, the "ENTER" key submits the ILL request, even if only the title has been entered. Then, the patron cannot edit this request anymore.

**Improvement suggestion**

Ideally, the "ENTER" key submits the request, but a confirmation pop-up is opened: "Do you want to submit this request".
The patron can choose "Confirm" (call to action) or "Cancel" (outline, red).

**Comment by iGormilhit** [comment]
> even if only the title has been entered

To allow this behavior, no other fields have been defined as `required`.

**Comment by zannkukai** [comment]
It seems that a confirmation box is already present on submit button and when the enter key is fired : 
![image](https://user-images.githubusercontent.com/10031585/116220215-bfabea00-a74c-11eb-99b3-e1c9e6684206.png)

implemented by @jma 2021/03/16.
Is it suffisent ?

**Comment by pronguen** [comment]
@zannkukai You're right! I close it. Thanks :+1:
