### ISSUE TITLE
Display of unmasked documents with unmasked items/holdings

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1774]
When a document is unmasked and all of its items/holdings are masked, the document should be filtered out by the organisation filter, as it has no "non masked" holdings for this organisation.

**How it works**

Currently, the system displays an unmasked document for all the public views when all of its items/holdings are masked.

**Comment by PascalRepond** [comment]
This makes no sense. If a document needs to not appear, it should be masked by the professionnal.
