### ISSUE TITLE
E-books are not searchable in the organisation views of ilspilot

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1780]
**Describe the bug**

In the organisation views of ils.test.rero.ch, the Cantook e-books are searchable (1 result):
https://ils.test.rero.ch/aoste/search/documents?q=blackout%20navarro%20babelcube&page=1&size=10

This is not the case in the RBNJ view of ilspilot (0 result):
https://ilspilot.test.rero.ch/rbnj/search/documents?q=blackout%20navarro%20babelcube&page=1&size=10

However, they can be searched from the global view of ilspilot (1 result):
https://ilspilot.test.rero.ch/global/search/documents?q=blackout%20navarro%20babelcube&page=1&size=10

**To Reproduce**

See example in previous section

**Expected behavior**

* The e-books ebibliomedia are searchable in the view *rbnj* and *global*, but not in *rerovs* and *bulle*.
* The e-books mv-cantook are searchable in the view *rerovs* and *global*, but not in *rbnj* and *bulle*.

**Context**

* server: https://ilspilot.test.rero.ch/
* version: `v1.0.1`

**Comment by rerowep** [comment]
It looks ok on the api side:
`search  = DocumentsSearch().filter('query_string', query="The blackout", default_operator='AND').filter('term', 'holdings__organisation__organisation_pid=3})` gives the right result.
