### ISSUE TITLE
Library exceptions should be displayed in chronological order

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1782]
**How it works**

The exceptions are displayed in a random order. See last line "Test":
![image](https://user-images.githubusercontent.com/8154915/111484265-e3cfe080-8735-11eb-9a3a-9eccd9e9d410.png)

**Improvement suggestion**

* The exceptions are in practice quite numerous, so it is useful to have them sorted chronologically.
* Nice to have: a regular job removes all the exceptions that concern the past.

**Comment by zannkukai** [comment]
It's quite bit difficult because some exception could be repeatable with modular period (every 2 months, each year, every 4 years, ...)
