### ISSUE TITLE
User can display masked documents in public interface if s/he knows the document pid

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1789]
A masked document is usually not visible in the public interface.
However, if a user knows the document pid, s/he can access the document directly by visiting the URL:

https://~/documents/2000537

1. Mask a document in the pro interface and take a note of the document_pid
2. Logout and visit the public interface
3. visit the document page: https://~/documents/<document_pid>.
4.  You can display the document and its unmasked holdings/items

* server:  [ilsdev.test.rero.ch]
* version: `v1.1.0` 

masked record in the pro interface
<img width="1210" alt="Screenshot 2021-03-22 at 15 48 37" src="https://user-images.githubusercontent.com/26998238/112008768-13139280-8b26-11eb-8e61-e9e7ea16b45a.png">

record is visible by accessing directly the document URL
<img width="1198" alt="Screenshot 2021-03-22 at 15 48 50" src="https://user-images.githubusercontent.com/26998238/112008805-1b6bcd80-8b26-11eb-8935-7a04ba227cfd.png">

**Comment by PascalRepond** [comment]
The masking mechanism should hide documents from the public search but the API is public and should still respond. Moreover, there can be many links to the document in the public view (entities, partof etc) that we do not want to filter out or lead to an empty page.

**Comment by PascalRepond** [comment]
The masking mechanism should hide documents from the public search but the API is public and should still respond. Moreover, there can be many links to the document in the public view (entities, partof etc) that we do not want to filter out or lead to an empty page.
