### ISSUE TITLE
data.rero.ch/01-[RERO nr.] should be redirected to RERO ILS for the go-live

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1802]
**Is your feature request related to a problem? Please describe.**

The service data.rero.ch/01-[RERO nr.] provides permalink to
- view the RERO Explore public display of a document
- access alternative formats (marcxml, marchtml)

**Describe the solution you'd like**

The redirection to the RERO Explore public display should be set to RERO ILS for the go-live (July 2021).

**Describe alternatives you've considered**

- abandon this service: this alternative was not retained as the redirection requires a low effort and a lot of permalinks are potentially used on the web.

**Comment by iGormilhit** [comment]
@pronguen I think that this is not a RERO ILS feature.

This should be done by @rerowep or @philippe-rero.

Do we expect to redirect to the same record on RERO ILS? Or the redirection will be done on the RERO ILS home page? Will *every* record present on data.rero.ch migrated to RERO ILS?

**Comment by Garfield-fr** [comment]
It is currently not possible to replace data.rero.ch, because we break other applications that use this service.

**Comment by pronguen** [comment]
This redirection is still blocked by other working services (FPR). After a so long waiting time, it makes no sens to implement it.

Therefore, we close the issue.
