### ISSUE TITLE
In a holdings, only active predictions should generate expected and late issues.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1807]
**How it works**

Currently, every holdings generates expected and late issues, even for a journal that is not received anymore since a long time.

**Improvement suggestion**

* Only holdings with `acquisition_status`=currently_received generate expected and late issues.
* Field `acquisition_status`
   * is required, with default value "currently_received".
   * is place just before field "patterns"

**Comment by zannkukai** [comment]
@pronguen @BadrAly 
Am I wrong if i think that the `acquisition_status` field is required only for `serial` type holding ?

**Comment by pronguen** [comment]
@zannkukai The field is possible only for serial holdings, but is currently not required.
