### ISSUE TITLE
Late issues: possibility to access directly the holdings

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1808]
**How it works**

In the late issues brief view, it is only possible to access an *issue detailed view*.
From there, it is possible to jump to the *document detailed view*.
From there, it is possible to manually look for the concerned holdings and open the *holdings detailed view*.

Most of the time, the librarian want to land on the holdings detailed view, because he/she has an overview of the reception and late issues.

**Improvement suggestion**

In the late issues brief view (see picture below)
* the main link opens the holdings detailed view
* the barcode opens the issue detailed view

[nice to have] In the issue detailed view, it is possible to jump to the holdings detailed view. This should not be possible from a standard item detailed view

![image](https://user-images.githubusercontent.com/8154915/113122597-138de680-9214-11eb-9132-e257464061df.png)

**Comment by zannkukai** [comment]
Unable to link to the correction PR : https://github.com/rero/rero-ils-ui/pull/602
