### ISSUE TITLE
"Catalog" in the main menu is not translated

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1812]
**Describe the bug**

"Catalog" in the main menu of the professional interface is not translated.

**To Reproduce**

* Open the professional interface

**Expected behavior**

It is translated

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.1.0`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/113739782-6a0d9000-9700-11eb-9c1c-c23a8342ed7d.png)

**Comment by iGormilhit** [comment]
The string is not even extracted.
