### ISSUE TITLE
Parts of public patron account are not translated

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1819]
**Describe the bug**

"Edit" button and "None" counter are not translated. See screenshot.

**To Reproduce**

* Open a patron account in the public interface

**Expected behavior**

It is translated.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.1.0`

[1]: https://ils.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/114344052-6d20da00-9b5f-11eb-9d2d-21978eec15c6.png)

**Comment by zannkukai** [comment]
Seems solved. Maybe a punctual javascript bug breaking the end of javacsript process ?
![image](https://user-images.githubusercontent.com/10031585/116515739-f7da3680-a8cc-11eb-80aa-f0cd0832aa92.png)
