### ISSUE TITLE
BnF: only the EAN is imported, ISBN is ignored.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1825]
**How it works**

Currently, only the EAN (field 073) is imported from a BnF record, the ISBN (field 010) is ignored.

**How it should works**

Both are imported. See CONVERSION file for specification.

**Comment by ManaDeweerdt** [comment]
The ISSN (011) is also ignored.

**Comment by JoelleDosimont** [comment]
> The ISSN (011) is also ignored.

I have updated the CONVERSION file for the ISSN.
