### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by rerowep** [rero/rero-ils#1827]
https://sentryils.rero.ch:8443/organizations/sentry-rero-ils-prod/issues/77/?project=2&query=is%3Aunresolved

UnboundLocalError
local variable 'msg' referenced before assignment

rero_ils/modules/items/tasks.py in clean_obsolete_temporary_item_types at line 99
```python
            )
        current_app.logger.info(msg)
        # remove the obsolete data
        del item['temporary_item_type']
        item.replace(data=item, dbcommit=True, reindex=True)
    set_timestamp('clean_obsolete_temporary_item_types', msg=msg)
    current_app.logger.debug("Ending clean_obsolete_temporary_item_types()")
```

**Comment by iGormilhit** [comment]
@rerowep We need to understand what it is and rewrite it. Otherwise it will be lost.
