### ISSUE TITLE
Rename in the item field "Enumeration and chronology" into "Unit"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1830]
**How it works**

The field `enumerationAndChronology` has as title "Enumeration and chronology". But in the interface, it is displayed as "Unit", more understandable label.

**How it should works**

* the field key stays `enumerationAndChronology`
* only the title changes: "Unit"

**Comment by zannkukai** [comment]
I changed the JSON schema. I didn't find other occurence of this string into other "public" view.
