### ISSUE TITLE
Requests: Waiting queue position not displayed anymore (public interface)

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1851]
**Describe the bug**

In the public interface, a user cannot see anymore his position in the waiting queue.

**To Reproduce**

1. Log in as a librarian.
2. Add several requests to an item.
3. Log in as a user

**Expected behavior**

As a user, I should be able to see in my account 'request' tab, my posititon in the queue if there are several requests on the item.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v0.1.0.0` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/12396034/116251295-d5320b80-a76e-11eb-814b-9b6ff9793cb8.png)

**Comment by zannkukai** [comment]
Should be solved after https://github.com/rero/rero-ils/pull/1797 integration.
Need to be validate
