### ISSUE TITLE
Circulation policies: unable to create cipo with different loan period for 2 different libraries

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#1859]
**Describe the bug**

The CIPO editor doesn't allow to create 2 CIPO with the same conditions (patron type/item type),
with different loan periods, for 2 different libraries.

**To Reproduce**

1. Go to ilsdev, login with Astrid, Go to the professional interface.

In the CIPO editor, you create a CIPO called "X1" with a loan period of 10 days. 
You can indicate it applies to selected patron types and item types, and for a specific library (AOSTE-CANT1) => OK

Let's say you want to create a CIPO, called "X2",  with a loan period of 5 days, for another library (AOSTE-LYCEE)
You can't indicate it applies to patron types and item types because they are already selected in CIPO X1.

**Expected behavior**

In the CIPO Editor, the admin user must be able to create CIPOs for different libraries, with different loan periods, for the same patron types/item types.

* server: ils.test.rero.ch
* version: v1.1.0

**Comment by pronguen** [comment]
The editor does not allow it, but if the JSON is created manually and inserted into RERO ILS, it works.
