### ISSUE TITLE
Multiple checkouts is possible on same item for the same patron

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1864]
A new record `loan` is normally created in DB when a `checkout` action is done for an item `A` and a patron `B`.  
The `invenio-circulation` module does prevent users from creating new `loans` for the same pair. However if you try to use the method `Loan.create` to create a new `loan` for the same pair it will work.

When this happens, you can end up having as much loans as you want in the DB for the same pair and for the same `loan.state`. This breaks and corrupt completely the circulation module and its data. 

Some measures need to be be put in place to prevent this from happening. It is true that only the `sysadmin` staff have the access to the `Loan.create` method, but at least need to create some kind of protection.

**To Reproduce**

1. in the frontend, `checkout` item `A` to patron `B`,  
2. try to `checkout` the same item to the same patron, transaction will fail because item is already checked-out.
3. using the backend, try to create a new `loan` using the method `Loan.create` for the same pair above and the loan.state=ITEM_ON_LOAN
4. repeat the step 3 as many times as you want.
5. You end up check-out the same item for the same patron multiple times
6. same goes for other types of transactions `requests`, `renewals`...

**Expected behaviour**

Only on active `loan` is allowed for item/patron in DB.

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.2.0` 

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by zannkukai** [comment]
@BadrAly 
Is right to think that the combination of `patron`+`item`+`loan.state` must be unique in the system excepted for state "ITEM_RETURNED, "CANCELED" AND "ITEM_IN_TRANSIT_*"

**Comment by PascalRepond** [comment]
This seems to not happen anymore
