### ISSUE TITLE
Bug list for the v1.2.0 RC

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#1873]
**List of bugs**

- [x] [ @jma on it] All persons and corporates bodies detailed views of the public interface crash (internal server error). PR: https://github.com/rero/rero-ils/pull/1874
- [x] https://github.com/rero/rero-ils/issues/1895 [not blocking] ILL resquest of the public interface is accessible for non patron users such as librarians and it should not be the case. When a non patron user fill in the form, this results in an internal server error.
- [x] [not blocking] As we want to import a document from BNF, it displays the availability ('not available') but it is not necessary.
- [x] [not blocking] Public interface: some strings are displayed in the wrong language (see below - french interface) - linked to @pronguen 's comment below
- [x] [not blocking] In the document editor, the "ISBN check" doesn't convert ISBN 10 in 13. __(see issue https://github.com/rero/rero-ils/issues/1893)__
- [x] [not blocking] In the document editor, when loading the template list, the list appear empty until you click on it. https://github.com/rero/ng-core/pull/389

![image](https://user-images.githubusercontent.com/16501502/117016980-88f94500-acf3-11eb-8133-e044d2e62a5c.png)

**Context**

* server: [ilsdev.test.rero.ch][2].
* version: `v1.2.0RC`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by pronguen** [comment]
I put my comments here to avoid parallel edition of the same Github comment:
- [ ] Language of the circulation information does not respect the interface language (see screenshot)
![image](https://user-images.githubusercontent.com/8154915/117012508-4d5c7c00-acef-11eb-9fe7-c469af4fb6d7.png)
- [ ] Tab history is missing in the patron account professional interface, but is present in the public interface.

**Comment by ThierryClavel** [comment]
[not blocking] editor : content-media-carrier : content type only is proposed : impossible to choose media type and carrier type
![image](https://user-images.githubusercontent.com/31695537/117026873-6d466c80-acfc-11eb-8452-d5235b1c6f9c.png)
