### ISSUE TITLE
Keep the ID of RERO authorities when IdRef or RERO-RAMEAU does not exist

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1886]
**How it works**

1. Field `contribution.identifiedBy`: the identifier of the RERO authority is never imported from Virtua
2. Field `subjects.identifiedBy`: the identifier of the RERO authority is sometimes not imported from Virtua
3. Field `genreForm.identifiedBy`: the identifier of the RERO authority is sometimes not imported from Virtua
4. Field `provisionActivity.place`: the identifier of the RERO authority is never imported from Virtua

**How it should works**

*(See https://github.com/rero/rero-ils/issues/1885 for JSON schema spec)*

1. Field `contribution.identifiedBy`: import the RERO ID of the authority if there is no link to IdRef
    * these modifications are indicated in red in file "CONVERSION", row L22
2. Field `subjects.identifiedBy`: import the RERO ID of the authority if there is no link to IdRef (for places, works, persons, corporate bodies) or no link to RERO-RAMEAU (for concepts)
    * these modifications are indicated in red in file "CONVERSION", row L50
3. Field `genreForm.identifiedBy`: import the RERO ID of the authority if there is no link to RERO-RAMEAU
    * these modifications are indicated in red in file "CONVERSION", row L49
4. Field `provisionActivity.place`: import the RERO ID of the authority if there is no link to IdRef
    * these modifications are indicated in red in file "CONVERSION", row L15

**Comment by rerowep** [comment]
`provisionActivity.place` is not implemented jet. Will be solved during implementation.
