### ISSUE TITLE
Editor : the ISBN check for duplicates doesn't convert ISBN 10 into 13

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#1893]
**Describe the bug**
When entering the ISBN in the editor, the system check for duplicates in the catalog. But if the existing document has ISBN 13 and I write the ISBN 10 corresponding, the duplicates won't be found.

**To Reproduce**

1. Create a new bibliographic record
2. Fill an ISBN with 10 numbers, matching an ISBN 13 in the catalog (for ex. : 2072165113 / 9782072165115).
3. See that it doesn't find the potential duplicates.
4. Try with the ISBN 13, and the duplicates is found.

**Expected behavior**
The system should find the document whatever ISBN form is in the existing document (it works with the global search).

[Update 2022-03-24 - B. Erken] Same behaviour is expected in the **acquisition brief view**:
In the orders/receipts screen, when a librarian looks for documents with an ISBN-13, the system should find document with ISBN-10 and ISBN-13

**TO DO**

- [ ] Acquisition orders : complete the "acq_order" indexed data with all ISBN (10 and 13). Now, only the `document.identify_by[@type=isbn']` are added to the indexed_data, we need to complete with the possible conversion.
- [x] Document editor (enhance validator)

**Context**

* server: [ilsdev.test.rero.ch][2]?
* version: `v1.2.0` or the commit hash (see frontpage).

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/55576980/117263604-b7d9fd00-ae52-11eb-87a9-0bfd915c1db9.png)

**Comment by benerken** [comment]
Same behaviour is expected in the acquisition brief view: 
when the librarian looks for an ISBN-13, the system should find document with ISBN-10
