### ISSUE TITLE
Request: pickup location set by default to the item owning location

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#1899]
**How it works**

As a user, in the public interface, I can select different pickup location for a request.

**Improvement suggestion**

Two use cases exist:
1. RERO: let the user chose the pick-up location to avoid errors
2. UCL: by default, the item owning location is already selected as a pickup location because it concerns 95% of the cases
* either sort the pick-up libraries alphabetically and pre-select the first one corresponding to the item location
* or put on top of the list the pick-up libraries corresponding to the item location, and put the default value on the first.

To be implemented with a *flag* on instance level, so that both use case can be configured.

Possible solution
* an optional configuration on location that set the default pick-up location

**Comment by pronguen** [comment]
@zannkukai I just completed this issue https://github.com/rero/rero-ils/issues/2301 that brings another solution for the same problem. Maybe better?

**Comment by PascalRepond** [comment]
@ManaDeweerdt At grooming, it was decided to pull this issue from this sprint and discuss it in regards to its priority and its possible interaction with #2301
