### ISSUE TITLE
Error 401 when trying to add local fields on a document

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#1901]
**Describe the bug**

Sometimes, when trying to add local fields on a document, as the librarian click on the *add local fields* button, the system respond with a 401 error. It may happen 30 minutes after the initialization of the application, but this has to be confirmed.

If the librarian navigate elsewhere or reload the page, he/she can add the local fields.

**To Reproduce**

1. Log in as a librarian or system librarian in the professional interface.
2. Display a document detailed view (not an ebook) and open the local fields tab.
3. Wait 30 minutes.
3. Click on the *add local fields* button.
4. See error.

**Expected behavior**

At every moment, the authenticated professional should be able to add local fields on a document.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2].
* version: `v1.2.0`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

**Additional context**

This could be linked to the guard (`/projects/admin/src/app/guard/can-add-local-fields.guard.ts`) on the local fields form. This guard seach for the current user organisation in the local storage, that expire after 30 minutes. And the datastore seem cleared herd: https://github.com/rero/rero-ils-ui/blob/0776afc6cd6412d719d27835ee6eb83e6815df1f/projects/admin/src/app/service/app-router-event.service.ts#L63

**Comment by PascalRepond** [comment]
Related to #2705
