### ISSUE TITLE
Boosting of the most recent document

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1922]
**How it works**

Currently, there is no ranking based on the date of a document.

**Improvement suggestion**

Most recent document are boosted, even if the initial request does not contain any date parameters.

Example: if I search for "communicator" and there are 3 documents with this word in the title, the most recent should appear on top.

**Comment by PascalRepond** [comment]
Closing as wontfix. This behaviour is incompatible with ES's ordering of results based on relevance. Furthermore, search results can be ordered by date.
