### ISSUE TITLE
ContentMediaCarrier : value to remove  and placeholder to add

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#1924]
In the professional interface,  the element Content, media, carrier type is constituted of  3 subelements : contenttype, mediatype and carriertype.
1- the value "Content type" (type de contenu) in yellow, should be removed from list of values.
2- A placeholder "Choose the type of media (choisir le type de media) should be added
![image](https://user-images.githubusercontent.com/31695537/126750185-4b4bb62f-5879-4cb8-a662-6702c0de88c8.png)

**Comment by zannkukai** [comment]
@ThierryClavel 
1st image: `ContentType` isn't a place holder, this is the value of the field. See https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json#L11
In french, it's translated by 'Type de contenu'. In english it's also translated with badly spaced "contentType" string in weblate.
![image](https://user-images.githubusercontent.com/10031585/126162057-97cc0dd2-460e-42ae-b6a1-8f9999a16d90.png)

2nd image: we can't change the field name when duplicate it. In your example, you duplicated the first "Content, media, carrier type" field (by clicking on double box icon). The field name is duplicated too.

**Comment by ThierryClavel** [comment]
please dont close the issue. This field is not clear for users : the field 'content media carrier" is constituted of 3 subfields : content type , media type and carrier type . "Content type" should not be a value of the first field "content media carrier" :  a place holder "saisir le type de media"" or a value "media type" should be added instead.
