### ISSUE TITLE
Field `modeOfIssuance.subtype` sometimes not imported

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1928]
**Describe the bug**

When I import a resource, sometimes the field `modeOfIssuance.subtype` is not imported. In this case, I cannot save, and the form does not indicate the field concerned by the error. See screenshot.

**To Reproduce**

1. Import the document 9782354040628
2. Try to save the form without changing anything
3. See that the subtype of mode of issuance was not imported

**Expected behavior**

*  `modeOfIssuance.subtype` is imported, or deduced.
* If it is not selected, the field is highlighted in red.

**Context**

* server: [ils.test.rero.ch][1]

[1]: https://ils.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/118457744-5b03ff80-b6fa-11eb-844c-87b244a48dc0.png)

**Comment by rerowep** [comment]
It is working in https://github.com/rero/rero-ils/pull/1935
