### ISSUE TITLE
An item linked to a exhibition / course / collection is not displayed in the document detailed view

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1942]
**Describe the bug**

An item linked to a exhibition / course / collection is not displayed in the document detailed view, public and professional. The holdings appears, but without items. See screenshot.

**To Reproduce**

1. Add an item to an exhibition
2. Display the document detailed view of this item
    * in the public interface
    * in the pro interface

**Expected behavior**

They are displayed as before:

![image](https://user-images.githubusercontent.com/8154915/119511086-5f6f8e80-bd72-11eb-95a4-660cd44ab2b3.png)

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.2.0`

[1]: https://ils.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/119510557-e5d7a080-bd71-11eb-8170-3c24c9abfe68.png)

**Comment by zannkukai** [comment]
![image](https://user-images.githubusercontent.com/10031585/120775603-a3f1eb80-c523-11eb-9f8e-7ebf3025a02e.png)

I can't reproduce on localhost.
When I analyze request from ils.test.rero.ch, it seems than the backend return an error. But I don't have access to sentry to view this error, and don't receive any email.
