### ISSUE TITLE
Rename document subtypes and add subtype for pictorial book.

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#1947]
Document editor: field Type
1. the following subtypes are named : docsubtype_other_book, docsubtype_other_electronic_carrier, docsubtype_other_game, docsubtype_other_image, docsubtype_other_object \
   `docsubtype_other_book` should be renamed `docsubtype_book` (French: `livre`; German: `Buch`).
docsubtype_other_electronic_carrier should be renamed 'docsubtype_electronic_carrier'
docsubtype_other_game should be renamed 'docsubtype_game'
docsubtype_other_image should be renamed 'docsubtype_image'
docsubtype_other_object should be renamed 'docsubtype_object'

    => This was done in the translations. Is it better to do it also in the raw codes?

2. Add a subtype to Maintype Book. Name of new subtype: `docsubtype_pictorial_book` (French: `Livre illustré (beaux livres)`).

**Comment by pronguen** [comment]
This issue is very similar: https://github.com/rero/rero-ils/issues/1947

**Comment by pronguen** [comment]
This issue was merged into: https://github.com/rero/rero-ils/issues/2884

We decided to not rename the main and sub-type codes, for now, as it impacts all the connected services.
