### ISSUE TITLE
The "City" facet of the patron search relies on the wrong field

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1949]
**Describe the bug**

The facet relies on the city of the secondary address.

**To Reproduce**

1. Open https://ilspilot.test.rero.ch/professional/records/patrons?q=&page=1&size=10
2. Look at the "City" facet

**Expected behavior**

It should rely on the city of the primary address.

**Context**

* server: ilspilot.test.rero.ch
* version: `v1.2.0`

**Comment by zannkukai** [comment]
Now, the facet is based on `facet_city` ES field. This field is populated from "primary address city" **and** "secondary address city". We can only index "primary city" without any problem in the facet. Is it the expected behavior ?

**Comment by pronguen** [comment]
The facet seems to be populated only by the "secondary address city":

https://ilspilot.test.rero.ch/professional/records/patrons?q=nicolas%20prongu%C3%A9&page=1&size=10
![image](https://user-images.githubusercontent.com/8154915/121023732-d9a50780-c7a3-11eb-8627-6434f1e219c4.png)

Expected behaviour:
* at least primary address city
* we can also keep the secondary address city

**Comment by iGormilhit** [comment]
Closed by rero/rero-ils#1990.
