### ISSUE TITLE
Wrong mapping for user secondary address and phone

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1950]
**How it works**

Concerns: ilspilot.test.rero.ch (2nd load, v1.2.0)

* The street (secondary address) was imported as city
* The city (secondary address) was not imported
* The second phone (270$l) was not imported
* The keep history was not imported: all patrons have it disabled in RERO ILS.

**How it should works**

* All data is imported correctly.
* If 270(ind1=2)$a is repeated, concatenate it with a semi-colon ;

**Comment by iGormilhit** [comment]
Added to [RERO migration: final load][us].

[us]: https://tree.taiga.io/project/rero21-reroils/us/2107
