### ISSUE TITLE
Import of document field `issuance` sometimes wrong

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1951]
**How it works**

Concerns: ilspilot.test.rero.ch, v1.2.0
Field `issuance` is sometimes wrong. See example R008120841.

**How it should works**

It should be "SingleUnit/materialUnit" because the MARC document does not contain any 019 $a Niveau supérieur.

**Comment by rerowep** [comment]
I tested with the latest dev and it was correct!

**Comment by iGormilhit** [comment]
Added to [RERO migration: final load][us].

[us]: https://tree.taiga.io/project/rero21-reroils/us/2107

**Comment by pronguen** [comment]
@rerowep Pilot libraries say: "Visiblement énormément de notices ont été migrées avec un mode de parution "monographies en plusieurs parties" à la place de "unité isolée"
