### ISSUE TITLE
Problems on ilspilot, v1.2.0

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1959]
- [x] Some items are not displayed in the public and professional document detailed view. Example: no RERO (035):  0293948.
    ![image](https://user-images.githubusercontent.com/8154915/120152938-653ff680-c1ee-11eb-98a8-36d3c17c92f6.png)
    @iGormilhit: seems that the items are not in the DB.
- [x] Item request: "An error has occurred."
    1. check-out an item for patron A
    2. request this item in the professional interface for patron B
    3. systematically, RERO ILS gives the following error message, but the request is saved.
    ![image](https://user-images.githubusercontent.com/8154915/120218461-0ef8a500-c23a-11eb-9a01-4f3c26cafab4.png)
- [x] This item https://ilspilot.test.rero.ch/professional/records/items/detail/1622054 is marked as "on loan" but
    - on the item detailed view, the patron who has it on loan is not displayed
    - cannot be checked in
    - this is linked to the following point of the list
- [x] When I try to return an item on loan, with 1 request, I get an error message "Name 'recipient' not defined. Exemplaire non trouvé", see image below.
    ![image](https://user-images.githubusercontent.com/8154915/120220573-3d2bb400-c23d-11eb-8083-08c5967b95b8.png)

**Comment by jma** [comment]
> * [ ]  Some items are not displayed in the public and professional document detailed view. Example: no RERO (035):  0293948.
>   ![image](https://user-images.githubusercontent.com/8154915/120152938-653ff680-c1ee-11eb-98a8-36d3c17c92f6.png)
>   @iGormilhit: seems that the items are not in the DB.

This is due to the virtua import data that do not index well the holdings when a new item is loaded: here some hodlings should be removed or mark as hidden.

**Comment by jma** [comment]
> * [ ]  This item https://ilspilot.test.rero.ch/professional/records/items/detail/1622054 is marked as "on loan" but
>   
>   * on the item detailed view, the patron who has it on loan is not displayed
>   * cannot be checked in
>   * this is linked to the following point of the list
This item has been returned and an automatic validation request has been done. Unfortunately the item status has not be updated. Further investigation should be done to know if an error has been raise (date: 2021-05-31T16:15:28.703624+00:00) due to the instance instability or a bug. Need to see if it can be reproduced.

**Comment by iGormilhit** [comment]
Has to be retested on the `v1.3.0`.

**Comment by iGormilhit** [comment]
Tested on `v1.3.0`.
