### ISSUE TITLE
Item does not get the correct status after migrating Virtua loans

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1974]
Item status remains on_shelf after creating ITEM_ON_LOAN loan for the item.

The method `reroils_modules_loans_load_virtua_transactions` is created to load loans from the Virtua database directly to the REROILS instance. Process works correctly however, the loaded loans do not update the item `status`. 

After loading the loan, the new loan is well attached to the item. the `on_shelf` status remain unchanged.
 

* server: [ilspilot.test.rero.ch]
* version: `v0.12.0` 

**Screenshots**

<img width="1288" alt="Screenshot 2021-06-03 at 15 19 57" src="https://user-images.githubusercontent.com/26998238/120651531-2d9bad80-c47f-11eb-8265-176e8e292bc3.png">

Item is checked-out and status remains `on_shelf`.

**Comment by ManaDeweerdt** [comment]
Same when we add a new item. Ex https://ils.test.rero.ch/professional/records/items/detail/4052
In this case, it should display the status label in place of 'on shelf'.
