### ISSUE TITLE
Missing OS utilities into the pod `ils-setup-shell`

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1977]
We use the pod `ils-setup-shell` mainly to manage database manipulation and other daily tasks. This pod is missing major linux commands like `ps` to show running processes. 
For now and at least, please ensure this pod has the `ps` command

**Comment by iGormilhit** [comment]
Not exactly a RERO ILS issue. Should be fixed through the private git repository about deployment.

@BadrAly I think a list of needed utilities should be made in order to install them in the container.

**Comment by PascalRepond** [comment]
@BadrAly Is this issue still relevant?
