### ISSUE TITLE
Circulation error for item migrated from Virtua

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1983]
1. It is impossible to renew the loan created at the data load
2. When trying to return any of the the migrated Virtua checked-out items at an external library, the following error appears:

<img width="503" alt="Screenshot 2021-06-05 at 14 44 14" src="https://user-images.githubusercontent.com/26998238/120892070-a67c4000-c60c-11eb-8a8a-15f8f2b26d9a.png">

The check-in transaction itself goes well and the item receives the `in_transit` status. Which is a normal behaviour.

The inspector of the browser shows the following error:

```
'NoneType' object has no attribute 'get_library'
```

**Comment by zannkukai** [comment]
Complicated without server console/sentry.
It seems due to a problem into loaded data from Virtua. 

The method `get_library` is always called on a `Location` class instance. It seems that a location object cannot be loaded from either the loan object, either the item object.
