### ISSUE TITLE
Do we need to import Virtua issues?

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1984]
**How it works**

RERO ILS issues are created even if the issue is not received in Virtua.

![image](https://user-images.githubusercontent.com/8154915/120973754-a0eb3b00-c76f-11eb-997f-8c6f33d33b16.png)

**How it should works**

Virtua data is recovered as is.

**Comment by BadrAly** [comment]
@pronguen 
For me it is normal to migrate this issue, no bugs here.
The issue in question is a received issue, it just has no Virtua item attached to it.
