### ISSUE TITLE
The `price` is not correctly imported for items.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2007]
**How it works**

The `price` is not correctly imported for items. This concerns all items.
![image](https://user-images.githubusercontent.com/8154915/121314119-57cdef00-c907-11eb-987b-9a4c4e3285c6.png)

**How it should works**

The price should be 27.90 instead of 2790.-.

**Comment by iGormilhit** [comment]
According to @BadrAly it is fixed.
