### ISSUE TITLE
Item with barcode 1002157781 is imported in the wrong location

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2019]
**How it works**

Item with barcode 1002157781 is imported in the wrong location.
* it is in Espace jeunesse in Virtua
* it is in Espace adulte in RERO ILS

Other item examples (barcode): 1002145667, 1002151592

**How it should works**

The origin location is respected.

**Comment by BadrAly** [comment]
It is likely related to the mass correction carried out the 4.5.2021 in Virtua (re_task_rero: https://www.rero.ch/admin_request_mod.php?id=4645). The new extraction (test_date_10_5_2021) shows that the item is well at the  location `FR Bulle Bibl. publique et scolaire – Espace jeunesse`
