### ISSUE TITLE
Import BNF: the staff gets an error message in browser console when he looks for a title

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#2026]
**Describe the bug**

Import BNF : when you search for a title, you get the result set but the console of the browser displays an error message 
**ERROR TypeError: e is undefined**

(_It's not a blocking issue_)

**To Reproduce**
1. Go to ilsdev
2. Loin as a librarian and go to professional interface
3. Go To "Import from the Web" and search for a title
4. See error in the console

**Context**

* server: ilsdev.
* version backend : https://github.com/rero/rero-ils/commit/2c5e4b7f12f1bc9c672cc95e70fdd7758eb748fe
* version frontend : https://github.com/rero/rero-ils-ui/commit/49fedde0a6b61ea18d9fe99d081a05364c35b7ec

**Screenshots**
![image](https://user-images.githubusercontent.com/16501502/121665497-ad8dcd00-caa8-11eb-900d-6bea46112a9e.png)

**Comment by PascalRepond** [comment]
Doesn't happen in `v1.9.0`
