### ISSUE TITLE
Field `item.temporary_location` is displayed in the public and professional interfaces

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2038]
**How it works**

Currently, the exhibition/course is displayed as "Temporary location" on
* pro: document detailed view
* public: document detailed view

**Improvement suggestion**

With the new field `item.temporary_location`, we need to display under the same label "Temporary location"
* the linked exhibition/course
    * else: the temporary location
* or both? **TO CLARIFY BY PO GROUP**

This applies to 
* pro: document detailed view
* pro: item detailed view
* public: document detailed view

**Comment by zannkukai** [comment]
According to Gitter "PO room" : 
 * on affiche l'exposition/cours (+lien)
 * s'il n'y en a pas on affiche `item.temporary_location`
 * s'il n'y en a pas on n'affiche rien

**Comment by zannkukai** [comment]
Unable to work with UI `public-holding-items` project on localhost :'(
