### ISSUE TITLE
Two users can have the same e-mail if the case is different.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2048]
**Describe the bug**

Two users can have the same e-mail if the case is different (see screenshot).

**To Reproduce**

1. Add a user with the same e-mail than an existing user
2. Make one letter upper case

**Expected behavior**

The form prevents to save a user with the same e-mail than another user, even if the case is different.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.2.0`

[1]: https://ils.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/122407737-25b13280-cf82-11eb-8a7d-819c442487e0.png)

**Comment by zannkukai** [comment]
@jma I need your opinion :
 * Is this better to force the `email` field to be lowercase when we store data ? https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/users/api.py#L98-L99
 * Is this better to add a pattern on the `user-id-editor.componenent` email field to allow only lowercase characters ? https://github.com/rero/rero-ils-ui/blob/dev/projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts#L94-L98
 * Is this better to change the pattern into the `user` resource JSON schema ? https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json#L215
 * Is this better to create an analyzer for the field email into the ES mapping ? 
 
The last solution sounds good for me but, I didn't find any mapping for `User` resource in RERO_ILS and I don't know how I can hack the default mapping from Invenio (?)

**Comment by pronguen** [comment]
@zannkukai The solution implemented should solve the login problem: the user should be able to login with an e-mail with upper case, even if it is stored in lower case... or the system tells at login that the e-mail cannot have upper case characters.
