### ISSUE TITLE
Transaction log can be displayed for other organisations

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2056]
**Describe the bug**

As a librarian of organisation 1, I can display via the API transaction logs for loans of other organisations.

**To Reproduce**

1. Request the API, for instance with https://ils.test.rero.ch/api/operation_logs/?q=_exists_:loan

**Expected behavior**

* Only the loan logs of the organisation of the logged in librarian or system librarian are shown
* The document operation logs are displayed for all organisations.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.3.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/122748179-31f00500-d28c-11eb-8ac8-2f19c416492d.png)

**Comment by PascalRepond** [comment]
This seems fixed. Can you check @pronguen?

**Comment by PascalRepond** [comment]
The `operation_log` is the same resource for loans, items, documents etc. The permission structure doesn't allow to specify different access permissions for the same resource. This issue implies a big refactoring of this resource.

**Comment by PascalRepond** [comment]
Not critical and too complex, closing as not planned.
