### ISSUE TITLE
Extra parenthesis on the display of an ILL request detailed view

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2062]
**Describe the bug**

In the professional interface, on the detailed view, there are extra parenthesis at the end of the year and of the enumeration of the host document.

**To Reproduce**

1. Log in as a professional.
2. Navigate to `professional/records/ill_requests`.
3. Display an ILL request detailed view that has a publiation year and/or an enumeration.
4. See error.

**Expected behavior**

No additional parenthesis at the end.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.3.0`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/12396034/122016888-c0aede80-cdc1-11eb-9cbe-ad16e2574b2d.png)

**Comment by PascalRepond** [comment]
Has been closed by : issues/rero/rero-ils-ui/673
