### ISSUE TITLE
History anonymised still displayed

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2067]
**Describe the bug**

If a patron with "Keep history: no" does transactions, and on the same day activate his/her history, the transactions are shown in the history. The flag `to_anonymize` seems to be always set on "false".

**To Reproduce**

1. Open a patron with "Keep history: no"
2. Do a checkout and checkin for him/her
3. Activate then the history: "Keep history: yes"
4. Wait one day
4. See that the transaction done when history was disabled appears in the history

**Expected behavior**

We need to confirm the following behaviour in order to establish the documentation of it in the help of RERO ILS.

Logic

* The flag `to_anonymize` is set on "true" when the transaction done is for a patron with "Keep history: no"
* The anonymization job works on every loan that
    * is not active anymore (no fees linked, no litige)
    * AND has
        * either `to_anonymize` set on "true" 
        * or is closed for more than 6 months ago (already implemented in principle)
    * AND is not yet anonymized
* All loans receive `to_anonymize` on "true" when a patron disables his/her history.

The flag `to_anonymize` is either set on false once the loan is anonymised or contain 3 states (to_anonymise, anonymised, to_not_anonymise).

Display

* In the public interface (patron account)
    * Display the history tab only if "Keep history: yes" (already implemented)
    * Inside this tab, display only the loans that
        * are not anonymized, AND
        * have `to_anonymize` set on "false" (find a solution for loans where some logs are on "false", some other on "true")

Documentation

* confirm this information so that a documentation can be created.

See also https://github.com/rero/rero-ils/issues/2068

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.3.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by PascalRepond** [comment]
This is too minor and complex to fix. Closing the issue.
