### ISSUE TITLE
When editing a resource, default values are automatically added to fields (that were not present before edition)

### ISSUE THREAD

**Issue by Garfield-fr** [rero/rero-ils#2080]
**Describe the bug**

When adding the "Uniform resource locator" field when adding a document, the "Content type" field is present although it is optional.
When editing a record that contains the "Uniform resource locator" field, the "Content type" field is present even if the value is not in the data.

Generally, this problem happens with:
* document:
    * `electronicLocator.content`
    * `scale.type`
* holdings:
    * `max_number_of_claims`
    * `days_before_first_claim`
    * `days_before_next_claim`

**To Reproduce**

1. Go to 'https://ilsdev.test.rero.ch/professional/records/documents/detail/1028'
2. Edit the record
3. Jump to "Uniform resource locators"
4. Remove "Content type" field on element
5. Save record
6. Edit this record
7. Jump to "Uniform resource locators"
8. you see the "Content type" field even though there is no data

**Expected behavior**

If the field or sub-field is empty in the existing resource, it stays empty when editing the resouce.

**Context**

* server: [ilsdev.test.rero.ch][2]
* version: `v1.3.1`.

[2]: https://ilsdev.test.rero.ch

**Screenshots**

<img width="1175" alt="Uniform" src="https://user-images.githubusercontent.com/48578/123382057-c78fdb00-d591-11eb-8ae0-f91cdbf594e4.png">

**Comment by pronguen** [comment]
After a check of all sub-fields, this problem also happens with `scale.type`, where the default value should be removed. I added it in the main text of this issue.

**Comment by pronguen** [comment]
@Garfield-fr @jma A quick fix of this issue is to remove the default values for the mentioned field.

A mid-term fix (out of this issue scope) is to distinguish the displayed fields for document update or creation.
