### ISSUE TITLE
Wrong availability for item_type "no checkout"

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#209]
Items with `item_type.pid:4` are displayed as available, but the `item_type` is "No Checkout", which is associate with circulation policy 8, "No checkout".

![capture_169](https://user-images.githubusercontent.com/1557213/53964009-b71c7380-40ee-11e9-83a2-bda467aed461.png)

**Item type 4**:
```
{
    "$schema": "https://ils.rero.ch/schema/item_types/item_type-v0.0.1.json",
    "description": "No checkout.",
    "name": "No checkout",
    "organisation": {
      "$ref": "https://ils.rero.ch/api/organisations/1"
    },
    "pid": "4"
  }
```

**Circulation policy 8**:
```
{
    "$schema": "http://ils.rero.ch/schema/circ_policies/circ_policy-v0.0.1.json",
    "allow_checkout": false,
    "allow_requests": false,
    "description": "No checkout.",
    "is_default": false,
    "name": "No checkout",
    "organisation": {
      "$ref": "https://ils.rero.ch/api/organisations/1"
    },
    "pid": "8",
    "policy_library_level": false,
    "settings": [
      {
        "item_type": {
          "$ref": "https://ils.rero.ch/api/item_types/4"
        },
        "patron_type": {
          "$ref": "https://ils.rero.ch/api/patron_types/1"
        }
      },
      {
        "item_type": {
          "$ref": "https://ils.rero.ch/api/item_types/4"
        },
        "patron_type": {
          "$ref": "https://ils.rero.ch/api/patron_types/3"
        }
      },
      {
        "item_type": {
          "$ref": "https://ils.rero.ch/api/item_types/5"
        },
        "patron_type": {
          "$ref": "https://ils.rero.ch/api/patron_types/3"
        }
      },
      {
        "item_type": {
          "$ref": "https://ils.rero.ch/api/item_types/6"
        },
        "patron_type": {
          "$ref": "https://ils.rero.ch/api/patron_types/3"
        }
      }
    ]
  }
```

**Comment by BadrAly** [comment]
Should be fixed after merging https://github.com/rero/rero-ils/pull/210

**Comment by iGormilhit** [comment]
@BadrAly Very nice! If true, could you add in the commit message:
`* FIX Fixes #209`
Thanks, and sorry for the annoyance.

**Comment by iGormilhit** [comment]
@BadrAly I don't think that rero/rero-ils#210 is fixing this issue:

![capture_170](https://user-images.githubusercontent.com/1557213/54130869-7e8fd900-4411-11e9-899e-47e952c75b84.png)

**Comment by BadrAly** [comment]
Correction:
The circulation policy controls the display of the request button. This part is working.
The current logic is : An item is available if it has a status on_shelf and has no requests. (no relations with item type + patron type)

**Comment by iGormilhit** [comment]
Should be fixed by https://tree.taiga.io/project/rero21-reroils/task/797

**Comment by iGormilhit** [comment]
Fixed by https://github.com/rero/rero-ils/pull/491.
