### ISSUE TITLE
Entered data can be easily lost in the modal window of the user editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2098]
**How it works**

Entered data can be easily lost in the modal window of the user editor. For example with one click outside of the window, all data is lost without confirmation.

**Improvement suggestion**

Find a solution to avoid this, for example:
* a click outside of the modal window does not close the window
* the form is not in a modal window
* the modal window take the entire screen so that it is impossible to click outside
* other solution welcome

**Comment by iGormilhit** [comment]
May be not fixed in `v1.4.4.`.
