### ISSUE TITLE
Pointer in the screen is too low after having added a new field in the long editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2103]
**How it works**

When I add a field in the long editor, I cannot see it because the pointer in the screen is too low. That is, the new field is a bit to high on top of the screen and not completely visible.

**Improvement suggestion**

The new added field is more visible. The pointer is lower vertically.

**Comment by iGormilhit** [comment]
@jma or @zannkukai 

I think that this is due to the sticky top menu, that's hovering the page content.

https://github.com/rero/ng-core/blob/5866e27a8d5179655167cd0e423f40de0c16fef8/projects/rero/ng-core/src/lib/record/editor/editor.component.scss#L36
