### ISSUE TITLE
Cannot read property `default_currency` when displaying items in pro interface

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#2135]
In the pro interface when visiting the item details view, the console of the navigator throws this error message:

```
ERROR TypeError: Cannot read property 'default_currency' of undefined
    at e.get organisationCurrency [as organisationCurrency]
```

**To Reproduce**

1. Login to pro interface as a librarian or system_librarian
2. display the item details view https://ilsdev.test.rero.ch/professional/records/items/detail/1640
3. the error is displayed in the console of the navigator.

* server: [ilsdev.test.rero.ch]
* version: `v0.14.0` 
<img width="1498" alt="Screenshot 2021-07-09 at 10 31 58" src="https://user-images.githubusercontent.com/26998238/125050547-5593b780-e0a2-11eb-8b79-47e875fe867c.png">

**Comment by PascalRepond** [comment]
Cannot reproduce, has probably been fixed tangentially.
