### ISSUE TITLE
cli: import users does not update the user record

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#2142]
The cli `fixtures.import_users` used to load new and modified patron records. For modified records, this cli does not update the fields of the `user` record. 

Updates to the `patron` record works OK.

- records affected by this bug are the delta_1 and delta_2 patrons

**Comment by iGormilhit** [comment]
@BadrAly Please, next time, respect the issue template. It helps a lot!

**Comment by PascalRepond** [comment]
Is this still relevant, and is this really high priority? @BadrAly
