### ISSUE TITLE
Some IdRef authorities appear in more than one MEF cluster

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2144]
**Describe the bug**

Some IdRef authorities appear in more than one MEF cluster. Consequence: the document are linked to one or another of the duplicate. See screenshot.

**To Reproduce**

See screenshots.

**Expected behavior**

* An IdRef authority always exists in only one cluster and all document are linked to it.

**Context**

* server: production (https://bib.rero.ch)
* version: `v1.4.0`

**Screenshots**

Duplicated authority. In Virtua, all 30 documents are linked to the same authority.
![image](https://user-images.githubusercontent.com/8154915/125203311-2767d080-e278-11eb-896d-2ca2bee752e5.png)

Other example: Lucinda Riley
![image](https://user-images.githubusercontent.com/8154915/125203449-a8bf6300-e278-11eb-9640-a575c59d3936.png)
Other example: Adam Horowitz
![image](https://user-images.githubusercontent.com/8154915/125203455-b674e880-e278-11eb-8768-99f40fb58ad4.png)

**Comment by rerowep** [comment]
The cases were solved by hand. We have to implement sync with MEF to solve futur simular cases.

idref 080779387 ['10413493', '2649008']
idref 080559271 ['1022676', '3565174']
idref 153832592 ['1533917', '8378718']
idref 172528860 ['8759315', '9032503']

**Comment by PascalRepond** [comment]
This is linked to an currently prioritized US: https://tree.taiga.io/project/rero21-reroils/us/1749
