### ISSUE TITLE
URL in e-mail sent to patrons with the wrong instance's URL

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2151]
**Describe the bug**

See screenshot.

**To Reproduce**

See screenshot.

**Expected behavior**

Always the URL of the current instance is sent in the notifications.

**Context**

* server: bib.rero.ch
* version: `v1.4.1`

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/125407265-fdb6c280-e3b9-11eb-8e03-87104f547b02.png)

**Comment by iGormilhit** [comment]
@rerowep changed the option in the bib.rero.ch instance.
