### ISSUE TITLE
Request is sent to the wrong e-mail and even if the document is on loan

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2152]
**Describe the bug**

A) `request` notifications are sent to the wrong e-mail
B) `request` notifications are sent when the item is on loan (should not)
C) some patron notifications (due_soon, availability, reminders, recall) are sent to the library (should be sent to the patron)
D) `booking` notifications are sometimes not sent

See examples below.

**To Reproduce**

To be completed according to examples.

**Expected behavior**

A) Requests: they are always sent to
1. E-mail specified in the item location: `notification_email` (if `send_notification`=true)
2. Else: e-mail specified in the library: `notification_settings.email` (if `type`=request)
3. Else: not sent

B) `request` notifications are sent when a request is done AND the item is on shelf (no active loan, no other pending loan).

C) Patron notifications (due_soon, availability, reminders, recall) are
1. Sent to patron if communication chanel is e-mail (to main e-mail, to additional e-mail, or to both if applicable)
2. Else: sent to library

D) `booking` notifications are sent.

**Context**

* server: bib.rero.ch
* version: `v1.4.1`

**Examples**

* (B) this item is on loan. No "request" notification should be sent for it.

Von: noreply@rero.ch <noreply@rero.ch>
Gesendet: Montag, 12. Juli 2021 16:34
An: MEDIATHEK-WALLIS-BRIG
Betreff: Bestellung

Datum: 12.07.2021, 16:34:20

Titel: Neue Geländespiele : 21 Ideen für die Praxis / Simon Schild

Strichcode: 1011181295
Standort: BRIG - Mediathek Wallis / Erwachsene
Signatur: 793.7

Abholort: Brig - Mediathek Wallis
Leser: 2010530000

---

De : noreply@rero.ch <noreply@rero.ch> 
Envoyé : lundi, 12 juillet 2021 13:32
À : BMDA Interne
Objet : Demande

Date: 12 juil. 2021, 13:32:14

Titre: Une soeur / scénario & dessin Bastien Vivès

Code-barre: 70133600
Localisation: Bibliothèque municipale de Delémont - section adultes / BD auteur
Cote: BMDA VIV

Lieu de retrait: Bibliothèque municipale de Delémont - section adultes
Lecteur: 2050145013

---

* (A) this e-mail was sent to MV-Sion for an item belonging to Collombey. It has no e-mail object but it is a request. Notification settings are ok on Collombey's library.

De : noreply@rero.ch <noreply@rero.ch>
Envoyé : lundi, 12 juillet 2021 15:24
À : Pret MVSION Objet : Demande

Date: 12 juil. 2021, 15:24:07

Titre: Soyez l'expert de votre bébé / Mélanie Bilodeau

Code-barre: 1012020812
Localisation: COLLOMBEY - Bibliothèque communale et scolaire  / Documentaires adultes
Cote: 613.9 BILO

Lieu de retrait: Sion - Médiathèque Valais
Lecteur: 06502108

---

* (C) this "availability" e-mail was sent to the library instead of patron. The patron has an addition communication e-mail AND correct communication channel.

Date-time: 13.07.21, 8h20
Barcode: 1051238767

---

* (C) this "recall" e-mail was sent to the library instead of patron. The patron has an addition communication e-mail AND correct communication channel.

Date-time: 13.07.21, 8h20
Barcode: 1051238767

---

* (D) no `booking` notification was sent for this item that was checked-in on 13.07.21 at 10h04 in Bulle, with one request
 
https://bib.rero.ch/professional/records/items/detail/1321623

**Comment by iGormilhit** [comment]
A, B, D are fixed by #2164.
