### ISSUE TITLE
Item availability is not displayed in 3 situations

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2170]
**How it works**

Item availability is not displayed:
1. on item detailed view
2. on document detailed, for issues (public)
3. on document detailed, for issues (pro)

**Improvement suggestion**

It is always displayed.

**Screenshots**

Item detailed view (case 1)
![image](https://user-images.githubusercontent.com/8154915/125618836-f5b2c94d-bdfb-4b65-9202-ad17779e8118.png)

Document detailed view (professional interface) (case 3)
![image](https://user-images.githubusercontent.com/8154915/125618796-3c20a655-059a-4e3b-aeee-4c01aa58aeb8.png)

Document detailed view (public interface) (case 2)
![image](https://user-images.githubusercontent.com/8154915/125618682-70de0d23-2cf5-415d-ad74-889fdbb443d3.png)

**Comment by zannkukai** [comment]
@pronguen I'm unable to reproduce/found the third situation problem. Do you have an URL to a current example ? Thx

**Comment by pronguen** [comment]
@zannkukai I retested it and the case nr. 2 (public interface) is solved in production.

For case nr. 3 (pro interface, 2nd screenshot - sorry it's a mess), it also works correctly... but the display is different: the green/red dot is missing, as well as the number of requests.

**Comment by zannkukai** [comment]
@pronguen Great. My PR should solve these problems.
you mention "the number of request" for pro-interface. At this time isn't not included, is it necessary ? If yes, due to screen spaces available, the number of request takes place under the status text. Are you agree ?

**Comment by pronguen** [comment]
@zannkukai 

> At this time isn't not included, is it necessary ?

It's better from a UX point of view: the availability would then be displayed in the same way in all views

> If yes, due to screen spaces available, the number of request takes place under the status text. Are you agree ?

Yes of course. Most of the items/issues have no request anyway.

**Comment by zannkukai** [comment]
@pronguen 
Serial item availability with 1 pending request.
![image](https://user-images.githubusercontent.com/10031585/149777909-7c11ef81-4552-49e0-95f2-31e8918eba0b.png)
The display isn't perfect but an issue already exists to improve it : https://github.com/rero/rero-ils/issues/2554
