### ISSUE TITLE
Failed checkouts are saved in the circulation history of the concerned item

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#2173]
When a librarian tries to scan the item barcode for a checkout twice. The second scan normally fails with the error message:

`400 MultipleLoansOnItemError: Multiple active loans on item`

The system captures the two transactions and adds two entries in the circulation history of the scanned item.

* server: [bib.rero.ch]
* version: `v1.4.1`

**Comment by PascalRepond** [comment]
Cannot reproduce, has probably been fixed.
