### ISSUE TITLE
Person and corporate body search should be restricted on the organisation scope

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2176]
**Describe the bug**

* When searching persons or corporate bodies, we find all resutls
* On the person/corporate body page, the linked documents are from all organisations

In the public view, this is working!

**To Reproduce**

1. Look for person "Pastier, Minouche, 19..-...." (logged in as an RBNJ librarian)
2. Open the person detailed view
3. There is one document linked: Confitures à l'ancienne : plus de 100 recettes gourmandes 
4. This document has no items in organisation RBNJ

**Expected behavior**

This was working before. It is a regression. In the public view, this is working!

* I find only persons/corporate bodies with items linked to my organisation.
* On the detailed view of the person/corporate body, I have the list only of the documents linked to my organisation.

**Context**

* server: bib.rero.ch
* version: `v1.4.2`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by Garfield-fr** [comment]
We have removed the document filtering in the administration interface. It is logical that the documents now appear in the "person/corporate" section
