### ISSUE TITLE
Due date not computed correcty (also after renewal)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2198]
**Describe the bug**

Case 1: Renewal date is sometime one day later than checkout date, and does not respect the open days of the library.

Case 2: The loan duration is not exactly the same than in the circulation policy (in general 1 or 2 days longer) and does not respect the library open days.

**To Reproduce**

Case 1
1. Take a patron account
2. Use two items with the same item type.
3. Set the same loan and renewal duration (for inst. 28 days for both)
4. Do a renewal on one item and a checkout on the other
5. See the different due dates

Case 2
1. Log in bib.rero.ch as a Valais professional
2. Do a checkout for a standard patron with a standard item (should be a 28 days checkout)
    * use item barcode `test_rero` on patron.pid `223550`
3. See that the due date is not correct

**Expected behavior**

Due date respects the circulation policy settings and the library open days.

**Context**

* server: [ils.test.rero.ch][1] and production
* version: `v1.4.3`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by ManaDeweerdt** [comment]
I'm note sure if it is linked but on our instance (ver.1.4.9), we tested checking out an item with a circulation policy 'onsite' (0 days).
The item should be overdue the same day at night but on the user account the item is overdue the next day.
Note: the due date in the overdue notification is correct.
In the screenshot below, the due date should be the 6/09 PM but it says 7/09 on the user account.
![image](https://user-images.githubusercontent.com/12396034/132481799-ccf2d830-b502-47a2-b95e-3495a6b7c80f.png)
![image](https://user-images.githubusercontent.com/12396034/132481705-407200a7-597b-474c-b130-d4d4c5f2d7d9.png)
