### ISSUE TITLE
Item local fields and item temporary circulation category should be indexed in the document

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2211]
## How it works

They are currently not indexed in the document.

## Improvement suggestion

They are indexed in the document (but check the potential performance issues of this!).

## Use case

Create links to the document public view, with specific search results, for instance the new acquisitions, but filtered with the temporary circulation categories that are available. Currently, those links include also all documents that are in acquisition or in treatment.

### Test the use case

* a library has 10 codes (acq1, acq2, acq3) as subdivision for its new acquisitions. They are saved as local fields of the item.
* this library want a specific link/URL from its website to RERO ILS public interface for the new acquisitions
    * for a subdivision, excluding some item temporary circ category (imagine all item that have the temporary category "in acquisition")

Example: link to all *documents" where one item (⚠️ nested)
1. has an item with local code "acq1"
2. AND is neither [with temporary circulation category] "in acquisition" nor "missing"
3. AND was acquired in the last 3 months

#### How to test
![image](https://user-images.githubusercontent.com/10031585/168278874-e882324d-8a7a-4dbd-a70a-56796f8c83f3.png)

```
https://localhost:5000/api/documents/?q=holdings.items.local_fields.fields.field_1:acq1%20AND%20!holdings.items.temporary_item_type.pid:14
&new_acquisition=2022-05-01
```

**Comment by zannkukai** [comment]
If I remember well, we removed the local_fields indexation for performance issue.
