### ISSUE TITLE
Overlap of opening hours

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#222]
When editing library opening hours, the system indicates a false overlap when the eary period is entered after the late period (ex: 14.00-16.00, 10.00-12.00).
It should accept the two periods and reorder them automatically.

**Comment by NicolasLabat** [comment]
Ok, the system accepts periods not correctly ordered and reorders them.
Example : Friday originally closed. Add following opening hours : 14:00-18:00, 08:00-12:00
Display after saving : 08:00-12:00, 14:00-18:00
But remains the problem afterward : when editing the opening hours, Friday is indicated as closed.
