### ISSUE TITLE
UX of date exceptions

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#223]
Improve UX of date exceptions:
1. For a "one day" exception, the exception cannot be saved if it is not repeated
2. For a "one day" exception, the repeat option "every 1 day" should be disabled as it makes sense only if there is an end to the exception.
3. Clarify the button "Days period" and align it with the ON/OFF option. Example: "The exception last more than one day: ON/OFF"

**Comment by NicolasLabat** [comment]
It remains a bug : when enter a date exception, activate/deactivate the repeat button has the effect to disable the OK button.
