### ISSUE TITLE
Requests for patrons by librarians are impossible with librarian accounts of a specific library

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2234]
**Describe the bug**

When connected as a librarian working at BPUN (RBNJ), it impossible to create request for patrons on every item that are not owned by the BPUN library. The BPUN library deactivate request on its own items during holidays.

The pickup location does not matter, for every pickup the request is impossible.

-> Hypothesis: if the pick-up location of the login library does not allow the requests, there are server errors.

**To Reproduce**

1. Log in as a librarian in the professional interface (try on bib.test.rero.ch).
2. Verify the selected library is BPUN.
3. Find an item to request in the professional interface.
4. Try to place a request for a patron. See the error. (See screenshot below).

**Expected behavior**

The request should succed.

**Context**

* server: <http://bib.rero.ch>, <https://bib.test.rero.ch>
* version: `v1.4.5`.

**Screenshots**

![ksnip_20210722-170428](https://user-images.githubusercontent.com/1557213/126662464-9a9dd6c4-ff75-450e-9cdb-9b1293736d92.png)

**Additional context**

From the patron point of view, any request with a pickup libary of the BPUN will also fail.

**Comment by pronguen** [comment]
I was not able to reproduce this behaviour. I could place a request on this document

**Comment by iGormilhit** [comment]
@pronguen 

On <https://bib.test.rero.ch>, as a patron, I tried to place a request on [the same document][doc], holdings of *Bibliothèque des Archives de l'Etat de Neuchâtel (Neuchâtel): Réserve)*, selecting *Bibliothèque publique de Neuchâtel - lecture publique* as a pickup location, and the request fails: `https://bib.test.rero.ch/api/item/patron_request 403 forbidden`.

![ksnip_20210728-110507](https://user-images.githubusercontent.com/1557213/127296057-6787ff2f-b858-4533-8156-e317ac4df5b7.png)

As a librarian, placing a request on the same item, on behalf of a patron, selecting *Bibliothèque publique de Neuchâtel - lecture publique* as a pickup location, and the request fails: `https://bib.test.rero.ch/api/item/patron_request 403 forbidden`.

![ksnip_20210728-111406](https://user-images.githubusercontent.com/1557213/127296991-c0ac5446-f6e0-49a9-b6c1-d33ea9d5d2d4.png)

I have the exact same behavior on <https://bib.rero.ch>.

I'll try to reproduce on <https://ils.test.rero.ch>.

[doc]: https://bib.test.rero.ch/rbnj/documents/241229

**Comment by pronguen** [comment]
@iGormilhit I could reproduce it on ils.test.rero.ch:
1. Disallow requests on all locations of a library
2. Log in as a librarian of this library
3. Try to do a request on an item of another library (no matter what the pick-up location is)
4. Error in the screenshot

![image](https://user-images.githubusercontent.com/8154915/127318789-f743f16d-3246-4d66-9ce6-8e9aa1572abb.png)

Expected behaviour:
Disallowing request on a location has an effect only on the items of this location

**Comment by iGormilhit** [comment]
@pronguen Thanks a lot!

This also prevent a patron to place a request on any item not belonging to this library, but with this library as a pickup location.

**Comment by pronguen** [comment]
@iGormilhit This bug still happens on ils.test.rero.ch (v.1.4.11). Could you verify on your side and reopen the issue?
