### ISSUE TITLE
The collection search page of the public interface is available, even if there's no collection

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2236]
**How it works**

In the public interface of the organisation, the link to the collection is available even if there's no collection.

https://bib.rero.ch/vs/search/collections?q=&page=1&size=10 (you may need to reload the page).

**Improvement suggestion**

When there's no collection, we should either:

- Display some text that explains that there's no collection.
- Or avoid to display the link to the collection list of the public interface.

**Comment by zannkukai** [comment]
This is the same behavior for all search page (ex: document search with no result : https://bib.rero.ch/global/search/documents?q=boudiou&page=1&size=10).

For my opinion, we need to improve the initial dashboard of the professional interface a lot including only consistent information about the current logged user for the current used library. Inspiration from Invenio-ILS ? 
https://files.gitter.im/59c3604fd73408ce4f76b460/zUF3/Screenshot_2021-07-14_at_11.44.53.png

This will be part of a specific US

**Comment by iGormilhit** [comment]
@zannkukai You are right about the professional interface, but this issue/enhancement is for a public interface search page.
