### ISSUE TITLE
Generate square brackets in genre_form field 

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2237]
**How it works**

-->Genre_form fields were imported from Virtua without square brackets
![image](https://user-images.githubusercontent.com/31695537/126747372-21009e5c-5709-4962-899b-2a8c6ac7a213.png)

**How it should works**

  All genre_form fields should have square brackets
Generate square brackets only in genre_form fields thart have none
![image](https://user-images.githubusercontent.com/31695537/126747914-a8d6c0df-c14d-4750-9bd2-23a97430edf7.png)

**Comment by pronguen** [comment]
According to RERO+, the RERO RAMEAU concepts have to be in MEF without brackets, as there is a specific field indicating if they are genre/form or not.

There will remain some brackets when the local subjects are still in the documents. With the full shift to the RERO RAMEAU links, this will no more be the case.
