### ISSUE TITLE
Make the document typehead of the document editor usable

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2249]
**How it works**

In the document editor, in field like `partOf` and `document_relation`, a typehead allows to search for a specific document to be linked to. But the results only provide the title, which is not enough to unambiguously identify a specific document.

**Improvement suggestion**

The result list should display some identifiers such as the ISBN or the ISSN and provide a link to the document, as it is done when linking to a contribution.

**screenshots**

![Link to a document](https://user-images.githubusercontent.com/1557213/127326377-c9907167-74b2-4a19-85cd-5db6403e846c.png)

![link to a contribution](https://user-images.githubusercontent.com/1557213/127326443-729668d2-3d46-4753-9a6e-d4a76dce1d72.png)

**Comment by Garfield-fr** [comment]
The new menu presentation

<img width="801" alt="menu" src="https://user-images.githubusercontent.com/48578/128457212-405981b1-84d0-4d73-a866-fab6b4e71b2d.png">
