### ISSUE TITLE
Deleting the last issue on a serial holding makes the "show more" link appear twice

### ISSUE THREAD

**Issue by Garfield-fr** [rero/rero-ils#2254]
**Describe the issue**

When deleting the last issue of a holding's collection, the "show more" link appears twice

<img width="1145" alt="issue_delete" src="https://user-images.githubusercontent.com/48578/127603067-6bf38d22-a05c-419d-bf0c-e184586edc53.png">

**What should be done**

When deleting the last issue, only one "show more" link should remain.

**To reproduce**
1. Add a holdings on a document.
2. Add irregular issue on this holdings.
3. Delete the issue.

**Context**
version: 1.4.6

**Comment by PascalRepond** [comment]
Seems to be resolved now.
