### ISSUE TITLE
Dropdown fields: focus should enable to type letters to find a value within long list

### ISSUE THREAD

**Issue by Garfield-fr** [rero/rero-ils#2255]
**Describe the issue**

When you are editing a document (for example), and you open the "Language value" menu on language section and then type the 2 letters "fr" on the keyboard, you are redirected to the requests page. The shortcut is applied.

**What should be done**

Disable shortcuts when editing.

**To reproduce**
1. Create a document.
2. Go to the language section.
3. Click on the drop-down menu (do not put the cursor in the search field).
4. Type the 2 letters "fr" on the keyboard.

**Expected behaviour**

When the focus arrives in a dropdown list, it is possible to type letters in order to find a value within the list.

**Context**
version: 1.4.6

**Comment by pronguen** [comment]
Linked to #2104 

The shortcuts are activated because the focus is not set in the dropdown list.

As enhancement, I would prefer a better management of the focus.

**Comment by JoelleDosimont** [comment]
> Linked to #2104
> 
> The shortcuts are activated because the focus is not set in the dropdown list.
> 
> As enhancement, I would prefer a better management of the focus.

I agree with Nicolas. When opening a dropdown list, the cursor should automaticaly be in the search field.
