### ISSUE TITLE
Provide a way for patrons to view new acquisitions

### ISSUE THREAD

**Issue by paprickka** [rero/rero-ils#2264]
Patrons are interested to know what are the new and coming acquisitions their libraries have made or will make. Such a functionality is yet not available.

Providing a way to list and filter catalogue content based on the different facets, one being the acquisition date would be a value adding feature.

Patrons should be able to do this by themselves without support of librarians (as it was the case in RERO). The idea is to have something similar to what is available in e-bibliomedia for example, but extended to what also is in acquisition.

Ideally I would like to be able to filter catalogue content on the existing facets plus the acquisition date on some time periods like
- in acquisition
- last month
- last 3 months
- last 6 months
- ... 

Example : e-bibliomedia facet "Date de parution"
![image](https://user-images.githubusercontent.com/83698969/127994603-3a93c99a-3b50-4408-9f85-837f7b03f4e9.png)

**Comment by pronguen** [comment]
This point is part of the feature list of the RERO+ libraries, but has not yet been prioritised.

**Comment by iGormilhit** [comment]
I've mentioned this issue in the list of features to be prioritized by the libraries.
