### ISSUE TITLE
Request expiration date should be displayed on requests list for items to pick up

### ISSUE THREAD

**Issue by paprickka** [rero/rero-ils#2266]
Whenever an item a patron requested is available for pick up, the date until when he/she can pick it up is included in the mail he/she receives. However that date does not appear on the requests list.

That information should be added to the elements displayed on the requests list in addition to **Title**, **Pick up location** and **Status**.

As long as the status is not "to pick up" field should be empty or "-", else it should be the date until when the element has to be picked up.

**Comment by pronguen** [comment]
This is addressed by a user story that is in the current development sprint:
https://tree.taiga.io/project/rero21-reroils/us/1349

**Comment by iGormilhit** [comment]
As it is solved by the US mentioned, I'm closing this.
