### ISSUE TITLE
Whenever a library disables loans and requests, a message should inform patron

### ISSUE THREAD

**Issue by paprickka** [rero/rero-ils#2267]
**How it works**

During this summer holidays, the Bibliothèque publique de Neuchâtel deactivated the possibility to submit requests for items.

However, when I tried to request a book, the library was listed and the **_Confirm your request_** button was active. But clicking on it did nothing except having the wait icon (small circle turning) going on for ever.

**Improvement suggestion**

At some point in the workflow of requesting an item, the patron should be informed that this action is not available at the time and until when it will be unavailable.

-> the request button appears, but it is disabled with a message on mousehover.

**Comment by pronguen** [comment]
> when I tried to request a book, the library was listed and the Confirm your request button was active. But clicking on it did nothing except having the wait icon (small circle turning) going on for ever.

This bug is addressed in the resolution of https://github.com/rero/rero-ils/issues/2234
