### ISSUE TITLE
A template created from an existing record can't be used

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#2269]
**Describe the bug**

When a template is created from an existing record (from the record editor in update mode), it can't be used: it cause an error during the record submission.

**To Reproduce**

1. Edit an existing record
2. Save as template
3. Create an new record from this template
4. Submit the record: an error is given

**Expected behavior**

**Context**

* server: bib.rero.ch
* version: v1.4.6
* sentry Event 926b1c0bae264efc9d0e687b604854e2

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

**Additional context**

__Note__: the problem is that the pid is not removed during the template creation. A mass correction should be done to fix the existing templates.

**Comment by BadrAly** [comment]
5.8.2021: Removed the `pid` from the following templates in production:
```
