### ISSUE TITLE
Temporary circulation category : circulation info not displayed

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2273]
**Describe the bug**

The circulation info of the temporary circulation category  is not displayed in the public and professional interface.

**To Reproduce**

1. Add a temporary circulation category to an item. Ex: no checkout.
2. It should display 'prêt non autorisé' but it's not.

**Expected behavior**

The circulation info of the temporary circulation catgory should be displayed at least in the public interface.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v0.14.6` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/12396034/128478640-da3a6368-51bc-476e-bd72-79a8806a2cb5.png)

**Comment by pronguen** [comment]
Following our PO meeting of 10.08.21, the needs must be clarified by UCL team.

Options:
* status quo (only circulation info of the main circulation category is displayed)
* display the circulation info of the temporary circulation category after the status (ex: "En acquisition - Pas de prêt, demandes possibles")

**Comment by ManaDeweerdt** [comment]
Status quo!
There was a confusion on our instance: some item types related directly to the circulation (on site, on seminar) were mapped as temporary circulation category.
