### ISSUE TITLE
Add identifiers fields for Document in relation (when label) and Series statement

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2275]
**How it works**

In the related document fields (ex. : Succeeded by) and the Series statement, it is not possible to add an identifier.

**Improvement suggestion**

Add the sub-field identifiers (at least ISBN and ISSN, ideally all types of identifiers should be possible) for the following fields : 
- seriesStatement
- Document in relation (only, if they are labels) : supplement, supplementTo, otherEdition, otherPhysicalFormat, IssuedWith, precededBy, succeededBy, relatedTo, hasReproduction, reproductionOf.

The sub-field is added on the same structure than `document.identifiedBy` with the same labels, display and conditionality (i.e. value/type required, source required if type=bf:Local).

**Comment by pronguen** [comment]
Problem with the `oneOf` in the editor linked to ng-core issue: [add ref]
