### ISSUE TITLE
Often the public and professional interface changes the language

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2277]
**Describe the bug**

Often the public and professional interface changes the language automatically.

See also #2705

**To Reproduce**

Impossible to reproduce at any time.

**Expected behavior**

The chosen language stays for the whole session, except if it is intentionally changed.

**Context**

* server: bib.rero.ch
* version: `v1.4.6` or the commit hash (see frontpage).
* browser: Firefox 90.0.2 (64-bit)

**Comment by pronguen** [comment]
A language change in the professional interface is not kept. The change should be made in the public interface, and will then impact the professional interface.

To be clarified: does the problem of language inconsistency also happen in the public interface?

**Comment by iGormilhit** [comment]
Each time the user reload the page, the locale is set according to the browser locale, which is very much annoying!

**Comment by pronguen** [comment]
This problem is still observed by the libraries in the version 1.8.0, therefore we re-open the issue.
