### ISSUE TITLE
Applying the library facet should impact the availability and the displayed items

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2278]
**How it works**

Currently, selecting a value in the facet "Library" filters only the document in the document search result. The user expects it to filter also the displayed items.

**Improvement suggestion**

When we apply a "Library" filters in the document search result:
* the document availability (in the document search result list) is calculated according to the selected values
* the items displayed in the document detailed view are filtered according to this facet
    * Ideally a button indicates that the items are filtered, and it can be removed.
    ![image](https://user-images.githubusercontent.com/8154915/128714322-c4eea027-32c8-46b0-a34b-407624c24288.png)

**Comment by ManaDeweerdt** [comment]
Linked to this:
In the public interface, in an institutional view, the status facet is not filtered by the institution.
Ex: https://ilsdev.test.rero.ch/aoste/search/documents?q=*&page=1&size=10&status=on_loan&document_type=docmaintype_series
'Stromata patristica et mediaevalia' has no item 'on loan' for Aoste.

**Comment by PascalRepond** [comment]
This feature is utterly unfeasible without a complete refactoring of the views. There is no simple way to pass the selected facets from a brief view to a detailed view and adapt the elements. This is the same as "previous/next" button in detailed view. Closing this as wontfix.
