### ISSUE TITLE
Notifications sent to the library (for printing) instead of the patron

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2279]
**Describe the bug**

Some notifications (recall, availability) sent to the library (for printing) instead of the patron.

Moreover, it is sometimes sent to the wrong library and without addressee block (see example 2)

**To Reproduce**

We don't know yet how to reproduce it. See examples below.

**Expected behavior**

The patron notifications (recall, availability) are always sent to the patron if communication channel is e-mail.

**Context**

* server: bib.rero.ch on 04.08.21
* version: `v1.4.6`

**Example 1**

In this case the availability notification was sent to the library:
* item: https://bib.rero.ch/professional/records/items/detail/2929301
* patron: https://bib.rero.ch/professional/circulation/patron/2030115527

**Example 2**
In this case the availability notification was sent to the wrong library, should have been sent to the patron:
* item: https://bib.rero.ch/professional/records/items/detail/3113506
* patron: https://bib.rero.ch/professional/records/patrons/detail/19066

> Von: noreply@rero.ch <noreply@rero.ch> 
> Gesendet: Montag, 9. August 2021 13:11
> An: MEDIATHEK-WALLIS-BRIG <MEDIATHEK-WALLIS-BRIG@admin.vs.ch>
> Betreff: Invitation à retirer un document
> 
> Chère lectrice, cher lecteur,
> Le document que vous avez demandé est maintenant disponible. Vous pouvez venir le retirer au bureau de prêt de la bibliothèque mentionnée ci-dessous.
> 
> Titre : Das Seelenleben des Kleinkindes und andere Beiträge zur Psychoanalyse / Melanie Klein Lieu de retrait : Sion - Médiathèque Valais
> Titre : Narzissmus : eine Theorie der psychoanalytischen Behandlung narzisstischer Persönlichkeitsstörungen / Heinz Kohut Lieu de retrait : Sion - Médiathèque Valais
> 
> A retirer jusqu'au : 20.08.2021
> 
> Si le document n'est pas retiré dans les délais, il sera remis en circulation pour d'autres personnes.
> Vous pouvez consulter votre compte et prolonger la durée de prêt de vos documents à l'adresse : https://bib.rero.ch/vs/patrons/profile
> 
> Avec nos compliments
> 
> SION - Médiathèque Valais
> Rue de Lausanne 45, CP 182, CH - 1950 Sion

**Comment by zannkukai** [comment]
Address block for mail notification has added into https://github.com/rero/rero-ils/pull/2312 PR

**Comment by pronguen** [comment]
@jma Here the issue about the location that is no more pick-up: https://github.com/rero/rero-ils/issues/2162

**Comment by iGormilhit** [comment]
Solved by https://github.com/rero/rero-ils/pull/2312.
