### ISSUE TITLE
Add a button "Link to an entity" for contributors without any link

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2283]
**How it works**

When importing a record, for contributors, it's necessary to switch to "Link to a person / corporate body entity". Doing so, you delete the information that are already filled in the original record and there is no going back.

**Improvement suggestion**

When contributors have no link to the MEF, we need to easily query the MEF without loosing the existing information.
Proposition : 
- Add a "Link to an entity" button to query the MEF, based on the name for a person or on the Corporate body name and the name of the subordonate units.
- Results appear in a pop-up window.
- You can either : choose a link (the type is automaticaly set to the correct type of link : person or corporate link) OR cancel the request (without deleting the information already present).

**Comment by pronguen** [comment]
I would not use "MEF" in the interface button.

What about "Link to an entity" instead of "Check the MEF"?

**Comment by JoelleDosimont** [comment]
> 
> 
> I would not use "MEF" in the interface button.
> 
> What about "Link to an entity" instead of "Check the MEF"?

Yes, it's much better ! I will update the issue

**Comment by PascalRepond** [comment]
There is a simple way to query MEF in this case: add a new contribution field and search for a MEF link. If a link is found, delete the field with the textual/local entity.
