### ISSUE TITLE
Patron search doesn't work as expected

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#229]
Example: admin/records/patrons?q=katie gives no result

**Comment by rerowep** [comment]
Is it working like this:  _admin/records/patrons?q=Katie_

Do we need lowercase search?

**Comment by iGormilhit** [comment]
@rerowep Of course, search should be case insensitive. And not limited to full words.

`admin/records/patrons?size=10&page=1&q=kat` should give results too.

**Comment by pronguen** [comment]
> `admin/records/patrons?size=10&page=1&q=kat` should give results too.

To be addressed in en enhancement if we really want that behaviour.

**Comment by pronguen** [comment]
To be solved by [US 671](https://tree.taiga.io/project/rero21-reroils/us/671)
