### ISSUE TITLE
Some links should be opened in a new tab (`target="_blank"`)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2291]
**How it works**

Currently, almost all links are opened within the same page. This was done this way according to some good practices, arguing that the user has always the choice to decide himself/herself to open any link in a new tab or window.

Various feedbacks from the fields indicate that for some link, the user expect automatically a new tab. 

**Improvement suggestion**

Links are opened in a new tab in the following cases:
* links within the editor (for ex. in the MEF suggestions) -> so that the user does not lose the entered data
    * opens already in a new tab
* link to the help (public + pro interface) -> because most probably the user wants to have the help in parallel to RERO ILS, or at least will come back to RERO ILS
* link to the public interface -> because it is a kind of external link (leaving the pro interface) and the user probably want to keep a tab with the pro interface.
* link to the professional interface
    * to be clarified, no specific use case indicates that this should open in a new tab, except the coherence with inverse link (from pro to public)
* document detailed view: link from field `document.electronicLocator` and `item.url` -> because they are always external links

To be clarified: add an icon to indicate that the link opens in a new tab?

**Comment by iGormilhit** [comment]
@pronguen I'm sorry but this is always the same logic. I'm keeping with the idea that link that may result in losing data or interrupting an action could be opened in a new tab or windows. But that's all. Othewise, the user **is limited in its choices**, especially users that have to use the keyboard.

I do think that the users should learn how to use a computer an open desired link in new tab or windows using either the middle click or right-click.

https://a11y-guidelines.orange.com/fr/web/designer/navigation-generale/#eviter-les-boites-de-dialogues-et-louverture-de-nouvelles-fenetres

Furthermore, it won't be easy to find an icon different from the external link icon.

I cannot and won't impose my opinion, of course, but I don't understand why some users would impose their opinion to all the users.
