### ISSUE TITLE
Permission: a librarian shouldn't be able to modify a CIPO at library level

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2299]
**Describe the bug**

A librarian affiliated to library A can modify a circulation policy set at library level with this location.

**To Reproduce**

1. Log in as a system librarian.
2. Modify a cipo and add some library.
3. Log in as a librarian

**Expected behavior**

A librarian shouldn't be able to modify a cipo.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.4.6` or the commit hash (see frontpage).

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by zannkukai** [comment]
This behavior was the first one coded. The current behavior seems a specific changes.
Need to be checked during a PO session to be sure.

**Comment by iGormilhit** [comment]
@zannkukai @ManaDeweerdt I think that long ago, it was desired that a librarian should be able to edit circulation policies of it's own library, to gain autonomy and to leverage the system librarian tasks.

So as it is, it works as excpected, as @zannkukai is saying.

I agree that we should talk about it in a PO session.
