### ISSUE TITLE
Check-out of an item "in transit"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#230]
An item which is "in transit" cannot be checked out. This should be possible, if the item has no request, or if the request is for the user concerned by the check-out.

**Comment by BadrAly** [comment]
According to the state chart `in-transit` items needs the action `receive` first before the `checkout` action. 

We can allow the execution of  these two actions 'receive` + `checkout` in one step  ONLY if the librarian is logged on to the `library` = `request.pickup_library`. Do not know if this

**Comment by pronguen** [comment]
Two cases:
1. The item has no request (it is in transit to owning library): in that case, it should be possible to check it out.
2. The item has a request (it is in transit to pickup library): in that case, is should be
2.1 possible to check it out, if it is for the user holding a request on this item (first in the request list)
2.2 impossible to check it out, if it is for another user (holding no request, or holding a request but not at first position in the request list)

Ideally, the state chart must allow a check-out, even if it not from the pick-up library, as soon as the above mentioned conditions are satisfied. There is no need (no use case) to verify the pick-up library.

**Comment by BadrAly** [comment]
👍 OK to resume in state chart terminology:-

Case 1: checkout is possible if `loan.status` = `ITEM_IN_TRANSIT_TO_HOUSE` and item has no requests
 
Case 2.1: checkout is possible if `loan.status` = `ITEM_IN_TRANSIT_FOR_PICKUP` and `loan.patron_id` = checked-out patron

In these two cases an automatic `receive`  is needed for the item at the checked-out-library ( and this can be done on the fly)
