### ISSUE TITLE
Patron should be able to define preferences in his/her account

### ISSUE THREAD

**Issue by paprickka** [rero/rero-ils#2301]
**How it works**
Today when you place a request, you're proposed with the full list of pick up locations availabe with no pre-selection. It would be ideal as a patron to have the possibility to define a preferred pick up location in the profile. Then that location would be the one preselected when you place a request.
The same logic could be applied for the quantity of loans displayed in the patron account.

**Improvement suggestion**

Add some parameters that the patron account can edit on his/her profile (public view):
* "Preferred library"
    * Description: "The items of this library will be displayed on top of the list"
    * Choices: all libraries of the organisation + option "None"
    * Effect: in the organisation view, holdings of the preferred library are displayed first (warning: effort could be important)
* "Preferred pick-up library"
    * Description: "Pick-up location preselected when doing a request"
    * Choices: all pick-up locations of the organisation + option "None"
    * Effect: the preferred pick-up location is preselected when doing a request (for standard and ILL Request both)
* "Loans displayed in the account"
    * Description: "Number of loans displayed by default when opening the patron account. Choosing \"all\" can impact the loading time of the page."
    * Choices: 10, 20, 50, all
    * Effect: see description

**Comment by iGormilhit** [comment]
Related to https://github.com/rero/rero-ils/issues/1899.

**Comment by pronguen** [comment]
For me:
Priority 1: remove default pick-up location (the user must choose his/her pick-up location)
Priority 2 (low): add this optional setting in the patron account.
