### ISSUE TITLE
Impossible to save a duplicated document that does not contain all default values

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2308]
**Describe the bug**

Impossible to save a duplicated document that does not contain all default values. Example: saving a duplicated article is impossible, because an article does not contain a publication statement (`provisionActivity.statement`).

**To Reproduce**

1. Create a document with a missing or incomplete publication statement
2. Duplicate this document
3. Try to save

**Expected behavior**

Default values on optional fields should not prevent to save a resource without these optional fields.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.4.6`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by iGormilhit** [comment]
@pronguen I think it's related to https://github.com/rero/rero-ils/issues/2080.
