### ISSUE TITLE
admin interface: The status of the item is not updated after a request

### ISSUE THREAD

**Issue by Garfield-fr** [rero/rero-ils#2314]
**Describe the issue**

In the document view in the professional interface, when you make a request on a item (with the small basket), the status of the item does not change. To see the correct status, you must reload the page.

**Context**

ils.test.rero.ch, v1.4.6

**What should be done**

After the request on a item, update the status.

**Comment by ManaDeweerdt** [comment]
- [ ] We still have to reload the page to see the new status.
