### ISSUE TITLE
Flash message: bring user at top of the page

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#232]
When a flash message is displayed, the top of the page must be displayed, so that the user can see the message.

Example: in the circulation UI, the user must click on "apply" on the bottom of the page and he doesn't get any reaction of the system, even if his actions were applied. The page has to give reaction: move to the top, display ev. flash message.

**Comment by iGormilhit** [comment]
:warning: https://github.com/rero/rero-ils/commit/168dcd62f1431e615b663440b78be4ed3ee8028c do not fix this issue, because the message is still on top of the page, not visible by the operator if he/she has scrolled down …

**Comment by iGormilhit** [comment]
Taiga task: https://tree.taiga.io/project/rero21-reroils/task/832?kanban-status=1224893
