### ISSUE TITLE
Using the pager of the result page does not display the top of the page

### ISSUE THREAD

**Issue by paprickka** [rero/rero-ils#2322]
**Describe the bug**

In public view, when going through the different pages of a result list should load new page on it's top.

**To Reproduce**

1. Run a search for example on a term like "pendule"
2. Go to the bottom of the first results page
3. Click on any page number to go to it
![image](https://user-images.githubusercontent.com/83698969/130661001-176552ee-de53-4ad3-a39b-efc3e342749e.png)
4. The selected page is displayed, however, we're not at the top of it

**Expected behavior**

When changing page, we should be at its top, not at its "somehow" bottom.

**Context**

* server: bib.rero.ch
* version: v1.4.6
* browser: Firefox 91.0.1

**Comment by iGormilhit** [comment]
@paprickka Thanks for this issue!

**Comment by ManaDeweerdt** [comment]
Please add a pager at the top of the result page. Not only at the bottom.
