### ISSUE TITLE
Support e-mail addresses with non ASCII caracters

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2323]
**How it works**

Currently, RERO ILS has errors when it tries to send notifications to addresses with non ASCII caracters.

**Improvement suggestion**

RERO ILS is able to send e-mails to such addresses. It doesn't matter if the recipient server is not able to receive them.

**Comment by iGormilhit** [comment]
Our current SMTP service provider does not support non ASCII chars in e-mail address. Most of the mail client do not support non ASCII chars either (Thunderbird does not, for instance).

**Comment by pronguen** [comment]
@iGormilhit A discussion with UCL colleagues shows that, in France, it is more common to use diacritics in e-mails, especially in the academic community.

**Comment by iGormilhit** [comment]
@pronguen I know. The point is, that with our mail service provider, it is not possible. Considering the clients, I tried Thunderbird on Linux and K-9 mail on android and as soon I typed a non ASCII chars, an error message occured.

What I mean is that it won't be an easy task, as it depends on many factors.

@jma tried with Gmail and it's supporting this feature. Of course, it's Gmail. 🙂

**Comment by iGormilhit** [comment]
Some basic information on this topic: https://en.wikipedia.org/wiki/International_email
