### ISSUE TITLE
Circulation UI: "an error occurs on the server: [object Object]"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#233]
By trying to realize an normal check-out, I receive the following error:
"an error occurs on the server: [object Object]"

checkout of item "10000001010" for patron "2000000001" at library "Bibliothèque cantonale valdôtaine, site d'Aoste".

**Comment by BadrAly** [comment]
For a frech install, the item barcode `10000001010` has the item_type `No checkout`. This could be the reason.

**Comment by iGormilhit** [comment]
@BadrAly If this is the reason, then the alert message should be something else than an error. :smiley:
