### ISSUE TITLE
History tab of the patron is empty (public interface)

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2331]
**Describe the bug**

The tab of loan history of the patron in the public interface is empty even if the patron keeps the history. The corresponding history viewed from the professional interface is displayed correctly.

**To Reproduce**

1. Log in as a user that keeps the loan history.
2. Navigate to https://bib.rero.ch/global/patrons/profile
3. Display the history tab
4. See that it's empty
5. Check the same history from the professional point of view and see that there's an history.

This can be easily checked with the RERO+ system librarian of bib.rero.ch/vs

**Expected behavior**

The loan history should be displayed.

**Context**

* server: <https://ils.test.rero.ch> and <https://bib.rero.ch>.
* version: `v1.4.7`. Confirmed with `v1.4.8`.

**Comment by PascalRepond** [comment]
Is now fixed.
