### ISSUE TITLE
Some due soon notifications are sent too early

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2336]
**Describe the bug**

Some due soon notifications are sent too early. This happened in RBNJ and in RERO+VS, on 25.08.21. It was the date of deployment of the `v1.4.7`, maybe linked?

**To Reproduce**

Still unknown, see examples

**Expected behavior**

The due soon notification is sent as specified in the circulation policy.

**Context**

* server: <https://bib.rero.ch>.
* version: `v1.4.7`.

**Example**

Concerned item (pid:3039066) / patron (pid:18251) - vs

> Chère lectrice, cher lecteur,
> 
> Le délai de prêt des documents mentionnés ci-dessous arrive à échéance :
> Titre : Gestion des conflits / Marjorie Danna, Cécile Neuville
> Echéance : 18.09.2021

> Vous pouvez consulter votre compte et prolonger la durée de prêt de vos documents à l'adresse : https://bib.rero.ch/vs/patrons/profile
>  
> Avec nos compliments
> 
> SION - Médiathèque Valais
> Rue de Lausanne 45, CP 182, CH - 1950 Sion

**Comment by jma** [comment]
The due soon notification has been created before the renewal and processed after the renewal. We need to be sure to create and process the due  soon notification the same day.

**Comment by iGormilhit** [comment]
Due to failed workers, that are now monitored.

The https://github.com/rero/rero-ils/pull/2345 is related to this issue.
