### ISSUE TITLE
Document: the temporary location URL (route) is wrong

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2337]
**Describe the bug**

In the public interface, the link of the collection is not working on the document detail view.
 
**To Reproduce**

1. Find a collection. Click on the document url.
2. Click on the temporary location field. Ex: https://ilsdev.test.rero.ch/highlands/documents/4/
3. Right click on it. Ex: https://ilsdev.test.rero.ch/highlands/documents/4/highlands/collections/6
4. See error (page not found)

**Expected behavior**

The link of the temporary location field should redirect to the collection page.
**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2].
* version: `v1.4.7`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by iGormilhit** [comment]
The route is wrong. It adds the collection URL to the document detail view URL.
