### ISSUE TITLE
Request on an item which is checked out

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#235]
When a request is done on an item that is checked out, the request should not be displayed in the list of pending requests to validate.
When the check-in/receive of this item is done in the pick-up library, the status should not be "on_shelf", it should be "at the loan desk".

**Comment by BadrAly** [comment]
- Testing on https://github.com/rero/rero-ils/pull/219 (to be integrated asap)

1- unable to duplicate point number one using the following workflow:
login as:
Müller, Astrid @ library : Bibliothèque du Lycée de la Vallée d'Aoste
checked-out item item_barcode = 10000000019 to patron Simonetta/ Casalini: 2050124311 
re-login as : reroilstest+philippe@gmail.com and request item_barcode = 10000000019
re-login as Müller, Astrid @ library : Bibliothèque du Lycée de la Vallée d'Aoste
item is not showing on http://localhost:5000/admin/circulation/requests

2. for the second point, i was able to duplicate. 
however, the status can be correctly displayed in these two cases:
1. if you click the `requests` tab , 
2. clear the `Checkin/Checkout` tab and re-scan the item barcode

**Comment by pronguen** [comment]
login as:
Müller, Astrid @ library : Bibliothèque cantonale valdôtaine, site d'Aoste
checked-out item item_barcode = 10000018384 (item type:standard) to patron Smith/John: 2000000001
re-login as : reroilstest+helder@gmail.com and request item_barcode = 10000018384 (pick-up location: Bibliothèque cantonale valdôtaine, site d'Aoste)
re-login as Müller, Astrid @ library : Bibliothèque cantonale valdôtaine, site d'Aoste
Check-in item_barcode = 10000018384

Result:
1. Item is "on_shelf" with a request
2. Item appears in the list of the pending requests.
3. Helder didn't receive any notification

**Comment by iGormilhit** [comment]
I think this is not ok, because as I tested it, the patron that requested the item being checked in don't get any email.
