### ISSUE TITLE
Add indexes for retrieval when linkink document to another document or authority

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2352]
**How it works**

When cataloguing, to link a document to another document or to a MEF authority, only one index is proposed (generally Title index for documents or Access point for MEF): 

**Improvement suggestion**

In different cases the autocompletion does not propose the right document or authority to link. as  showned  in example below.
![image](https://user-images.githubusercontent.com/31695537/131678200-c9372768-d698-4989-9575-23c3fb8f5aed.png)

The enhancement proposal is to add other possibilities of retrieval mainly by identifiers . For example Title + ISSN + ISBN for 
Partof field

List of fields concerned (each with proposed indexes to add : [to be discussed by PO other indexes ? RERO ILS PID ?]
PartOf : Title / add  ISSN / ISBN
PreceededBy : Title : add ISSN / ISBN
SuccededBy: Title : add ISSN / ISBN
supplement: Title : add ISSN / ISBN
supplement of : Title : add ISSN / ISBN
IssuedWith : Title : add ISSN / ISBN
AlsoIssuedas: Title : add ISSN / ISBN
Othereditions : Title : add ISSN / ISBN
Work Access Point: IDREf and GND identifiers
contributors: IDREf and GND identifiers
Subjects: IDREf and GND identifiers

An separate  issue rero/rero-ils#2249 was done for display identifiers in autocompletion results

**Comment by ThierryClavel** [comment]
test : on ilsdev : search by ISSN in "contenu dans" field works but title is not brought back in field. When you click on blue arrow, 404 error "page not found"
![image](https://user-images.githubusercontent.com/31695537/132462811-43832cc2-2214-4169-81f8-6e3ba69d8b1c.png)

**Comment by iGormilhit** [comment]
@ThierryClavel 

> test : on ilsdev : search by ISSN in "contenu dans" field works but title is not brought back in field. When you click on blue arrow, 404 error "page not found"
> ![image](https://user-images.githubusercontent.com/31695537/132462811-43832cc2-2214-4169-81f8-6e3ba69d8b1c.png)

Yes, I've warned @jma about these two issues. Thanks.
