### ISSUE TITLE
document : display of subjects persons : living years

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2354]
**How it works now**

Living years of a person subjects are not displayed in public and professional interface.

![image](https://user-images.githubusercontent.com/31695537/131690905-eff09ca4-4e4b-4f73-9c3c-06720395e6fd.png)

**Improvement suggestion**

 It's a lack of information. Living years should be displayed: they are part of the authorized access point.
 It is done for contributors. It should be the same for subjects.

**Comment by PascalRepond** [comment]
Duplicate of https://github.com/rero/rero-ils/issues/2609
