### ISSUE TITLE
Make the field "gender" visible on the patron view

### ISSUE THREAD

**Issue by Jojomotte** [rero/rero-ils#2399]
**Improvement suggestion**
We need the field "gender" from the RERO account to be visible in the patron view (https://bib.rero.ch/professional/records/patrons/detail/40370).
Because this information is mandatory for the communication with patrons.
![RERO account with gender field](https://user-images.githubusercontent.com/34459570/134342284-e68b3127-0b6f-402b-b1d5-1f327b11714f.PNG)

**Comment by iGormilhit** [comment]
@Jojomotte May I remind you that this field is optional and can be edited by the user.
