### ISSUE TITLE
document editor : missing value "lat-latn" in language drop down menu

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2405]
In the dropdown menu that is used to define the *language/script* of parallel title, the value `lat-latn` is missing, thus preventing to describe a title in latin script.

`lat` is the correct code to add (checked in MARC code list for languages): <https://www.loc.gov/marc/languages/language_name.html#l>

**Screenshot of the issue**
![image](https://user-images.githubusercontent.com/31695537/134637673-dac5c680-5495-4363-a676-3fd79e7660cd.png)

**Comment by iGormilhit** [comment]
@ThierryClavel The code to be added is `lat` or `lat-latn`?

**Comment by ThierryClavel** [comment]
@iGormilhit the complete code to be added is lat-latn

**Comment by ThierryClavel** [comment]
is it possible to add another missing code or do I have to make another issue ? : 
the other missing code is : roh-latn (romanche language spoken and written in Switzerland)

**Comment by zannkukai** [comment]
@ThierryClavel The related PR is merged to 1.7.0 branch ; I can't reopen it :(
But I can create an new small PR to solve this problem without open a new issue.

**Comment by ThierryClavel** [comment]
super thank you @zannkukai
