### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by zidingz** [rero/rero-ils#2411]
Hey there!

I belong to an open source security research community, and a member (@noobpk) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by iGormilhit** [comment]
@zidingz Hi, thanks for pointing the Github recommendations. I'm going to read it and then I'll try to add the informations. In the meantime, you'll find on my personnal website my professional e-mail and gpg key, just in case @noobpk wants to contact me.

**Comment by iGormilhit** [comment]
@zidingz I've created a PR with some minimal information: https://github.com/rero/rero-ils/pull/2415.

**Comment by noobpk** [comment]
@iGormilhit Have you seen my report on hunter.dev yet?

**Comment by iGormilhit** [comment]
@noobpk As a matter of fact, I wasn't aware of that report and I have issue to find it.

**Comment by noobpk** [comment]
@zidingz Can you help me. @iGormilhit cannot access to view my report

**Comment by noobpk** [comment]
@iGormilhit Did you find my report for your repo? I see my report was updated status 

<img width="753" alt="image" src="https://user-images.githubusercontent.com/31820707/135115218-d1c8e137-c3a5-46e7-9182-72aa55c20fd6.png">

**Comment by iGormilhit** [comment]
@noobpk We received an e-mail with an URL of the report. We'll have to discuss internally about it, hopefully today. Thanks.

**Comment by noobpk** [comment]
@iGormilhit Hi, is everything alright.

**Comment by noobpk** [comment]
@iGormilhit Hi, Can you validate my report? .

**Comment by noobpk** [comment]
@BadrAly Looks like I can't reach @iGormilhit. Can you help me confirm the reports?

**Comment by JamieSlome** [comment]
Just for reference, both reports can be found here:

https://huntr.dev/bounties/b032ff4d-baff-4fba-b59b-6b2eeb5f0838/
https://huntr.dev/bounties/9ef8c74f-41f4-4f04-ba94-d7c507227c9c/

They are private and only accessible to maintainers with repository write permissions 👍
