### ISSUE TITLE
Requests on items with temporary circulation category do not appear in the validation interface

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2426]
**Describe the bug**

Some requests on items that have a temporary circulation policy do not appear on the request validation interface. If the librarian enters the item barcode, the request is validated.

These requests are received by e-mail.

**To Reproduce**

No reproduced so far.

This problem happens with these item barcodes from CIP Tramelan (RBNJ): `407963`, `730450`

**Expected behavior**

These requests should be displayed on the request validation interface. The logic should be the same than for sending the availability notif

**Context**

* server: <https://bib.rero.ch>
* version: `v1.4.11`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by PascalRepond** [comment]
Seems OK in v1.14.1
