### ISSUE TITLE
API for conversion (MARC > JSON) used by EZP can generate false document references

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2436]
**How it works**

If a MARC document with a reference to another document which is not in RERO ILS, for instance in field `MARC 773$0`, is imported through the API, it is with the wrong reference.

**Improvement suggestion**

RERO ILS should check, at the conversion, if the reference exists in RERO ILS. If it does not, the conversion of field `partOf` (and all other reference fields) generates a `label` sub-field, and not a `$ref` sub-field.

**Comment by PascalRepond** [comment]
Cannot reproduce and not enough info in the issue description, closing.
