### ISSUE TITLE
Loan expiry notices sent only once, even in case of renewals

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2470]
**How it works**

`due_soon` notifications are sent only once. If a user receives a first loan expiry notice, then renews his/her loans, he/she won't receive another expiry notice for the new due date.

**How it should works**

If the due date changes, the expiry notice is sent again (without considering previous expiry notices sent).

**To clarifiy**

Do we want the same behaviour for overdue / reminders notifications?

**Comment by zannkukai** [comment]
@pronguen You're right ;-) It's the case with the PR.
We cancel a notification only if we found a similar notification created AFTER the transaction date.
In case of renewal, the trans_date is updates with the current timestamp ;-)

**Comment by pronguen** [comment]
This issue is reopened: the tests showed that the correction is not working.
