### ISSUE TITLE
Item number displayed on holdings for serial and standard items

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2494]
**Describe the bug**

When an item is masked, it's not displayed in the public interface. However, the number of items is incorrectly displayed (see screenshot).

**To Reproduce**

1. Go to a document with multiple items (in the same holding)
2. Mask one of the item (or issue for a serial)
3. Go to the public interface

**Expected behavior**

1. Remove the display of the number of items for *serial* holdings
2. For standard holdings, the masked items should not be taken into account in the public interface.

**Context**

* server: [ils.test.rero.ch][1] and [ilsdev.test.rero.ch][2]
* version: `v1.6.0`.

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/55576980/139849493-e5a89e54-0a98-4bba-8616-dc9157564452.png)

**Comment by PascalRepond** [comment]
Has been solved by: https://github.com/rero/rero-ils-ui/pull/822
