### ISSUE TITLE
Public view: the selected facets are not kept during the search

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2504]
**Describe the bug**

In the public view, after clicking on the back button in a document detail view, the user loses all the facets he had selected.
Note: the search term is kept.

**To Reproduce**

1. Go to public interface and make a search.
2. Select a facet. Ex: Book.
3. Select a document in the result.
4. Use the back button from the document detail view.

**Expected behavior**

As in the professional interface, the filters/facets should be kept during the search.
The search is reinitiated when the user clicks on the institutional logo.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.6.0` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

**Additional context**

**Comment by ManaDeweerdt** [comment]
Linked to https://github.com/rero/rero-ils/issues/2523

**Comment by pronguen** [comment]
Seems solved in v1.10.0
