### ISSUE TITLE
Renewal possible for a librarian even if the patron is blocked

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2514]
**How it works**

For now, the staff cannot renew a document if the patron is blocked (limit by fees, overdue etc).

**Improvement suggestion**

A librarian can use the override button to renew the item for a blocked patron (limit reached). As for a standard renewal, the overdue preview fees related to the item should become engaged fees.

To be done:
- visually: add a lock icon, make the button enabled, ideally add a tooltip "Renewal blocked: [reason]"
- permission: allow the renewal override, but only from the professional interface

![image](https://user-images.githubusercontent.com/8154915/149793676-a63edbcb-89af-4c4b-a8c8-229dfd0c7583.png)

The button "Renew all" only renew the loans with renewal not blocked.

**Comment by pronguen** [comment]
@ManaDeweerdt Could you precise: is it a permission problem or a fee problem?

**Comment by ManaDeweerdt** [comment]
The staff would like to have the permission to force the renewal in case a patron is blocked.
