### ISSUE TITLE
User account: display the loans of other institutions

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2545]
**How it works**

For now in the professional interface, the librarian logged in in institution A cannot see the loans of institution B on the user account if the user is also member of institution B.

**Improvement suggestion**

A librarian should be able to see (no action) other institution's loans on a user account.

**Comment by pronguen** [comment]
@ManaDeweerdt This has to be discussed. Indeed, RERO ILS is meant to be used by different organisations. The user subscribes to one organisation and might not want to share his/her "sensible" data (borrowed titles, fees, ...) with all organisations. This is the principle of the consortial feature of RERO ILS.

**Comment by ManaDeweerdt** [comment]
Sometimes it is interesting to know that a user has many fees in other institutions, to be aware of the behaviour.
For now, it seems that if the blocking message or note is visible, it fulfills our need.
