### ISSUE TITLE
Dates are not displayed correctly (delay of 1 day) in the fee tab of the patron account

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2550]
**Describe the bug**

Dates are *sometimes* displayed with a delay of 1 day in the tab "Fees" of the patron account (professional interface)

Date problem (see screenshot, case A):
* No fees on Monday as if it was Sunday 
* Fees calculated until one day after checkin
* There might be a day or date shift
* A lot of these examples are referenced in [this file](https://docs.google.com/spreadsheets/d/1rcZy1NGBhwZ-3sagP3Dt-uZKaAhpMjX6JERa-2vUir0/edit#gid=1702820063) (all for RBNJ org)

Date problem (see screenshot, case B)
* Due date is not displayed correctly on patron account (tab "On loan" and "Fees")
    * In the loan JSON data, the endDate is one day before
* This is maybe also the case on patron public account

Related issue: https://github.com/rero/rero-ils/issues/2198
* was deployed on bib.rero.ch on 06.10.21
* the examples were observed after (on 26.10.21)

**To Reproduce**

Unknown, see screenshots.

**Expected behavior**

Dates are calculated/displayed correctly.

**Context**

* server: bib.rero.ch 
* version: `v1.6.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshot, case A**

[Operations logs of this loan](https://bib.rero.ch/api/operation_logs/?q=loan.item.pid:820500%20AND%20loan.patron.pid:186327), patron pid:186327, item pid:820500

![image](https://user-images.githubusercontent.com/8154915/143195432-be17c240-22c5-4cd8-bf0d-8169e28924b4.png)

**Screenshot, case B**

Loan pid:404198 (end date is "2021-10-28T22:00:40.648577+00:00"), patron pid:34118 , item pid:3105966 
![image](https://user-images.githubusercontent.com/8154915/143198461-6443ac49-ed59-4ddc-80b2-2fec6a347a22.png)

**Comment by zannkukai** [comment]
Step exemple URL : https://bib.rero.ch/api/patron_transaction_events/?q=parent.pid:79828
It shows than dates are stored with the right day... this is a timezone display problem

**Comment by zannkukai** [comment]
The end-date problem should already be resolved by closing rero/rero-ils#2198 PR.
This PR has been merged 10/4 but this loan is starting before (9/30).

**Comment by jma** [comment]
With @zannkukai we checked the code: everything is ok since https://github.com/rero/rero-ils/tree/bib-v1.7.0-fix-20211222.
However, we still need to make a mass correction for the step dates for the patron transaction events. This mass correction should modified the data using this approach: https://github.com/rero/rero-ils/blob/c3d4aadbb3a2e716bfafdffc1e3183838c2f6086/rero_ils/modules/loans/api.py#L688.
