### ISSUE TITLE
Improve the Holdings detail view (Issue's section)

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2554]
**How it works**

In the issue section (where we can received the issue), there's a column named "Date of receipt". The dates are not the received date, but the status date.
There missing some informations usefull for serialists.

**Improvement suggestion**

See mockup (I did my best):
1. Rename the "Date of receipt" in "Last action" (corresponds to field `status_date`)
2. Add a column "Expected date" (based on the "The expected date for the next issue"). Even when an issue is received, it's useful to know when it was supposed to arrived (see if there are regular delays in reception).
    * Remove the text "expected at" within this column
3. To gain space, include the status dot in the first column, before numbering
4. Signal the issue with notes (with the same icon than in circulation interface) to help identify them.

![image](https://user-images.githubusercontent.com/8154915/149960209-e9d2ef42-c4a4-4a83-8ec1-ea330072da4b.png)

**Comment by zannkukai** [comment]
@JoelleDosimont It should be great, bu unfortunately, we don't have required space to display all these informations in one line. At this time, we have this design

![image](https://user-images.githubusercontent.com/10031585/149370470-890ebc9d-00c1-4a1b-a772-94bf7620b523.png)

It's impossible to reduce columns width to add a new one with another date.
Maybe we need to rethink usage of table display for this screen and use standard block display (with data on multiple lines).

@pronguen (for PO members) what is you feeling about that ?
