### ISSUE TITLE
Dispute shouldn't block a user

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2573]
**Describe the bug**

For now, a user with a dispute is considered as blocked. He cannot submit a request, nor can loan a book (the override works).
The disputed fees is counted in the limit by fees amount.

**To Reproduce**

1. Find a user with fees. Ex: Katie.
2. Add a dispute.
3. Try to make a checkout or add a request.

**Expected behavior**

A dispute should not block a user. It is used to point out a situation that requires clarification.
The amount of fees disputed, shouldn't be counted as a limit.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.6.1` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

**Additional context**

**Comment by zannkukai** [comment]
Point to discuss : 
* Disputes is a type of transaction event :: To know if a transaction is disputed we need to analyze if some 'dispute' related events exist. Should be possible to remove "dispute" event ? If yes, does it involved to remove the event (if yes we loos information that this transaction was disputed).
* If some transactions are disputed, Is this information must be specify into patron circulation UI panel ?
* At this time, we can't specify (using UI) the amount of a dispute. Is it necessary ?
