### ISSUE TITLE
Two screens: "no results" and "no records in this section"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2576]
**How it works**

In some cases like for the management of ILL requests, we use facets that stay active even if we change the page and come back. This is good. But with the update of the resources, this can lead to a message "There are no records in this section." that the user does not understand (see screenshot).

In this screenshot, the user just finished to treat the pending ILL requests and doesn't know how to list all ILL requests:
![image](https://user-images.githubusercontent.com/8154915/144384408-81fea759-dc3b-41c6-9ac5-52bdc8fce3ec.png)

In this different screenshot, there are no results:
![image](https://user-images.githubusercontent.com/8154915/144393085-8f44f0cd-21be-43be-b769-772a4b2d053e.png)

Hypothesis: this might be linked to this problem: if we directly change the facet parameter in the URL, it is sometimes lost.

**Improvement suggestion**

* clarify when to display "no records" or "no results"
    * ideally, display "no records" if really they are no records in the authorisations scope of the user (which is not the case in screenshot 1)
    * or find another solution, for instance: another message than "no records", or an expand button (as in https://github.com/rero/rero-ils/issues/975)

**Comment by ManaDeweerdt** [comment]
Linked to https://github.com/rero/rero-ils/issues/2633 ?
