### ISSUE TITLE
Found Multiple Vulnerability on Application

### ISSUE THREAD

**Issue by noobpk** [rero/rero-ils#2592]
I reported these vulnerabilities on Huntr a few months ago, but it seems that your team still doesn't pay attention to security, so they did not confirm these vulnerabilities.

I created this Issue hoping you can visit Huntr and confirm these vulnerabilities. We are all trying to contribute to the opensource community. ^^!!

**Describe the bug**
Open Redirect : [https://huntr.dev/bounties/9ef8c74f-41f4-4f04-ba94-d7c507227c9c/](https://huntr.dev/bounties/9ef8c74f-41f4-4f04-ba94-d7c507227c9c/)
Stored XSS : [https://huntr.dev/bounties/b032ff4d-baff-4fba-b59b-6b2eeb5f0838/](https://huntr.dev/bounties/b032ff4d-baff-4fba-b59b-6b2eeb5f0838/)

**To Reproduce**

For security reasons, I do not describe the `Steps to reproduce` section here. You can access the report on the hunter and see the details of the vulnerability.

Thanks

**Comment by PascalRepond** [comment]
For security issues, please contact security@rero.ch
