### ISSUE TITLE
Translation: Some strings not extracted

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2601]
**Describe the bug**

Some strings are not extracted in the acquisition tab of the circulation interface. It is translated in Weblate.
Ex: https://ilsdev.test.rero.ch/professional/circulation/patron/2050124312/fees

**To Reproduce**

1. Find a user and look at the fees tab.
2. See the menu on the left and the content.
3. See also the 'Note Subscription for 'Standard' from 2021-12-09 to 2022-12-09.'

**Expected behavior**

All the strings must be translated.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.7.0` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/12396034/146377774-f281cfd1-61cf-4334-8585-204f5661b658.png)

![image](https://user-images.githubusercontent.com/12396034/146378495-dec6ab12-5621-471e-b9f2-033584ae3b65.png)

**Comment by zannkukai** [comment]
@ManaDeweerdt  The note content is generated by a scheduled CLI script. This script is completely agnostic about the language to use => the note content is generated in English (by default). 
If you add any kind of notes on a ressource, the note content isn't translate if you switch language. Just the same here
