### ISSUE TITLE
The facet "status" should work within the organisation view

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2603]
**Describe the bug**

The facet status, in an organisation view, is calculated according to the items of all organisations.

**To Reproduce**

1. Create a document
2. Add an item in org1 and org2
3. Checkout the item of org1
4. Go in the public view of org1 and look for this item
5. See the status facet: it also displays the status "available"

**Expected behavior**

* The "Status" facet is calculated only according to the items of the organisation view
* [nice to have] If an organisation/library/location is selected in the facets, the status facets is calculated only according to it

**Context**

* server: bib.rero.ch
* version: `v1.7.0`

**Screenshots**

In this example, all items are on loan but the facet still displays the "available" status, because some items in another organisation are available.
![image](https://user-images.githubusercontent.com/8154915/146421043-31f7f9ed-b70b-4d7d-808f-0caad5288a63.png)

**Comment by ManaDeweerdt** [comment]
Same as https://github.com/rero/rero-ils/issues/2278 ?

**Comment by pronguen** [comment]
> Same as #2278 ?

@ManaDeweerdt The two issues are distinct, but related. #2603 is really about the "Status" facet. #2278 is more about the availability button (regardless of the facets).

**Comment by PascalRepond** [comment]
The facet status is calculated correctly through the field "document_status", it can be unintuitive that documents shown as "available" display no available item. But technically, the status is indexed once on the document according to all organisations. It would be overly complex and very heavy on the server to index a different field document.status for each organization.

Closing as wontfix.
