### ISSUE TITLE
Rename the field "enumerationAndChronology" for online holdings

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2605]
**Describe the bug**

For online holdings, the field "enumerationAndChronology" is displayed "Unit" (as for items).

**To Reproduce**

1. Go to https://ils.bibtest.uclouvain.be/
2. Filter to get the databases, and choose one to see the details
3. See error

**Expected behavior**

As it's on the holdings level, the field should be displayed "Collection".
**Context**

* server: [ils.bibtest.uclouvain.be][1]
* version: `v1.6.0` 

[1]: https://ils.bibtest.uclouvain.be

**Screenshots**

![image](https://user-images.githubusercontent.com/55576980/146527599-ecabe70d-4c04-410b-b7e6-459aba3b76e1.png)

**Comment by PascalRepond** [comment]
Linked to #1769 and #2606
