### ISSUE TITLE
Account number: the systems says it is already taken, but it is not

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2618]
**Describe the bug**

The [following account](https://ilsdev-2.test.bib.ucl.ac.be/professional/records/acq_accounts/detail/69) (log in library: Brig) cannot have the account number "GB-1". The systems says: *The number is already taken.* But it is not taken.

![image](https://user-images.githubusercontent.com/8154915/147078156-e1922629-0e79-4425-b8dd-ad5870f99145.png)

This is due to the fact that this field is indexed as text and not as keyword.

**To Reproduce**

See example above.
Impossible to reproduce with a new example.

**Expected behavior**

* It is possible to save the account if the number is unique within the library
    * i.e. index the field as keyword

**Context**

* server: ilsdev-2.test.bib.ucl.ac.be
* version: acquisition version (not released)

**Comment by zannkukai** [comment]
This bug should be already resolved with acquisition module integrate on `staging` (v1.8.0)
The problem was that `name` and `reference` fields was indexed as text (as ES mapping). 
To solve this problem, we create a raw mapping (index as ES keyword) and the uniqueness is checked on this field.

**Comment by zannkukai** [comment]
I confirm it's OK with `v1.8.0` (tested)
