### ISSUE TITLE
Autocomplete doesn't work above 10 characters per word

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2619]
**Describe the bug**

Some searches aren't displayed in the auctocomplete, for the collectivities. See screenshots below.

**To Reproduce**

1. In the global search try to type "international"
2. Until "internatio" : autocomplete works fine
3. After "internation" : autocomplete does not display any results (even if there are results)
Other word with the same effect : "association"

**Expected behavior**

Autocomplete should work on the entire word, if there are relevant results that contain the searched word.

**Context**

* server: [ils.test.rero.ch][1] and [ilsdev.test.rero.ch][2]?
* version: `v1.7.0`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/55576980/147081612-22fd7680-f2f6-496b-8e85-7714c876d58e.png)

**Comment by PascalRepond** [comment]
It seems to be that the search stops autocompleting if more than 10 characters are typed, is it a performance feature? (@jma, @zannkuai)
