### ISSUE TITLE
Extend MARC21 export in SRU

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2621]
**How it works**

Currently, the MARC21 exported via SRU does not contain all fields. It is a light export.

**Improvement suggestion**

More fields should be part of this export. The most important are (by order of priority):
* `subjects` (done by: https://github.com/rero/rero-ils/pull/3365)
* `originalLangage`
* `originalTitle`
* `tableOfContents`
* `contentMediaCarrier`
* `adminMetadata.source`
* `issuance`
* `partOf`
* `seriesStatement`

Specifications: https://ncloud.rero.ch/s/oM98pCMzEfDHFLZ

**Comment by Jojomotte** [comment]
Erara would also need these fields to work with SRU interface :
- title
- From the MEF ressource the field authorized_access_point in relation with agents in document ressource
- provisionActivity
- extent 
- dimensions
- illustrativeContent
- bookFormat
- dimensions
- note
- language
- electronicLocator
- seriesStatement
- From the item ressource the field call_number
- From the item ressource the field library

**Comment by PascalRepond** [comment]
These fields have now been treated.
