### ISSUE TITLE
circulation: unable to do a checkout in prof. interface

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#2626]
**Describe the bug**

Since the PR https://github.com/rero/rero-ils-ui/pull/776 has been merged in v1.8 RC, a librarian is unable 
to do a checkout in the professional interface. 
When you scan a patron barcode, the interface doesn't react and doesn't display patron profile.

**To Reproduce**

1. Go to ilsdev.test.rero.ch and login with Jean (librarian)
2. Go to prof. interface and click on Checkout/checkin
3. Scan the patron barcode 2050124312 (Broglio Giulia)
4. Nothing happens

**Expected behavior**

When you scan a patron barcode, the interface should display the patron profile.

**Context**

* server: ilsdev.test.rero.ch
* version: v1.8 RC

**Comment by pronguen** [comment]
The problem is not solved. I opened another issue: https://github.com/rero/rero-ils/issues/2735
