### ISSUE TITLE
inventory list: librarian can see items from all organizations

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#2627]
**Describe the bug**

In the v1.8 RC installed on ilsdev, a librarian who uses the inventory list can see all items, from all organisations.
Previously, the system used a least a filter on the organization of the librarian.

**To Reproduce**

1. Go to ilsdev and login as Jean (librarian of Aoste)
2. Go to professional view and click on Inventory list
3. By default, the system filters on my library (OK) but when I unselect it, the facet "libraries" displays all libraries, from all organizations. 

**Expected behavior**

The system should always apply a filter to my organization.

**Context**

* server: ilsdev.test.rero.ch
* version: v1.8 RC

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

**Additional context**

**Comment by ManaDeweerdt** [comment]
Same for the course/exhibition. On the professional view we can see libraries from other organisations in the facet.
In this case, the library field is blank.
Ex:
![image](https://user-images.githubusercontent.com/12396034/150987617-eb189a8e-8ef7-4752-ad11-1413081208cd.png)

**Comment by PascalRepond** [comment]
Is now fixed in `v1.9.0`. If I unselect the facet, I can see only libraries in my organization. Re-open if this is not satisfactory.
