### ISSUE TITLE
Convert steps dates in iso format for patron overdue preview

### ISSUE THREAD

**Issue by jma** [rero/rero-ils#2629]
Add an  iso transformation here:

https://github.com/rero/rero-ils/blob/38922a1eed91c16e85d4c0ec2ac8efd394ba6074/rero_ils/modules/patrons/views.py#L99

**Comment by zannkukai** [comment]
get code from : https://github.com/rero/rero-ils/blob/c3d4aadbb3a2e716bfafdffc1e3183838c2f6086/rero_ils/modules/loans/api_views.py#L59
