### ISSUE TITLE
Due date in a check-out does not consider closed days introduced in exceptions

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#263]
If I do a check-out, the due date is calculated without considering the exception days (closed days).

**Comment by BadrAly** [comment]
unittest to demonstrate this issue is created in:
`tests/api/test_libraries_rest.py:: test_library_exceptions` lines `201`,` 202`

**Comment by BadrAly** [comment]
Problem was that if you have a day configured as `closed` in the library `opening hours` section. Then the same day is added as open 'exception` day for few hours. system will consider it a closed day.
