### ISSUE TITLE
MEF : display field 686 IDREF 

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2635]
**How it works**

• IDREF field 686 (classification) was added by ABES in 2021 in IDREF form.
It is used to identify corpus of entities. In Switzerland, t is used by patrimonial libraries (Neuchâtel and Valais (codes NEU_AUT and VS_AUT in 686 $a) to identify their local authors.
•This field is difficult to search in IDREF et is not displayed in IDREF records on https://www.idref.fr/ (only visible in edition mode).

**Improvement suggestion**

Display content of IDREF 686 $a $2 in MEF as follows : 
example 686 $a NEU_AUT $2 RERO
display in MEF :
  "classification": [
      {
        "classificationPortion": "NEU_AUT",
        "type": "RERO"
 }
    ]

686 can be present in Persons, organisations and family records

**Comment by PascalRepond** [comment]
This field is not present in MEF as it is not exported by IdRef OAI set. Won't fix.
