### ISSUE TITLE
Incremental overdue fees should always be calculated according to the checkout library's opening days

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2640]
**Describe the bug**

Currently, the incremental overdue fees are calculated according to the opening days. If a loan is renewed, the fees will base on the opening days of the transaction library of the renewal.

In case of a trilogy checked out in library A where
- 2 items are renewed online by the patron (operator is: system)
    - fees are calculated based on library A
- 1 item is renewed by a librarian in library B
    - fees are calculated based on library B

By default, the "transaction library" of a renewal made by the patron (online) is the item library.

**To Reproduce**

See above

**Expected behavior**

Fees always base on the opening days of the checkout library.

* the fees always take as base the opening days of checkout library, not of the renewal library
* (nice to have) the "transaction library" of a renewal made by the patron (online) is the checkout library - and not the item owning library.

**Context**

* server: bib.rero.ch
* version: `v1.7.0`

**Comment by zannkukai** [comment]
Currently, the `item.location.pid` is used for transaction location for "extend by patron" circulation operation. Is it the right way ? 3 solutions possibles :
* keep this behavior
* use the previous transaction location (mainly the checkout transaction location)
* create a fictive location for this use case (effort ++)
