### ISSUE TITLE
Statistics: better labels with translations

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2675]
**How it works**

Currently, the indicators of the statistics module have labels that are difficult to understand.

**Improvement suggestion**

* indicators are renamed
    * `number_of_loans_by_transaction_library` > `checkouts_for_transaction_library`
    * `number_of_loans_for_items_in_library` > `checkouts_for_owning_library`
    * `number_of_extended_items` > `renewals`
    * `number_of_validated_requests` > `validated_requests`
    * `number_of_patrons_by_postal_code` > `active_patrons_by_postal_code`
    * `number_of_new_patrons_by_postal_code` > `new_active_patrons_by_postal_code`
    * `number_of_items_by_document_type_and_subtype` > `items_by_document_type_and_subtype`
    * `number_of_new_items` > `new_items`
    * `number_of_new_items_by_location` > `new_items_by_location`
    * `number_of_new_documents` > `new_documents`
* Columns are reordered in the sequence above
* All labels have a human readable and translated form:
    * `new_items_by_location` > *New items by location*
    * `validated_requests` > *Validated requests*
    * etc.

**Comment by vgranata** [comment]
@pronguen with the PR https://github.com/rero/rero-ils/pull/2661 I added a new query to get a csv file with loans (checkin/checkout) by library and item location.
Would the label "loans_by_item_location" be ok for this query ? Thanks

**Comment by pronguen** [comment]
> @pronguen with the PR #2661 I added a new query to get a csv file with loans (checkin/checkout) by library and item location. Would the label "loans_by_item_location" be ok for this query ? Thanks

I would write `loans_of_transaction_library_by_item_location` (*Loans of the transaction library, by item location*). It is a bit long, but I think we will have in the future the inverse (*Loans of the item library, by transaction library*).

**Comment by vgranata** [comment]
- All labels have a human readable and translated form: ...
The labels need to be readable or also translated according to the selected language ?

**Comment by pronguen** [comment]
> * All labels have a human readable and translated form: ...
>       The labels need to be just readable or also translated according to the selected language ?

Also translated, ideally!

**Comment by pronguen** [comment]
Solved by https://github.com/rero/rero-ils/pull/2661

**Comment by pronguen** [comment]
@vgranata I reopen it after tests. The labels are not translated in de/fr/it according to the interface.
