### ISSUE TITLE
Use better `transaction_location_pid` for self renewal

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#2680]
**Describe the issue**

Currently, when a patron renew a loan using the public interface, the `transaction_location_pid` used is the `item.shelf_location.pid`. It could be more logic to use the last `transaction_location_pid` (used for the previous checkout or previous renewal) OR a generic `self_renewal_location` for this operation

https://github.com/rero/rero-ils-ui/blob/a01372c7f131fef7ad1e77dbfc8c615594a90a8b/projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.ts#L80-L85

**Comment by PascalRepond** [comment]
Work has been done with the renewal logic since, is this still relevant?
