### ISSUE TITLE
Calculation of fees based on the library of the renewal or checkin, instead of the library of the checkout

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2683]
**Describe the bug**

In most of the cases, fees are calculated correctly. In some cases though, they are counted on closed days.

Hypothesis to verify: maybe the fees takes as basis the checkin library opening hours and exception days.

**To Reproduce**

Unknown, see hypothesis above

**Expected behavior**

Calculation of overdue incremental fees always takes as basis the checkout library opening hours and exception days.

**Context**

* server: bib.rero.ch
* version: `v1.8.0`

**Example 1**

* Loan pid:269879
* Applied cipo is pid:22
* Item library pid:30 (La Chaux-de-Fonds)
* Checkout library pid:30 (La Chaux-de-Fonds)
* After last renewal, loan due date was 23.12.21
* La Chaux-de-Fonds was closed on 24-26.12
* Grace period (4 days) was applied on 27-30.12
* La Chaux-de-Fonds was closed on 31.12-03.01
* Fees started on 03.01 instead of 04.01

Other examples of this error exist in the same user account (fees of CHF 4.-). All are item of La Chaux-de-Fonds checked out in La Chaux-de-Fonds, but checked in in Neuchâtel. Maybe the fees takes as basis the checkin library opening hours and exception days. Indeed, Neuchatel was open on 03.01.

![image](https://user-images.githubusercontent.com/8154915/152845923-e4e60b62-ec0c-4a6e-8ba4-53464f9b7469.png)

**Comment by zannkukai** [comment]
@pronguen. Your hypothesis is correct. At this time, all fees are calculated based on "transaction_location_pid". So in this case, this is the `library/39` that was used to build the fee. This library is open every day except sunday. So the fee steps build seems correct.

With the rero/rero-ils#2678 PR, the library used to build fee steps will be the library related to "checkout_location_pid". So in this case, `library/30` (and with calendar of this library)

**Comment by pronguen** [comment]
> Your hypothesis is correct. At this time, all fees are calculated based on "transaction_location_pid"

@zannkukai So if the item (belonging to library A) was checked out at library A, then renewed **from** library B (by a professional), then the overdue fees will also base on library B?

Case (fees have been added after the second renewal):
![image](https://user-images.githubusercontent.com/8154915/153001379-fb9ce1f9-2243-4d60-8ebf-c4416a912caf.png)

**Comment by zannkukai** [comment]
> So if the item (belonging to library A) was checked out at library A, then renewed **from** library B (by a professional), then the overdue fees will also base on library B?

@pronguen At this time I think you're correct. With the PR, fees will always be calculated based on "checkout_library" despite if a librarian from libraryB make a "renew" operation.
