### ISSUE TITLE
Detail of fees history sometimes not displayed

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2684]
**Describe the bug**

The detail of the fee history (so called "patron transaction events") sometimes is not displayed in the professional patron account. See example.

**To Reproduce**

See example.

**Expected behavior**

Is displayed

**Context**

* server: bib.rero.ch
* version: `v1.8.0`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Example**

Below, the second case has no history displayed. (patron pid:30222 / item pid:2806072)
![image](https://user-images.githubusercontent.com/8154915/152847989-23b6bfe8-ef5c-4803-8b65-ea65adf8dbe6.png)

Other example is: patron pid:39602 / item pid:1540537

**Comment by zannkukai** [comment]
The `PatronTransaction` could be found here : https://bib.rero.ch/api/patron_transactions/?q=patron.pid:30222%20AND%20item.pid:2806072 (pid:138513) [for ORG:3 - RBNJ]

But no event seems linked to this transactions... (https://bib.rero.ch/api/patron_transaction_events/?q=parent.pid:138513)

**Comment by pronguen** [comment]
@BadrAly Could you investigate this problem? It might be linked to the deletion of the fees that was performed on 03.01.2022

**Comment by zannkukai** [comment]
According ES indexed data, this transaction seems to be created the 03.**02**.2022
```json
{
"created": "2022-02-03T13:37:11.866017+00:00",
"id": "138513",
"links": {
  "self": "https://bib.rero.ch/api/patron_transactions/138513"
},
"metadata": {
  "$schema": "https://bib.rero.ch/schemas/patron_transactions/patron_transaction-v0.0.1.json",
  "creation_date": "2022-02-03T13:37:11.844076+00:00",
  "document": {
    "pid": "1648755",
    "type": "documents"
  },
  "item": {
    "pid": "2806072",
    "type": "items"
  },
  "library": {
    "pid": "39",
    "type": "libraries"
  },
  "loan": {
    "pid": "651641",
    "type": "loanid"
  },
  "note": "incremental overdue fees",
  "organisation": {
    "pid": "3",
    "type": "org"
  },
  "patron": {
    "pid": "30222",
    "type": "ptrn"
  },
  "pid": "138513",
  "status": "open",
  "total_amount": 4.6,
  "type": "overdue"
},
"updated": "2022-02-03T13:37:11.866024+00:00"
}
```

**Comment by pronguen** [comment]
Grooming:
* is there a link with mass correction of fees for RBNJ (03.01.22)?
* is there a link with the bug of the fee multiple of 0.01?
* check Sentry
