### ISSUE TITLE
Librarians should recieve a notification when an item arrives at desk

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2695]
**Describe the bug**

For now, the `booking` notification is sent after a checkin action, when there is a pending loan. This does not completely meet the needs because:
* the request expiration date cannot always be set in the notification (if the item goes in transit)
* some libraries want to print a notification at the moment of the request validation rather than at the request creation

**Expected behavior**

1. Create a notification `at_desk`
    * it is sent when a loan arrives "ITEM_AT_DESK" (same condition that triggers the `availability` notification, with an eventual delay configured)
2. Add a new template for this notification (see below)
3. Adapt the library notification settings to add this notification type. As for availability, it should contain the "delay" field.

Difference with the `availability` notification
* it is sent to the transaction library, not to the patron
* the template is different (very similar to `booking` notification, but completed with the request expiration)

[TEMPLATE: at_desk.odt](https://github.com/rero/rero-ils/files/8261717/at_desk.odt)
[OVERVIEW OF NOTIFICATION SPEC: spec_impressions.odt](https://github.com/rero/rero-ils/files/8261718/spec_impressions.odt)

**Comment by PascalRepond** [comment]
To me, this is not a bug. By definition a transit or booking notification shouldn't happen on request validation. See specs here: https://bib.rero.ch/help/circulation/#notifications-de-circulation
I think this is also what causes misunderstandings in #2707

**Comment by pronguen** [comment]
This issue has been re-written according to a discussion in the PO group.
