### ISSUE TITLE
Add some fields to the Inventory list

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2704]
**How it works**

In the inventory list, some fields are missing to help librarians in the collection management.

**Improvement suggestion**

Please add the following fields :  
From the document records 
- Identifiers : ISBN and ISSN
- Series statement : _text (so we can see all the parts and numbering)
- Provision Activity : Agent (in the Statement)
- Provision Activity : startDate and endDate
- Edition statement : _text
- Masked : Yes/No
- Local fields of the organisation

From the item records and loans
- Creation date of the item
- Temporary circulation category : expiry date
- All the notes type (notes.type:"acquisition_note" ; "binding_note" ; "condition_note" ; "patrimonial_note" ; "provenance_note"). [in addition to the one that are currently in the inventory]
- Masked : Yes/No
- PAC code
- Number of renewals
- Local fields

Check the field called "created" in the current CSV export
- if it is the creation of the item, put the field in the beginning of the columns
- if it is another creation date, rename the field

See current bug at exporting loan count: https://github.com/rero/rero-ils/issues/2793

Nice to have : Be able to choose the fields we need when exporting

**Comment by pronguen** [comment]
Linked to https://github.com/rero/rero-ils/issues/2793

**Comment by pronguen** [comment]
@JoelleDosimont It seems that the line break management is a problem of Excel only. Indeed, it is working well when using LibreOffice Calc, OpenRefine or a simple text editor. See also: https://stackoverflow.com/questions/2668678/importing-csv-with-line-breaks-in-excel-2007

**Comment by JoelleDosimont** [comment]
> @JoelleDosimont It seems that the line break management is a problem of Excel only. Indeed, it is working well when using LibreOffice Calc, OpenRefine or a simple text editor. See also: https://stackoverflow.com/questions/2668678/importing-csv-with-line-breaks-in-excel-2007

Yes, you're right. I deleted that part of the issue. Thanks for the advice.
