### ISSUE TITLE
Notification: add the request expiration date to the templates `request` and `booking`

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2707]
**How it works**

For now, the booking and request notifications don't mention the expiration date of the request.
![image](https://user-images.githubusercontent.com/12396034/154305353-2edb205e-755d-4850-8c9e-d22c1cfc9d14.png)

**Improvement suggestion**

Add the expiration date (field `request_expire_date`) below the username in the template. Label: "Request expiration"
* if the circulation policy does not define any expiration date: display nothing

**Comment by pronguen** [comment]
After discussion within the PO group, this issue won't be fixed, as it is not relevant. This one (https://github.com/rero/rero-ils/issues/2695) should address this problem.
