### ISSUE TITLE
Search items by current number of pending requests

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#2708]
**Improvement suggestion**

As a librarian, I want to be able to search the most requested items for my library, so that I can manage my collections and periodically buy more copies of items that have many pending requests.

**Acceptance criteria**

- In the inventory list view: 
    - I can sort items by `current_pending_requests` (descending), so that I see most currently requested items at the top.
    - I can use an expert search to target for example: items with more than 5 current pending requests. 
    - The `current_pending_requests` is displayed in the listed items when it is not zero. 
    - The `current_pending_requests` is exported in the CSV of the inventory list
    - Nice-to-have: A range facet allows me to filter by number of pending requests.

**Use case explanation**

* In order to satisfy my patrons and avoid long waiting times for popular books, my library policy states that I need to buy one more copy of an item if it has more than X pending requests.
* As an acquisitions librarian, I need to stay on top of these most requested items. 
* Every week, I am able to view a list of the items that *currently* (at the time of my search) possess the highest number of *pending requests* so that I can buy more copies. I can then dispatch the pending requests to shorten the waiting time of my patrons.

**Comment by zannkukai** [comment]
Is it really necessary to index this data into item ? 
If we need to know how many pending_request are placed on an item, an aggregation on `loan` index could be enough. (This solution works only for curent timestamp - not possible to get this info 
for past period because loan state changed)

How this should be implemented into UI ?
Does we need to implement an alert on home page ? Or only on request page ?

**Comment by PascalRepond** [comment]
@zannkukai If the performance is OK, this solution could work. For the UI, I thought the simplest would be to add a facet "number of requests" in the inventory list so that a librarian can filter the items that have "more than X" requests. Alerts would be nice to have but not in the scope of this issue.

**Comment by ManaDeweerdt** [comment]
After discussion at UCLouvain, we thought that the 'loans view' is a better place for this information as we already can retrieve the 'pending' loans. 
What do you think?
