### ISSUE TITLE
Deletion of a location is not blocked if holdings are attached to it

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2729]
**Describe the bug**

Currently when deleting a location
* deletion is blocked if an item is attached to it
* deletion is NOT blocked if a holdings is attached to it

**To Reproduce**

1. Create a location X
2. Create a serial holdings Y attached to X
3. Delete location X
4. See that it is possible and the holdings is in error

**Expected behavior**

It is not possible to delete a location that has attached holdings.

**Context**

* server: bib.rero.ch
* version: `v1.8.0`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by PascalRepond** [comment]
Maybe to be fixed with https://github.com/rero/rero-ils/issues/2813 (part 2)
