### ISSUE TITLE
Display 20 loans instead of 10 loans in the public patron account

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2750]
### How it works

For performance reasons, in the public patron account, only the 10 first loans are displayed. Various patrons contacted directly RERO+ to ask for displaying all the loans. They don't understand why there is a paging.

### Improvement suggestion

* Display if possible all the loans.
* If the performance does not allow it, display at least 20 loans (and then 20 by 20 for the hidden ones)

**Comment by pronguen** [comment]
@Garfield-fr Do you think performance allow to load the loans 20 by 20, or even all together? This is the case in the professional interface.

**Comment by Garfield-fr** [comment]
> @Garfield-fr Do you think performance allow to load the loans 20 by 20, or even all together? This is the case in the professional interface.

Yes I think 20 items is reasonable.

**Comment by Garfield-fr** [comment]
> @Garfield-fr Do you think performance allow to load the loans 20 by 20, or even all together? This is the case in the professional interface.

It is not possible to display all loans on the account due to charge on the API. However, we can go up to 20 loans to test.
