### ISSUE TITLE
Multiple loans for the same item and patron

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#2791]
This error message appears, not very often, in Sentry. 
`400 MultipleLoansOnItemError: Multiple active loans on item with PID 'item:________'`

Hypothesis 1
* RERO ILS sometimes is not able to re-index the item according to the realised circulation transaction.
    * 2 Consequences:
      * The librarian see a bug (the item does not go in transit, a flash message is not displayed, etc.)  
      * This might enable to create another loan for the same patron/item

Hypothesis 2
* RERO ILS creates two identical loans when some checkouts are made. The two loans are created in the same second. Later on, when the patron returns the item, REROILS attempts to checkin the first loan successfully and reports that a second ACTIVE loan is found on the system. 
      * For the librarian, the quick fix is to check-in the item another time, or manually delete the extra loan.
      * Ideally, the front-end needs to block the check-out input form to prevent a second checkout. The input form is disabled while loading the transaction and until receiving the response.

### Expected behavior:
One loan is created for each checkout. The item is always reindexed after the corresponding circulation transaction.

### Steps to Reproduce

* Open a patron account with at least 120 loans
* Before the front-end has loaded all the 120 loans, already enter an item barcode (to be checked out)
* Try to enter this item barcode various times as quick as possible
* By chance, you will be able to reproduce the case

### See also

https://github.com/rero/rero-ils/issues/1864

### Server

* [X] production: [bib.rero.ch](https://bib.rero.ch) 

### Version
`v1.9.0`, `v1.12.0`, `v1.13.0`

### Examples

**Example 1**
This example is based on patron.pid:36102 and item.pid:2916843 on bib.rero.ch.
![image](https://user-images.githubusercontent.com/8154915/190449816-bfbe18d8-1262-4754-97a7-c23c396b35a5.png)

**Example 2**
Observed on `v1.13.0` on 27.09.2022
Based on item_pid:3237989 AND patron_pid:29951 on bib.rero.ch.
Scenario explained by the librarian:
1. The item belongs to La Chaux-de-Fonds, was requested for pickup in Neuchâtel (loan A)
2. La Chaux-de-Fonds did a checkin in order to validate the request (loan A)
   * result: the item didn't go "in transit" (analysis: probably the item was not updated/reindexed)
3. La Chaux-de-Fonds deleted the first request and created another one
![image](https://user-images.githubusercontent.com/8154915/192743016-c5fc06d6-4234-4228-9819-9379dde4dd8d.png)

**Comment by PascalRepond** [comment]
This seems to not happen anymore
