### ISSUE TITLE
Trying to display a draft record in the public ui raises an error

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#2792]
### How it works

Sentry raises an internal server error if someone tries to load a record with `_draft:true` in the public UI because the document doesn't return a `type`. See Sentry error ID `RERO-ILS-163`.

### Improvement suggestion

It is very unlikely that someone tries to load a draft record in the public UI. This error is thus of very low priority.

**Comment by ManaDeweerdt** [comment]
Duplicate of https://github.com/rero/rero-ils/issues/2623 ?
