### ISSUE TITLE
renewal counts

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#28]
The renewal count is incremented each time the action "renew" is selected. Even when the item new due date is not changed.

**Comment by iGormilhit** [comment]
As discussed, the renewal action should not be available after the first renewal, at least until the next day. It doesn't make sense.

@pronguen: Could you confirm?

**Comment by pronguen** [comment]
Yes, I confirm, more or less. The renewal action should be available only if the new anticipated due date is not equal to the current due date.

**Comment by iGormilhit** [comment]
See #231
