### ISSUE TITLE
Stemming should not be applied for an exact phrase search

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2834]
### How it works
For a an exact phrase search (use of quotes ""), RERO ILS applies the tokenisation and stemming mechanisms to each word. In the result, the sequence of each word must correspond to that of the query.

### Improvement suggestion
Stemming should not be applied for an exact phrase search, like in Swisscovery for instance. This will improve the precision.

**Comment by PascalRepond** [comment]
As discussed, I think this should be a `wontfix`. It is not compatible with ElasticSearch behavior and I cannot think of a use case where this might be needed.
