### ISSUE TITLE
E-mail validation must be stricter

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2838]
### How it works
It is possible to enter wrong formatted e-mails into RERO ILS for users/patrons.

### Improvement suggestion

In the user editor, professional view (user e-mail + patron additional communication e-mail) + in the public view (user e-mail), the validation should be stricter:
- no spaces in the beginning or the end (or they are automatically trimmed)
- no spaces in the e-mail
- no dot at the end, or other punctuation character
- only one `@`
- eventually the system checks if the domain name exists

**Comment by PascalRepond** [comment]
Linked to https://github.com/rero/rero-ils/issues/2765
