### ISSUE TITLE
A system librarian cannot access the statistics if he/she has not also the role "librarian"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2862]
### How it works

Since v1.10.0, a system librarian cannot access the statistics if he/she has not also the role "librarian".

### Improvement suggestion

A librarian accesses his/her library statistics, if she/he is not system librarian.
A system librarian accesses the organisation's statistics, whatever his/her other roles are.

**Comment by jma** [comment]
Releated sentry errors: RERO-ILS-1M8, RERO-ILS-1MM, etc.

**Comment by PascalRepond** [comment]
As of v1.11.0, this is fixed.
