### ISSUE TITLE
Check-in and checkout notes should be displayed within the concerned line

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2865]
### How it works
Currently, in the circulation interface, when performing a check-in or check-out, the check-in and checkout notes of the item are displayed on top right of the screen.

Problem: when a librarian scans a lot of items
* he/she doesn't know anymore which flash message corresponds to which item.
* the notes disappears after a time

### Improvement suggestion

Check-in and checkout notes of the item are displayed within the concerned line. Content is abbreviated if necessary, and if possible displayed in line to save vertical space (even in case of line breaks)
* in view `/professional/circulation/checkout`, only check-in notes are displayed
* in view `/professional/circulation/patron/2050124311/loan`, only check-out notes are displayed

Linked issue: #2864 

![image](https://user-images.githubusercontent.com/8154915/165785956-0eb86200-3814-49bd-bf0f-df9613158366.png)

**Comment by PascalRepond** [comment]
The notes are already displayed in the list (unexpanded), now the librarian can expand all lines and see which items have notes. This issue becomes irrelevant, closing.
