### ISSUE TITLE
Allow deletion of items with linked fees

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#2869]
### How it works
An item that is linked to a loan with fees cannot be deleted. It should be possible.

### Improvement suggestion

* It is possible to delete the item even if it still has fees (as long as the linked loan is closed)
    * A non blocking warning is displayed when deleting such an item
* Implement a mean to keep trace, in the fee, of the concerned document, if this latter has been deleted
* When the item has been deleted, the fee is still displayed in the pro and public patron profile, but 
without the link to the item.

### Context

This is to fix the incorrect implementation of https://github.com/rero/rero-ils/issues/2102

This enhancement concerns points 2+3 of a series of 3 enhancements:

1. Do not anonymise operation logs linked to an item with fees (priority 1) > described in https://github.com/rero/rero-ils/issues/3121
1. Implement a mean to keep trace, in the fee, of the concerned document, if this latter has been deleted (priority 2)
1. Enable deletion of an item with fees (priority 3)

### TO BE CLARIFIED AT GROOMING:
- What solution to keep a trace of the document linked to the fees (not even the item)?
    - Create a dedicated operation log?
    - Index in the fees the document title (only at the moment of the fee creation maybe)?

**Comment by pronguen** [comment]
Three actions might be necessary to completely solve this problem:
1. Enable deletion of an item with fees
2. Do not anonymise operation logs linked to an item with fees
3. Implement a mean to keep trace, in the fee, of the concerned document, if this latter has been deleted
