### ISSUE TITLE
Convert 4 last fields: abbreviated title, scale (maps), work access point, temporal coverage (RERO+ specific)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2878]
The 4 fields are converted and integrated, but only for the documents that exist in RERO ILS.

If the concerned fields already exists in RERO ILS, don't erase it but create a log to compare the data.

See [conversion specifications](https://docs.google.com/spreadsheets/d/1DCjCcMMylVsSoKIjsjx6ykWnGr9r_wPZ0fLRi3rlVpQ)

**Comment by rerowep** [comment]
`work access point` is already implemented.
