### ISSUE TITLE
Order template: add the subfield 'qualification' next the ISBN

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2880]
### How it works

For now, in the order sent to the vendor we have the ISBN field but additional information like 'qualification' could be useful to specify fo example the binding we want.

### Improvement suggestion

Add the subfield 'qualification' next the ISBN in the order template.

**Comment by PascalRepond** [comment]
Should have been closed by https://github.com/rero/rero-ils/pull/2928
