### ISSUE TITLE
Document's editor : performance problem when adding/deleting a field

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2882]
### Bug description:

In some records, the addition of fields takes too many seconds. It's the same when you delete them. It happens when adding a field that already exist in the record (duplicate of an existing field).
Ex. : try to add import the ISBN 0844741698 from Library of Congress and try to add an identifiers (with Firefox, my test takes approx. 15 seconds).

### Expected behavior:

The addition/deletion of a field should be as quick as possible.

### Steps to Reproduce:
1. Import the following ISBN 0844741698 from Library of Congress
2. Add an identifier
3. See that it's really slow

### Context

**Server:**
* [x] production: [bib.rero.ch](https://bib.rero.ch) or [ils.bib.uclouvain.be](https://ils.bib.uclouvain.be)
* [ ] test: [bib.test.rero.ch](https://bib.test.rero.ch)
* [x] dev: [ilsdev.test.rero.ch](https://ilsdev.test.rero.ch)
* [ ] dev test : [ils.test.rero.ch](https://ils.test.rero.ch)

**Version:**

`v1.10.0`

**Browser:**

Firefox: version 99.0.1

**Comment by jma** [comment]
This is linked to the number of initial value for the arrays. Here is a pure ngx-formly example:
https://stackblitz.com/edit/angular-9znuyr?file=src%2Fapp%2Fapp.component.ts,src%2Fassets%2Fjson-schema%2Farrays.json,src%2Fapp%2Farray.type.ts.

Commenting the line 45 make the editor quite fast. I have ask the formly authors on the following gitter room:
https://gitter.im/formly-js/ng2-formly
