### ISSUE TITLE
Add subtypes "Projected image" and "Pictorial book" to the document

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2884]
Document editor: field `type`, add 2 values as `subtype`:
* `docsubtype_projected_image` (French: *Image projetée*) > within main type `docmaintype_image`
* `docsubtype_pictorial_book` (French: *Livre illustré (beaux livres)*) > within main type `docmaintype_book`

**Comment by pronguen** [comment]
corrections de masse à faire après cette issue selon PV 17 groupe metadata: 
Spécifications pour les corrections de masse:

---

Si type de contenu, de média, support matériel = projeté
Type de contenu = image fixe
Type de support matériel = diapositive
Importance matérielle = diapositive* ou DIAPOSITIVE*
Et/ ou autres caractéristiques matérielles : ektachrome ou EKTACHROME
La catégorie type doit être : image et sous-type : image projetée.
Exemple : https://bib.rero.ch/professional/records/documents/detail/262840, https://bib.rero.ch/professional/records/documents/detail/1050939 
*********************************
Si type de contenu, de média, support matériel = projeté
Type de contenu = image fixe
Type de support matériel = diapositive
Importance matérielle = ektachrome* ou EKTACHROME*
La catégorie type doit être : image et sous-type : image projetée.
Exemple : https://bib.rero.ch/professional/records/documents/detail/1474383

**************************************************

Si type de contenu, de média, support matériel = stéréoscopique
Type de contenu = image fixe
Type de support matériel = carte stéréoscopique ou disque stéréoscopique
Importance matérielle = photographie* stéréoscopique* ou stéréoscopique*
La catégorie type doit être : image et sous-type : photographie.
Exemple : https://bib.rero.ch/professional/records/documents/detail/1390761

**Comment by PascalRepond** [comment]
TODO: 
- Dojson adaptation required?
