### ISSUE TITLE
Circulation policy (can request) should take into account the temporary location

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2885]
### How it works

- If an item is in a holding that disallows requests but has a temporary location that allows them, the request button is displayed but creates an error. The initial implementation is missing a test.

### Proposed fix

- When requesting an item with temporary location that allows requests, the request should be possible without error. Even if the holdings location (= item location) disallows requests.

> ## Old issue description
> 
> ### How it works
> 
> Currently, most of the circulation rules are defined in the circulation policies. There is a configuration possible in the location, it is possible to block the requests. The circulation then check if the request is allowed by the cipo, and if yes, check also if it is allowed by the location. If no, the location setting takes precedence and blocks it.
> 
> This works well with the base item location, but has not yet been implemented with the item temporary location.
> 
> ### Improvement suggestion
> 
> Expected: to see if requests are blocked
> * the system performs all the usual checks (cipo, etc.)
> * for the location check, in case of a temporary location, it ignores the base item location and only checks the temporary location.
> 
> Case 1
> * item A
>    * belongs to location LA (requests allowed)
>    * has location LB as temporary location (requests blocked)
> * Result: the request should be blocked
> 
> Case 2
> * item B
>    * belongs to location LB (requests blocked)
>    * has location LA as temporary location (requests allowed)
> * Result: the request should be allowed

**Comment by PascalRepond** [comment]
Reopening this as the implemented fix is incomplete.
