### ISSUE TITLE
Notifications information different depending on the view

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2886]
### Bug description:

The information about the notifications are different depending on wether the checkin is done in the checkin view or the patron loans view.

### Expected behavior:

The information displayed should be the same. All notifications should be displayed. 

3.2023: This info is now indexed in the operation log.

### Steps to Reproduce:

Test 1:
1. Patron A borrows an item.
2. Patron B makes a request.
3. Scan the item on the checkin view https://ils.test.rero.ch/professional/circulation/checkout .

Test 2:
1. Patron A borrows an item.
2. Patron B makes a request.
3. Scan the item on the Patron A loans page Ex: https://ils.test.rero.ch/professional/circulation/patron/2050124312/loan

### Context

**Server:**
* [ ] production: [bib.rero.ch](https://bib.rero.ch) or [ils.bib.uclouvain.be](https://ils.bib.uclouvain.be)
* [x] test: [bib.test.rero.ch](https://bib.test.rero.ch)
* [x] dev: [ilsdev.test.rero.ch](https://ilsdev.test.rero.ch)
* [ ] dev test : [ils.test.rero.ch](https://ils.test.rero.ch)

**Version:**

`v1.10.0` ; commit hash : `XXXX`

**Browser:**

Chrome

### Screenshots

**checkin view**

![image](https://user-images.githubusercontent.com/12396034/167154467-73047917-0c8c-44e6-b71d-33651c5579e8.png)

**Patron loans view**

![image](https://user-images.githubusercontent.com/12396034/167154168-2643585f-05e9-4fcd-8b1d-e88e8b740c71.png)

**Comment by PascalRepond** [comment]
This might be by design? We never display all notifications but only the ones linked to a specific loan. In the patron view, we display the notifications linked to the current patron. In the normal checkout view, we display the notifs for the next loan if there is one.
