### ISSUE TITLE
Edit templates per library for notifications

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2951]
### User story

As a system librarian, I want to customise the notification templates of my library so that the user receives adapted information.

### Acceptance criteria

* templates can be created per library, with a default organisation template
* text can be edited (must not be in the interface)
* images can be added (might imply PDF… to be discussed at grooming)
* [nice to have] layout can be customised (print/mail only)
    * Possible need of a template by location. Use case: there is more than one pickup location for a library and the librarian wants to add more specific information/requirements for an heritage collection (one of the pickup location).

### Tasks

to be completed

Explore https://pbpython.com/python-word-template.html

**Comment by ManaDeweerdt** [comment]
Possible need of a template by location. Use case: there is more than one pickup location for a library and the librarian wants to add more specific information/requirements for an heritage collection (one of the pickup location).
