### ISSUE TITLE
Improve subject mapping for e-bibliomedia e-books

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2978]
### How it works
Currently, e-books subjects are
* imported in English and French without distinction
* not distinguished between fiction and non-fiction
* imported many times because various classifications are used in parallel (example: https://la-chaux-de-fonds.ebibliomedia.ch/v1/resources/62b6a1187d8042000178b9f8.json)

### Improvement suggestion

* if the document contains `classifications.identifiers:FBFIC...` ([example](https://la-chaux-de-fonds.ebibliomedia.ch/v1/resources/5e3a645223579435db13930c.json))
    * import only the `classifications` with this type of identifier, and only in French
    * create the "Fictions" genre/form (see below)
* if the document contains `classifications.identifiers:FBTRV...` ([example](https://la-chaux-de-fonds.ebibliomedia.ch/v1/resources/5c8c9b552357945850af4de5.json))
    * import only the `classifications` with this type of identifier, and only in French
* [later] ideally establish a mapping between the FBFIC/FBTRV codes and the RERO-RAMEAU subjects

---

Genre/form 

```
"genreForm": [
      {
        "identifiedBy": {
          "type": "RERO-RAMEAU",
          "value": "A027757308"
        },
        "term": "Fictions",
        "type": "bf:Topic"
      }]
```

**Comment by PascalRepond** [comment]
Closing, this feature could be developed if needed by the clients.
