### ISSUE TITLE
Item operation history: add total number of checkouts

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2996]
### How it works

It is impossible to know the number of checkouts

### Improvement suggestion

Add 4 info in the item transaction history
   - Past year (Tooltip: Last 365 days)
       - Checkouts
       - Renewals
   - Total
       - Checkouts (total)
           - This includes the sum present in field `legacy_checkout_count`
       - Renewals (total)

Mockup

![image](https://user-images.githubusercontent.com/8154915/178944146-88fba86e-af55-4331-8c27-c48cf35426f5.png)

**Comment by PascalRepond** [comment]
I corrected "loans" to "checkouts". We have to be careful because `loan` is a resource. Same as in the inventory list, what we want to know here is the number of checkout transactions for a given item, not the number of loans. 

@pronguen Question, shouldn't we add the number of renewals as well?

**Comment by pronguen** [comment]
@PascalRepond Thanks. I added the number of renewals, but not sure if this is useful.

**Comment by zannkukai** [comment]
@PascalRepond @pronguen The anonymization of `operation_logs` cause trouble in your proposition.
Number of checkout/extend can only be calculated using this index (loan "triggered operation" change for any circulation op), but the link between patron and op_logs are lost as soon as a loan/op_logs is anonymized.

**Comment by PascalRepond** [comment]
@zannkukai I don't see the problem here. We don't need the link to the patron only the number of checkouts, we can use the same query as in the inventory list.

**Comment by zannkukai** [comment]
@pronguen You're correct, I think about "patron op history" but this issue talks about "item op history". My comment is not-relevant
