### ISSUE TITLE
Lost password workflow only in English

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#3]
Page https://ils.test.rero.ch/lost-password/ should be translated in DE/IT/FR.
Translations should be harmonised for the overall process.

**Comment by iGormilhit** [comment]
This is translated in `invenio-accounts`: [French](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/translations/fr/LC_MESSAGES/messages.po#L111) or [German](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/translations/de/LC_MESSAGES/messages.po#L113)

The question is why this translated messages aren't displayed.

**Comment by NicolasLabat** [comment]
Not fixed

**Comment by rerowep** [comment]
Overwrite Flask-Security configuration:
invenio_accounts.config.SECURITY_REGISTER_USER_TEMPLATE = 'invenio_accounts/register_user.html'
invenio_accounts.config.SECURITY_CHANGE_PASSWORD_TEMPLATE = 'invenio_accounts/change_password.html'
ivenio_accounts.config.SECURITY_FORGOT_PASSWORD_TEMPLATE = 'invenio_accounts/forgot_password.html'
invenio_accounts.config.SECURITY_LOGIN_USER_TEMPLATE = 'invenio_accounts/login_user.html'

and translate them
