### ISSUE TITLE
Loan pick-up location should not be updated at checkout

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#3004]
### How it works

Currently, the loan pickup location is updated to the owning item location at the checkout.

To reproduce:
* Take item A belonging to library A
* Request it with pick-up library B
* Do the checkout from library C
* See at that point that the pick-up location in the loan was updated

### Improvement suggestion

Pick-up location is not updated (in this case). This is then wrong for the statistics.
Only the transaction location should be updated (already the case).

**Comment by PascalRepond** [comment]
The actions to reproduce are not standard at all. This is very minor and not worth fixing.
