### ISSUE TITLE
It should not be possible to link a document to a harvested document

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#3018]
**Describe the bug**

Currently, it is possible to link a document to a harvested document, though fields `partOf`, `supplement`, `supplementTo`, `otherEdition`, `otherPhysicalFormat`, `issuedWith`, `precededBy`, `succeededBy`, `relatedTo`, `hasReproduction`, `reproductionOf`

**To Reproduce**

1. Add one of these fields to a document
2. Look for a document that is harvested
3. Link it to the document and save

**Expected behavior**

It should be prevented by the system.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.12.0`

Could be fixed together with: https://github.com/rero/rero-ils/issues/3016

A similar correction was implemented for the acquisitions: https://github.com/rero/rero-ils/issues/2439

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by PascalRepond** [comment]
To clarify, for existing data do we delete the existing link ? (@pronguen)
