### ISSUE TITLE
User editor: cannot save a new user using a template

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#3053]
### Bug description:

When we load a template to create a new user and try to save, we get errors.

### Expected behavior:

We must be able to create a new user.

### Steps to Reproduce:

**Server:**
* dev test : [ils.test.rero.ch](https://ils.test.rero.ch)

**Version:**

`v1.12.0`

**Browser:**

Chrome, Safari, Firefox; version XX

### Screenshots

![image](https://user-images.githubusercontent.com/12396034/185328561-36ccdc6a-fa12-4eaf-b3ce-660a9731601a.png)

**Comment by PascalRepond** [comment]
I think it only happens with the user template in the test instance's fixtures. Probably the field names in the fixtures are incorrect.
