### ISSUE TITLE
The related documents field disappears when it goes from "link" to "label"

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#3071]
### Bug description:

In edit mode, the related documents field disappears when it goes from "link" to "label".
For example, when the library discards the holdings related to a previous title (document A), the field precededBy in document B should become a simple "Label" (since the record for the document A will be deleted). In this case, the entire field disappears, is removed from the editor. I have to add it again.

### Expected behavior:

In an existing related documents field, switching from Link to Label leaves the field active and present in the record.
Optional (not in this issue): keep the link text in the label

### Steps to Reproduce:

**Server:**
* production: [bib.rero.ch](https://bib.rero.ch) and [ils.bib.uclouvain.be](https://ils.bib.uclouvain.be)
* test: [bib.test.rero.ch](https://bib.test.rero.ch)
* dev: [ilsdev.test.rero.ch](https://ilsdev.test.rero.ch)
* dev test : [ils.test.rero.ch](https://ils.test.rero.ch)

**Version:**

`v1.12.0`

### Screenshots

![image](https://user-images.githubusercontent.com/55576980/188076047-fd37b7cb-c393-4091-9aa4-fab3e4139c52.png)

**Comment by PascalRepond** [comment]
Seems to be fixed by Angular 17/Formly 6 update.
