### ISSUE TITLE
document editor : subject subdivisions to be hidden for RERO+ libraries

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#3078]
### How it works
 Subject fields (local concept) shows subdivisions in scrolling menu
![image](https://user-images.githubusercontent.com/31695537/188592284-d2a488e4-610b-4bc1-ab01-b9f623283781.png)

### Improvement suggestion
For RERO+ libraries subdivisions entries should be hidden in the scolling menu as RERO+ libraries do not use subdivisions

**Comment by PascalRepond** [comment]
It would be far too complicated to differentiate editor fields from an instance to another. If some subfield types are not used, then professionnals should just avoid using them, they don't need to be hidden.
