### ISSUE TITLE
Some loan stay with `CREATED` temporary state.

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#3100]
### Bug description:
In some special cases, some loan are saved with `CREATED` state. This state should only be a temporary state when a `Loan` object is create, but must only transit to `PENDING` or `ITEM_ON_LOAN`. This should never happens

### Expected behavior:
No `CREATED` loan should be saved avec any circulation operation.

### Steps to Reproduce:
don't really how to reproduce.

### Context

**Version:**
`v1.13.0`

### Anything else?
No circulation operations are directly linked with `Loan` REST_API, all API calls are linked to `Item` API (see `items.views.api_views.py)`.
In some cases, the `add_action_parameters_and_flush_indexes` decorator create a new loan object (https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/items/decorators.py#L61 , https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/items/api/circulation.py#L159). But, if no operation are done on this loan due to `invenio_circulation` triggers, then this loan stay on `CREATED` state and should be removed.

I will be interesting to create a system to check if the loan state changed after some circulation operation (request, checkin,checkout, ... not extend [status stay `ITEM_ON_LOAN`]). If it's the case, an error will be logged in Sentry with request context (loan, patron, itty, ...) for future analyzes.

After any circulation operation, if a new loan status is `CREATED` an exception should be raised and this loan should be deleted.
_The best solution should be to not commit/reindex a loan during the circulation process but commit all changes at the end of action process (or rollback if any errors are detected) but this behavior change will be more challenging._

**Comment by PascalRepond** [comment]
May or may not be linked to : https://github.com/rero/rero-ils/issues/1864 https://github.com/rero/rero-ils/issues/2218 https://github.com/rero/rero-ils/issues/2791
