### ISSUE TITLE
facets: unselecting sub-level facets should not unselect superior levels

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#3158]
### How it works
When fitering results with a second or third level facet (for example: library="Bibliothèque communale et scolaire d'Avise"), if I unselect this sub-level, the first level (organisation=réseau des bibliothèques du Canton d'Aoste) is also unselected. This is unintuitive.

### Improvement suggestion
When unselecting a sub-level facet, the facet of the above levels stay selected so that, for example, I can disable the `library` filter while keeping the `organisation` filter.

**Comment by zannkukai** [comment]
The source of the problem seems from `ng-core` : https://github.com/rero/ng-core/blob/staging/projects/rero/ng-core/src/lib/record/search/record-search.service.ts#L98-L101
Question : Why removing parentFilters ?
