### ISSUE TITLE
Loans brief view: expired request facet retrieves wrong loans

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#3209]
### How it works

For now, the facet 'expired_request' retrieves loans with a `request_expire_date` lower than the current timestamp.
With this condition, it will retrieve also the `ITEM_IN_TRANSIT_TO_HOUSE` and `ITEM_ON_LOAN`.
Ex: https://ils.test.rero.ch/professional/records/loans?q=&page=1&size=10&misc_status=expired_request
Need: identify loans with the state `ITEM_AT_DESK`, `ITEM_IN_TRANSIT_FOR_PICKUP` + request expired.

### Improvement suggestion

It should exclude loans with the state `ITEM_IN_TRANSIT_TO_HOUSE` and `ITEM_ON_LOAN`.

**Comment by PascalRepond** [comment]
Closing this as won't fix. It is too difficult to add a second filter and this can already be done with the "Status" facet in the interface.
