### ISSUE TITLE
Inventory list : sort by call number leads to an Error 500

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#3212]
### Bug description:

An error 500 occurs when we try to sort by the call number or the 2nd call number in the inventory list.

### Expected behavior:

Every sort should work properly.

### Steps to Reproduce:

1. Go to inventory list.
2. Change the sort to call number.
3. See error

```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 
'Text fields are not optimised for operations that require per-document field data like aggregations and sorting, 
so these operations are disabled by default. Please use a keyword field instead. 
Alternatively, set fielddata=true on [call_number] in order to load field data by uninverting the inverted index. 
Note that this can use significant memory.')
```

### Context

Due to this PR: https://github.com/rero/rero-ils/pull/3074

**Server:**
* production: [bib.rero.ch](https://bib.rero.ch) or [ils.bib.uclouvain.be](https://ils.bib.uclouvain.be)
* test: [bib.test.rero.ch](https://bib.test.rero.ch)
* dev: [ilsdev.test.rero.ch](https://ilsdev.test.rero.ch)
* dev test : [ils.test.rero.ch](https://ils.test.rero.ch)

**Version:**

`v1.14.1`

**Browser:**

Chrome, Safari, Firefox; version XX

### Screenshots

![image](https://user-images.githubusercontent.com/12396034/212643028-cd90b4da-72e2-4a32-88d7-dbbf5a9a3959.png)

**Comment by lauren-d** [comment]
It's due to indexed field type. `call_number` is indexed as `text` field.
We need to created a new keyword field like `sort_call_number`, reindex all items and update sort field in config.py and rero-ils-ui if needed.

**Comment by PascalRepond** [comment]
2nd call number apparently is not mapped.
