### ISSUE TITLE
Login location not displayed if only one affiliation

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#3477]
### How it works

For now, if a librarian has only one affiliated library, the login location is not displayed.

### Improvement suggestion

Display the library-switch menu for all profesionnal users even when there is only one library.

![image](https://github.com/rero/rero-ils/assets/12396034/b5e57526-58d8-4b0f-8207-d586db6fb4a2)

**Comment by PascalRepond** [comment]
What is the use case for this? It seems not a very useful information to display.

**Comment by ManaDeweerdt** [comment]
> What is the use case for this? It seems not a very useful information to display.
We had an issue with a librarian with the wrong location. It is better if the library is displayed to avoird possible error of editing.
