### ISSUE TITLE
Removing the barcode from a patron leads to an error after "Submit" action

### ISSUE THREAD

**Issue by NicolasLabat** [rero/rero-ils#37]

**Comment by iGormilhit** [comment]
A condition is missing. The [`jsonschema`](https://github.com/rero/reroils-data/blob/master/reroils_data/patrons/jsonschemas/patrons/patron-v0.0.1.json) should states that the patron's barcode is required when `"is_patron": true`.

**Comment by iGormilhit** [comment]
:warning: 
As @BadrAly said, the user module is going to be refactored.

**Comment by iGormilhit** [comment]
As the condition is on the value of a property, it requires the `oneOf` method for the JSON schema, but it's not supported by Angular Schema Form yet

**Comment by iGormilhit** [comment]
It's still possible to submit a patron record without barcode.
