### ISSUE TITLE
Authors facets does not appear on public search view

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#372]
It's difficult to reproduce, because this issue appears only from time to time, and I didn't get any pattern. Sometimes, when you launch a query through the public interface, logged in or not, as a patron, a librarian or a system librarian, the authors facet is not displayed. But sometimes it is. When it's not, clicking on the *persons* tab and back on the *documents* tab makes the authors facets appear. I never saw the authors facet missing when the browser inspector is open. I think that with chrome the facet is always there. As far as I have tested, through the API, the facet is always present.

**Comment by iGormilhit** [comment]
This is still happening on ils.test.rero.ch.

**Comment by iGormilhit** [comment]
**Issue #554 gives further information.**

**Comment by AoNoOokami** [comment]
Should be mentionned in commit message when rero-ils-ui US986 branch will be merged to dev, as the work on this project closes the issue.
