### ISSUE TITLE
Displayed page after creation/update of a ressource

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#376]
Bug: after saving a resource, the page displayed is (at least for document) the page where we were before editing. Ex: a librarian is in his/her library settings, he clicks on "Create a bibliographic record" and save it: he will land again on his/her library settings.

Page to display after saving a
* resource with a professional detailed page (document) → professional detailed page of the resource
* resource with a professional result list (item types, patron types, etc.) → professional result list
* item → professional document detailed page, with item list below

**Comment by iGormilhit** [comment]
@pronguen I think we have to update specification of this having in mind recent decision, ie professional interface and public interface being separated.

And I also think that it could be done by a US.
