### ISSUE TITLE
Wrong organisation when adding item or patron types

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#389]
As a librarian or system librarian of Org 1, when I try to add an item or patron type, it belongs by default to Org 2, and I am not able to save it.
* It should belong by default to Org of the authentified librarian (Org 1)

As a system librarian of Org 2, it works as expected.

**Comment by iGormilhit** [comment]
3rd organisation is now "Network of fictive libraries".

**Comment by zannkukai** [comment]
Seems fixed with new rero-ils-ui. To be confirmed
