### ISSUE TITLE
Scope of search bar not always visible

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#39]
The scope of the search bar is not always visible. For example when I edit a patron, the scope is not defined. See https://ils.test.rero.ch/editor/update/ptrn/13

**Comment by pronguen** [comment]
The scope should *always* be displayed for a librarian, whatever it is.

The scope varies according to the page where the librarian is:
* Menu "circulation" and related pages: scope "Documents"
* Menu "documents" and related pages (editor, detailed view, item view, result list, ...): scope "Documents"
* Menu "organisations" and related pages: scope "Libraries and locations" (for future, or members and locations for present)
* Menu "users" and related pages: scope "Users"

**Comment by iGormilhit** [comment]
And the scope information should be more than just a placeholder.

**Comment by iGormilhit** [comment]
Not relevant anymore.
