### ISSUE TITLE
Wording: details

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#4]
Error: two words without white space in this sentence: "Vous avez bien réinitialisé votre mot de passe et avez été automatiquementconnecté."
The form used to reset the password would be more understandable with the wording "Nouveau mot de passe" and "Confirmer le nouveau mot de passe" in the two fields.

**Comment by iGormilhit** [comment]
For the missing space, see: https://github.com/mattupstate/flask-security/pull/751

**Comment by NicolasLabat** [comment]
Error on the homepage in French : Le projet RERO ILS a pour but de créer le futur système de gestion de **blibliothèque** --> bibliothèque

**Comment by iGormilhit** [comment]
@NicolasLabat Not the same topic, I've  created a new issue: https://github.com/rero/reroils-app/issues/31

**Comment by NicolasLabat** [comment]
Not fixed

**Comment by iGormilhit** [comment]
@jma Could we use the develop branch? https://github.com/mattupstate/flask-security/tree/develop

**Comment by iGormilhit** [comment]
According to [this comment](https://github.com/mattupstate/flask-security/pull/751#issuecomment-505071503), we should use the following fork of `flask_security`: https://github.com/jwag956/flask-security (which does have, among other things, the fix of this issue).

**Comment by AoNoOokami** [comment]
Version used: 3.0.0
Version who includes the fix: 3.0.1
