### ISSUE TITLE
Increase size of result set during API calls 

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#405]
Release 0.2.3

We have created a test instance with : 
3 organisations
22 libraries
75 locations
9 patron_types
37 item_types

In the admin screen for "circulation policies", we can choose the organisation/libraries, the patron types and the item_types but by default, the software displays ONLY the first 10 entries.
(So we are unable to configure the circ policies for all libraries, item_types or patron types.)

![Capture du 2019-07-17 15-24-55](https://user-images.githubusercontent.com/16501502/61379290-8a037d00-a8a7-11e9-9470-8a0e46b5cfb0.png)

For now, it calls the APIs like this : 

![Capture du 2019-07-17 15-30-28](https://user-images.githubusercontent.com/16501502/61379475-e797c980-a8a7-11e9-9b2c-adb127f47a11.png)

You need to increase the "default size" of APIs result sets when you get the list of libraries, items types etc...
or you could add a "size" parameter when you call the APIs
Ex:  /api/item_types/    =>   /api/item_types/?size=100
/api/locations/    =>   /api/locations/?size=100

Hope it helps,
Ben & the team :-)

**Comment by benerken** [comment]
It's the same behaviour when we edit an ITEM.
It lists the locations available, but only the first 30 entries. 
It calls "/api/locations/?page=1&size=30&q="
=> You need to increase the size for consortium with more than 30 locations.

**Comment by lauren-d** [comment]
Hi,
 
I guess that isn't the best way but, as temporarly workaround, it's possible to modify methods in library.service.ts and item-type.service.ts files like that : 

```
libraries() {
    return this.http.get(
      this.apiService.getApiEntryPointByType('libraries')+'?size=100',
      httpOptions
    );
  }
```

```
itemTypes() {
    return this.http.get(
      this.apiService.getApiEntryPointByType('item_types')+'?size=100',
      httpOptions
    );
  }

```

best,

Lauren-D
for UClouvain
