### ISSUE TITLE
Checkout for the end of a day (23h59)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#417]
Current situation:
* we define a checkout of 3 days in the CIPO
* We do a checkout this morning at 10:00. The system fixes the due date at today + 3days = 2019-08-03 10:00

Desired situation:
* By default, the due date is set on the end of the day (23h59)

*Note for later: it will be possible to define in the circulation policy a checkout of less than one day (1 hour, 4 hours, ...)*

**Comment by BadrAly** [comment]
Same logic for the renewal transaction.
