### ISSUE TITLE
Patron without barcode

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#48]
When trying to display patron nr. 10 (Broglio, Giulia), we got an internal error server. To reproduce it, try to open [https://ils.test.rero.ch/patrons/10](https://ils.test.rero.ch/patrons/10).
It seems that this patron does not have any barcode, is this the cause of the problem? How is it possible that she has no barcode?

For information, this problem already appeared at previous deployment with patron Simonetta.

**Comment by iGormilhit** [comment]
@pronguen I've been able to edit this patron loading the http://localhost:5000/editor/update/ptrn/10 URL, and then to correct the missing barcode.

Still, I don't understand how this patron had no barcode after the populate.

**Comment by iGormilhit** [comment]
On localhost, at the https://github.com/rero/reroils-data/commit/6533d66c98dfc0db2678113215a8365c797cfd20, I have:
![capture_120](https://user-images.githubusercontent.com/1557213/42227989-187ce412-7ee3-11e8-9388-fe915db6fef0.png)

**Comment by iGormilhit** [comment]
After a fresh deployment, all patrons have barcodes. I think that the removing of the barcode happens later, but I don't know how.

**Comment by pronguen** [comment]
Sorry, I just destroyed again Giulia. What I did:
* Looked for patrons
* Selected Broglio, Giulia
* Edited the patron
* Deleted the barcode, but kept the patron role
* Saved
* Answer from the system: "The record has been saved (Utenti, pid: 10)." (Flash notification) + "Internal server error"

I managed to reintegrate this patron by using the "back" button of my web browser, and saving it again with the barcode.

Two problems then:
* No validation before saving that there is a barcode
* Saving is possible without barcode
