### ISSUE TITLE
Broken link in circulation table

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#50]
After the checkin of an item, the link to the document displayed in the circulation table (first column) is broken.

**Comment by iGormilhit** [comment]
I think this is the case every time a new item is added in the table, be it a check in or a check out. The link doesn't have any document PID at the end.

**Comment by MarionRERO** [comment]
Is this the reason why the link to the document in the circulation table gives an error message "
Page not found - The page you are looking for could not be found."?

**Comment by iGormilhit** [comment]
@MarionRERO Yes, it is.
