### ISSUE TITLE
Wrong circulation status after checkin

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#51]
After checkin of an item with a request, the item has a circulation status "on_shelf". It should be directly "at_desk" (if the pickup member == transaction.member).

**Comment by iGormilhit** [comment]
If `pickup member != transaction.member` it's ok. It's only in the case indicated by @pronguen.

**Comment by MarionRERO** [comment]
When the status of the item isn't at_desk, the patron doesn't receive a notification either.

**Comment by pronguen** [comment]
See issue #235
