### ISSUE TITLE
Title missing in e-mail sent to patron

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#52]
The title is missing in the document availability e-mail sent to the patron. See [original_msg.txt](https://github.com/rero/reroils-app/files/2154630/original_msg.txt). In this e-mail example, the corresponding document is doc [10676](https://ils.test.rero.ch/documents/10676).

**Comment by iGormilhit** [comment]
Fixed through PR https://github.com/rero/rero-ils/pull/347
