### ISSUE TITLE
Journal/giornale appears as "Città" in facet document type

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#529]
Journal/giornale appears as "Città" in facet document type and under the cover in the document brief view.
In the detailed view, the correct label is displayed.
The translation seems ok.

![image](https://user-images.githubusercontent.com/8154915/65670512-cb519f00-e045-11e9-978e-2ce29cdc8ad7.png)

**Comment by AoNoOokami** [comment]
Journal is translated as "Città" in the json file in the previous ui app. Should it be corrected on both or only in the new one?

**Comment by pronguen** [comment]
@AoNoOokami If it is corrected in the new one, it is the most important!
