### ISSUE TITLE
Missing space between the check boxes and the titles of the roles in the patron registration form

### ISSUE THREAD

**Issue by rerowyj** [rero/rero-ils#539]
In the patron registration form, there is no space between the check boxes and the titles of the roles (user, librarian, system librarian).
![Capture space roles](https://user-images.githubusercontent.com/33427631/65950177-d63d7280-e43d-11e9-80aa-dfc8bea8a4fb.JPG)

**Comment by rerowep** [comment]
There is the same problem in circ policies form. Should be a general problem of the form editor for checkboxes.

**Comment by iGormilhit** [comment]
Closed by release [v0.6.0](https://github.com/rero/rero-ils/releases/tag/v0.6.0)
