### ISSUE TITLE
Wrong orgnisation translation in the item type editor

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#540]
**Describe the issue**
The item type editor displays a wrong french translation, "Collectivité" instead of "Organisation". But should this read only field even be display, in the first place?

**To Reproduce**
1. Log in as a librarian.
1. Through the menu, create a new item type.
1. Be sure to use the french user interface.
1. The first field input name reads "Collectivité".

**Expected behavior**
The first field name should read "Organisation".

**Screenshots**
![rero-ils-itemtype-collectivite](https://user-images.githubusercontent.com/1557213/65951127-e8fc7b00-e42e-11e9-84c2-58764d55b496.png)

**Additional context**
I think that for English, German and Italian, the translations are correct.

**Comment by pronguen** [comment]
@iGormilhit In the translation process, we decided to use
* "corporate body" (RDA official terminology) for an agent related to a document
* "organisation" for the RERO ILS consortial structure.

On that basis, @AoNoOokami asks if we change the translation only in Transifex or also directly in the code (everywhere). I think the 2nd option is more clear and maintainable.
