### ISSUE TITLE
Persons aren't filtered by views

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#550]
**Describe the issue**
Every view give access to the complete persons list, even if there's no document/holdings/item associated to theses persons in a given view.

**To Reproduce**
1. Launch an instance at least containing https://github.com/rero/rero-ils/commit/11b52713d3a03af4dc6a2e30084efaac9500b0d3
1. On the frontpage, click on the "Réseau des bibliothèques du Canton"
1. Make an empty request to display the entire view results.
1. See the Persons tabs, with no document/holdings/item associated.

**Expected behavior**
No person without document/holdings/item should be displayed.

**Comment by iGormilhit** [comment]
Public search is filtered by views.

Professional search is filtered by logged in professional.

**Comment by pronguen** [comment]
For this issue, the correction must be done only in the public view.
For admin view, see [US 984](https://tree.taiga.io/project/rero21-reroils/us/984)
