### ISSUE TITLE
Facet author not always displayed (in Firefox)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#554]
The author facet is not always displayed when launching a search:
* Example: https://ils.test.rero.ch/global/search/documents

Switching to the "Person" result tab and back to the "Document" tab: the facet usually appears.

After a few tests, the problem seems to exist in Firefox (69.0.2, desktop Windows). Not observed in Chrome and Firefox for Android.

**Comment by iGormilhit** [comment]
Duplicate of https://github.com/rero/rero-ils/issues/372.

**Comment by iGormilhit** [comment]
As it is a duplicate, I close this issue.
