### ISSUE TITLE
Missing translation of "requested items"

### ISSUE THREAD

**Issue by MarionRERO** [rero/rero-ils#56]
The French, German and Italian translations of "requested items", as a header to the table, are missing.
<img width="966" alt="capture d ecran 2018-07-04 a 11 32 21" src="https://user-images.githubusercontent.com/32259659/42269396-55c057f0-7f7e-11e8-9941-76f72fcb810a.png">

**Comment by iGormilhit** [comment]
Maybe this text is not even necessary, there's already a title on top of the input field (in french 'Demande(s)'). But if we keep it, it should be translated, that's true.
