### ISSUE TITLE
Add a changelog autogeneration script

### ISSUE THREAD

**Issue by blankoworld** [rero/rero-ils#568]
# Description

`CHANGES.rst` is now generated by https://github.com/github-changelog-generator/github-changelog-generator

Each time we want to update the release, we need to: 

- generate the .md file (Markdown)
- transform it to .rst
- append after the header
- delete all text older that tag v0.1.0a16

These actions could be done via an automatic script.

**Comment by iGormilhit** [comment]
Now it's much simpler as we keep the file in markdown:

```bash
github_changelog_generator --user rero --project rero-ils -t <token> --release-branch dev --future-release <release-tag> --since-tag v0.1.0a13 -o CHANGES.md
```

The github changelog could be added to to npm packages installed through the bootstrap script. And the command added to the poetry commands.
