### ISSUE TITLE
Protect the library custom editor

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#575]
As librarian, I can access directly (by url) to the edit form of another library. Is it possible to protect that?
note: the save action doesn't work as expected

If you login as Virgile, you can have access to all libraries by changing the pids in the url:
`~/admin/records/libraries/2`

**Comment by iGormilhit** [comment]
@BadrAly Could it be related to https://github.com/rero/rero-ils/issues/574 ?

**Comment by BadrAly** [comment]
> @BadrAly Could it be related to #574 ?

@iGormilhit https://github.com/rero/rero-ils/issues/574 does address the backend permissions part of the problem. This issue needs to be fixed in the new (or current) `ui` admin.
