### ISSUE TITLE
Changes of communication language for patrons are effective but not displayed

### ISSUE THREAD

**Issue by rerowyj** [rero/rero-ils#583]
Changes of communication language in the patron editor are effective but not displayed.

1. Log in as a librarian
2. Edit a patron record 
3. Change its communication channel and click on 'Submit'
4. Edit again the same patron record
5. The change of communication channel doesn't appear in the form

![image](https://user-images.githubusercontent.com/33427631/67494157-124ca780-f679-11e9-99c0-14e835bb7f87.png)

**Comment by zannkukai** [comment]
Same behavior for `communication channel`.
If I empty my cache and try again, all works as expected.
