### ISSUE TITLE
New/edit patron required field validation

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils#584]
**Describe the issue**
When creating a new patron or editing an existing one, following required fields are not validated:
* Barcode or card number
* Communication channel
* Communication language

<img width="1094" alt="Screen Shot 2019-10-25 at 12 25 52" src="https://user-images.githubusercontent.com/28982829/67564240-dbcb6700-f722-11e9-9cea-d7c778412b7f.png">

**To Reproduce**
1. Login as system librarian
2. Go to User Services>Patrons>Add
3. Fill in all required fields except for those mentioned above
4. Submit button is enabled

**Expected behavior**
Submit button should be disabled if required fields are empty or not selected.

**Additional context**
Should be corrected in rero-ils-ui + ng-core

**Comment by iGormilhit** [comment]
Closed by https://github.com/rero/rero-ils/commit/2d80af920fb4b9d147e855a44fb1187e9a0869e1(move to ngx-formly).
