### ISSUE TITLE
Due date according to opening hours not working

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#599]
**Describe the issue**
The due date is not always set at an opened day.

**To Reproduce**
1. Log in as Virgile
1. Set your library "[Bibliothèque du Lycée de la Vallée d'Aoste](https://ils.test.rero.ch/admin/records/libraries/4)" to be opened only one day, for instance on Monday
1. Choose an item from Bibliothèque du Lycée de la Vallée d'Aoste, with type "standard"
1. Go to [checkin for Simonetta](https://ils.test.rero.ch/admin/circulation/checkinout?patron=2050124311)
1. Checkout the item for Simonetta
1. The due date is one day after the opening day of the library

**Expected behavior**
The due date should be set on an opened day of the transaction library

**Software version**
* Server: https://ils.test.rero.ch/
* Version: 0.5.1

**Comment by blankoworld** [comment]
Closed by https://github.com/rero/rero-ils/commit/01595a3a7a2784d81da13ff362ff4c5c4bf2460d
