### ISSUE TITLE
Location settings aren't explained in the editor and an online pickup location is possible

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#604]
**Describe the issue**
The location editor provides no explanation for the `is pickup location` and `is online` settings. Furthermore, both options can be activated.

**To Reproduce**
1. Log in as a system librarian or a librarian.
1. Create or edit a location.
1. See that there's no help provided to understand `is pickup location` and `is online` settings.
1. See that the submit button is not deactivated when both settings are selected.

**Expected behavior**
A usefull help message should be added to explain what are these settings. And an online location being a pickup location should not be possible.

**Software version**
ils.test.rero.ch, v0.5.1

ilsdev.test.rero.ch, https://github.com/rero/rero-ils/commit/9aa529c322f62a74b683d4814fcc78c65fece874

**Screenshots**
![reroils-location-online](https://user-images.githubusercontent.com/1557213/68379033-049d2480-0145-11ea-812d-35e341a8de53.png)

**Comment by zannkukai** [comment]
![image](https://user-images.githubusercontent.com/10031585/76416100-b752ed00-639a-11ea-8da6-8cb2d49e306a.png)
Solved
