### ISSUE TITLE
Validation message for email field

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#621]
**Describe the issue**
The validation message for the e-mail, in the patron creation form, is not user friendly:

> Must match pattern: ^.*@.*\..*$
> Must be an email address, like "name@example.com"
> Must be 6 characters or longer (current length: 1)

Line 1 is not understandable by a user and line 2-3 are not useful.

**To Reproduce**
1. Open the form to add a new patron
1. Type one character in the email field

**Expected behavior**
The user should only get a message "The e-mail is not valid."

**Software version**
ils.test.rero.ch, version 9aa529c3

**Comment by iGormilhit** [comment]
Yes, this is known. We have to move all validation messages that are now in the JSON schemas in the form options. The behaviour changed between `json-schema-form` and `anglular6-json-schema-form`.
