### ISSUE TITLE
Add locations to other libraries

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#622]
**Describe the issue**
From the brief view of libraries, a librarian can click to add locations to other libraries then his/her own. The forms is opened, but cannot be saved.

**To Reproduce**
1. Login as a librarian (not a system librarian)
1. Go to brief view of libraries
1. Click on "Add" for a location of another library than his/her own
1. Fill the form
1. Try to save

**Expected behavior**
* The "Add" button for locations of other libraries should not be displayed
* In the location edit form, only the librarian's library should be available (or the field should not be editable)

**Software version**
ils.test.rero.ch, version 9aa529c3

**Comment by AoNoOokami** [comment]
I'm closing it because it has been grouped with https://github.com/rero/rero-ils/issues/787
