### ISSUE TITLE
Item type with name "Standard"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#624]
**Describe the issue**
It is impossible to create an item type with name "Standard". System says *The item type name is already taken*, but it is not true: it doesn't exist inside the organisation.
The problem doesn't appear with other item type names.

**To Reproduce**
1. Open the item type editor for a new type
1. Fill up the name field with value "standard"
1. See validation message

**Expected behavior**
* if the item type name already exists in the same organisation, the name is blocked
* if the item type name already exists in other organisations but not in the current, the name is not blocked

**Software version**
ilsdev
version 1de3d25e

**Comment by iGormilhit** [comment]
Could it be that the async validator do not filter correctly by organisation?

**Comment by AoNoOokami** [comment]
When we are connected as reroilstest@gmail.com, there is an item type with the name "Standard". For which organisation is described this issue?

**Comment by pronguen** [comment]
I forgot to precise the organisation. I think it was org3, but now I cannot reproduce the bug. I discovered another reason blocking the name "Standard" (ils.test, 0.5.2):
1. log in as reroilstest@gmail.com (org1)
1. change item type "Standard" to "Standard2"
1. try to add an item type "Standard"

Result: "The item type name is already taken".

**Comment by iGormilhit** [comment]
Closed by release [v0.6.0](https://github.com/rero/rero-ils/releases/tag/v0.6.0)
