### ISSUE TITLE
Barcode and callnumber (at item level) shoudn't be mandatory

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#648]
**Describe the issue**
At item level, the fields "barcode" and "callnumber" shoudn't be mandatory.
In some cases, these fields can be empty (a new order in acquisition module etc...), 
or some libraries doesn't set barcode to items, because there is no loans for them.

**To Reproduce**
Create an new item: you'll see fields like barcode and callnumber are required.

**Expected behavior**
Staff should be able to create/modify an item, even if it hasn't any barcode or callnumber.

Be Careful: Today, in the document view (biblio + holdings/items), there is a hyperlink on barcode in order to view the item details screen. If we allow the barcode to be empty, this hyperlink should be set to another field on the item (See below)

![image](https://user-images.githubusercontent.com/16501502/69967591-02966d80-1519-11ea-8512-3df1d48287c3.png)

**Software version**
  * ils.test.rero.ch (v. 0.5.2)

**Comment by iGormilhit** [comment]
This issue is closed by https://github.com/rero/rero-ils/commit/8c9ca0abb8c5f194d250aab53f80d2196b47a665 in [release v0.9.0](https://github.com/rero/rero-ils/releases/tag/v0.9.0)
