### ISSUE TITLE
ElasticSearch always complaining about deprecated field _version_type and _version

### ISSUE THREAD

**Issue by blankoworld** [rero/rero-ils#725]
**Describe the issue**

When running the setup, ElasticSearch logs show:

```
es_1     | [2020-01-30T08:11:01,810][WARN ][o.e.d.c.ParseField       ] [esGFWFx] Deprecated field [_version] used, expected [version] instead                                 
es_1     | [2020-01-30T08:11:01,811][WARN ][o.e.d.c.ParseField       ] [esGFWFx] Deprecated field [_version_type] used, expected [version_type] instead                       
e
```

It appears that `rero_ils/modules/api.py` contains `def _index_action` that permit to change this quickly.

**Comment by rerowep** [comment]
No, we have to wait for a update from invenio!

**Comment by rerowep** [comment]
https://github.com/inveniosoftware/invenio-indexer/issues/91

**Comment by rerowep** [comment]
duplicate with: https://github.com/rero/rero-ils/issues/83

**Comment by AoNoOokami** [comment]
I'm closing this because it's a duplicate.
