### ISSUE TITLE
documents: import EAN - some abstracts are HTML encoded

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#743]
**Describe the issue**
When you create a document using "Import EAN", it retrieves metadata but sometimes, the abstract contains "HTML encoded" diacritics. 

**To Reproduce**
1. Login as librarian
1. Click on "Create a document"
1. In the box "Import EAN", copy/paste ISBN 9782035930910. Click on button "Import"
1. Have a look to the abstract. You'll see the problem like in the screen capture below.

**Screenshots**
![image](https://user-images.githubusercontent.com/16501502/74034461-9de40d00-49b8-11ea-932e-34db5481b70e.png)

**Expected behavior**
Decode HTML entities like "&amp;eacute;" in the abstract in order to get a "clean" abstract. (with "é")

**Software version**
ilsdev.test.rero.ch (0.5.2)

**Comment by rerowep** [comment]
It's stored like this on BNF:
```
<mxc:subfield code="a">
&nbsp; D&eacute;r&egrave;glement climatique, pollution des sols, &eacute;puisement des ressources fossiles, gaspillage &eacute;nerg&eacute;tique, scandales alimentaires et sanitaires, in&eacute;galit&eacute;s entre les populations&hellip; Il est temps d&rsquo;agir&nbsp; !&nbsp; Comment s&rsquo;y prendre&nbsp; ? Et si tout commen&ccedil;ait par la terre qui nous nourrit&hellip; Le mod&egrave;le agricole d&eacute;velopp&eacute; depuis les ann&eacute;es&nbsp; 60 consomme plus qu&rsquo;il ne produit, co&ucirc;te tr&egrave;s cher &agrave; la soci&eacute;t&eacute; et fait des ravages sur notre environnement et notre sant&eacute;. Alors que le secteur pourrait cr&eacute;er de l&rsquo;emploi et revitaliser nos campagnes, il fait exactement le contraire&nbsp; ; mais plus pour longtemps&nbsp; : les alternatives s&rsquo;organisent&nbsp; !&nbsp; Convaincu que l&rsquo;alimentation et l&rsquo;agriculture sont les premiers chantiers pour un avenir d&eacute;sirable, Maxime de Rostolan se bat avec toute l&rsquo;&eacute;quipe de l&rsquo;association Fermes d&rsquo;Avenir pour que l&rsquo;agro&eacute;cologie &agrave; taille humaine remplace l&rsquo;agriculture chimique de grande &eacute;chelle.&nbsp; Cet ouvrage accompagne la sortie du film documentaire de H&eacute;l&egrave;ne M&eacute;digue avec pour objectif de relier et mobiliser les pouvoirs publics, les citoyens, les entreprises, les paysans, les investisseurs, les personnalit&eacute;s&hellip;Vous aussi, lancez-vous&nbsp; !&nbsp; Maxime de Rostolan a fond&eacute; le r&eacute;seau Fermes d&rsquo;Avenir et Blue Bees, la premi&egrave;re plateforme de financement participatif d&eacute;di&eacute;e aux projets agricoles. Il remue ciel et surtout terre pour mettre en place un nouveau mod&egrave;le agricole.
</mxc:subfield>
```
Should we replace the html encoding?

**Comment by benerken** [comment]
It's not an emergency for now, but in the end, I guess a standard librarian will say "when I import a record, there is a problem with the abstract. I see strange things in the box". :-)
What do you think at RERO ?

**Comment by benerken** [comment]
Another example with EAN 9782807320185

The diactritics in the **abstract** looks good but there are not correctly coded.

you get this  "Par une approche fond**é**e sur l'exemple...."
but you should get "Par une approche fond**é**e sur l'exemple..."  

The json result of BNF API call looks like this for the abstract:

"abstracts": [
      "\"Par une approche fond**e\u0301**e sur l'exemple et l'illustration empirique, Paul Krugman, Prix Nobel d'**e\u0301**conomie 2008...
    ],

**Comment by benerken** [comment]
About ISBN 9782807320185, it seems to be a "local" problem of character rendering (fonts) in my browser (Firefox).
There is no problem with Chrome.
It's not an issue. I close it.
