### ISSUE TITLE
In transit to: display library name

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#769]
**Describe the issue**
In circulation UI, for a transaction with transit, it is displayed "in transit (to x)" where x is the location code. For pilot library data, this code is not understandable for human.

**To Reproduce**
Case 1: in the checkin form
1. Go to the checkin form
1. Do a checkin an on item that is on loan, without request and from another library
1. The item appears in the list with "in transit (to x)" where x is the location code

Case 2: in the patron account
1. Same procedure: do the same checkin but from a patron account

**Expected behavior**
x should be the library name
This should be the case for all destination in all cases. Later: display of the pickup location additionally.

**Software version**
ilsdev + ilspilot
rero-ils version c236bc87
rero-ils-ui version 4fc4656d

**Comment by pronguen** [comment]
Issue not solved: Currently is display library name + location. We want only library name.

**Comment by blankoworld** [comment]
Some details explained on Gitter (french): 

```
1. Dans certains cas de transit (lorsqu'il y a une request), la destination est une location "pickup" et il faudrait n'afficher que le texte de la pickup location name (qui est différent du location name)
2. Dans d'autres cas de transit (sans requests), la destination est une location (pas forcément pickup), et dans ce cas il faudrait n'afficher que le library name.
C'est un aspect de détail mais très important dans ce genre d'interface devant être optimisée pour du travail répétitif. Un nom de bibliothèque+localisation trop long ne sera pas lu entièrement, il doit être court.

- solution intermédiaire: afficher dans les 2 cas susmentionnés le library name (et le cas d'une library avec plusieurs pickup locations sera réglé plus tard)
```
