### ISSUE TITLE
In transit to: destination not displayed

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#770]
**Describe the issue**
In circulation UI, for a transaction with transit, destination is not displayed: "in transit (to )".

**To Reproduce**
Case 1: in the checkin form
1. Go to the checkin form
1. Do a checkin an on item that is on loan, with a request and a pickup in another library than the checkin library
1. The item appears in the list with "in transit (to )": no destination is displayed

Case 2: in the patron account
1. Same procedure: do the same checkin but from a patron account

**Expected behavior**
Library name should be displayed as destination

**Software version**
ilsdev + ilspilot
rero-ils version c236bc8
rero-ils-ui version 4fc4656d

**Screenshots**
![dbocnneimccobdif](https://user-images.githubusercontent.com/8154915/74831556-bf78b900-5315-11ea-802a-5e4ce68d8b97.png)

**Comment by zannkukai** [comment]
This problem occured only on 'circulation/checkout' page : the method "getTransitLocationPid()" return `null` because the item object doesn't have any `loan` attribute

**Comment by pronguen** [comment]
The case 1 is not solved. Transit destination is not displayed. (tested on ilsdev, rero-ils version e2fbc6b2, rero-ils-ui version 925ffabb)

![image](https://user-images.githubusercontent.com/8154915/75160244-f8e86480-5719-11ea-8b98-1f1822b7e863.png)

**Comment by pronguen** [comment]
Case 2 in the patron account is not resolved. 

Patron account: checkin
![image](https://user-images.githubusercontent.com/8154915/75161019-62b53e00-571b-11ea-8b00-b57047def92c.png)

Item detailed view
![image](https://user-images.githubusercontent.com/8154915/75160987-5335f500-571b-11ea-8ddc-6c32bc03d5e4.png)

**Comment by pronguen** [comment]
Case still not resolved. It seems to be a difference based on the owning library of the item, where it should not. My tests below.

The requests done (as Simonetta):
![image](https://user-images.githubusercontent.com/8154915/75321692-9904d180-5871-11ea-8567-20919313b7f2.png)

The checkin done (as Astrid, Bibliothèque du Lycée de la Vallée d'Aoste):
![image](https://user-images.githubusercontent.com/8154915/75321737-b2a61900-5871-11ea-9282-f61d61079d90.png)

Problems:
* avise1: in transit to Lycée, but Astrid (working at Lycée) just made a checkin so it should be at desk
* avise2: at desk, but was asked with pickup in Avise
* lycee1: ok
* lycee2: ok
