### ISSUE TITLE
Impossible to create a user with role "librarian"

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#771]
**Describe the issue**
When I create a user (ie. a patron), in the patron editor, add the role librarian, but I cannot save, even if all fields marked with asterisk are filled. The fields related to role patron are displayed. If I fill these fields, I can save. Whatever information I fill, if I select the role librarian, I get an error when saving the record, and cannot edit this record any more.

**To Reproduce**
1. Add a new patron/user
1. Select role librarian
1. Try to save
1. Fill all fields, incl. patron fields
1. Save and see error

**Expected behavior**
* Patron fields or librarian fields are displayed only if the corresponding role is selected.
* Saving a librarian is possible without filling patron fields

**Software version**
ilsdev + ilspilot
rero-ils version c236bc8
rero-ils-ui version 4fc4656d

**Comment by benerken** [comment]
Should be solved by PR https://github.com/rero/rero-ils/pull/773
