### ISSUE TITLE
Wrong locations proposed in the item editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#772]
**Describe the issue**
On a document detailed view, I add an item. The locations proposed are
1. either locations of my own library if the document has no other items
1. or locations of the library associated to already existing items on this document

In this second case, I cannot save my item.

**To Reproduce**
1. Add an item to a document with already an item of another library
1. Try to select a location of you library: it is impossible
1. Select a location of the other library
1. Save (it should not be possible)

**Expected behavior**
* The locations proposed in the item editor should be taken only from the library of the connected librarian, or from the current library of the system librarian
* It should not be possible to add items to other libraries

**Software version**
ilsdev + ilspilot
rero-ils version c236bc8
rero-ils-ui version 4fc4656d

**Comment by zannkukai** [comment]
When you refresh the editor page, the location select box options are well populated.
Maybe the problem come from 
  * https://github.com/rero/rero-ils-ui/blob/dev/projects/admin/src/app/routes/items-route.ts#L122 
  *  or https://github.com/rero/rero-ils-ui/blob/dev/projects/admin/src/app/routes/items-route.ts#L125

`userService.getCurrentUser()` or/and `user.currentLibrary` return a bad value at first call.
 Refreshing page solved the issue.
