### ISSUE TITLE
Checkin of item with requests: in transit to wrong library

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#780]
**Describe the issue**
As a librarian, **in a patron account**, I do a checkin of an item that holds a request:
1. If the item is requested with a pickup location not equal to my library, the item goes "at desk" instead of "in transit"
1. If the item is requested with a pickup location equal to my library, the item goes "in transit" to a random library (?) instead of "at desk".

As a librarian, **in the checkin form**, the same transactions have different behaviour:
1. If the item is requested with a pickup location not equal to my library, the item goes "in transit" to a random library (?) instead of "in transit" to the pickup library.
1. If the item is requested with a pickup location equal to my library, the item goes "in transit" to a random library (?) instead of "at desk".

*All cases have been tested on ilsdev and ilspilot*

**To Reproduce**
1. Open a patron account (tab checkout)
1. Add for this patron 2 items on loan
1. Add requests to these 2 items, one with pickup location equal to librarian's library, the other with another pickup location (for this step you have to log in as a patron)
1. In the patron account (tab checkout), checkin the 2 items
1. See error

Reproduce the same processes, but do the checkin on the 2 items from the checkin form (outside of a patron account).

**Expected behavior**
* the result of a checkin should always be the same, whenever it is in the checkin form or in the patron account (tab checkout)
* the transit destination should be the pickup library name (ideally "pickup location name") of the request
* status "in transit" or "at desk" should correspond to the transaction library (ie. to the library of the connected librarian)

**Software version**
ilsdev + ilspilot
rero-ils version c236bc8
rero-ils-ui version 4fc4656d

**Comment by BadrAly** [comment]
An invenio-circulation bug related to this function https://github.com/inveniosoftware/invenio-circulation/blob/c3fcc1a4674d5df24221e3c068e8e0c07db68016/invenio_circulation/transitions/transitions.py#L80

**Comment by pronguen** [comment]
Case 2 in the patron account is not resolved. 

Patron account: checkin
![image](https://user-images.githubusercontent.com/8154915/75161019-62b53e00-571b-11ea-8b00-b57047def92c.png)

Item detailed view
![image](https://user-images.githubusercontent.com/8154915/75160987-5335f500-571b-11ea-8ddc-6c32bc03d5e4.png)
