### ISSUE TITLE
Display Popup for a checkin operation if item are in transit

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#783]
When librarian operates a checkin operation, if the item state goes from ON_LOAN to IN_TRANSIT, the application should open a popup (or similar) to explain to the librarian that a special operation need to be done on this item.

At this time, librarian can operate multiple operation and UI displays only "in transit" whitout any other blocking action

![image](https://user-images.githubusercontent.com/10031585/75029162-d9df9d80-54a1-11ea-8f96-3d42f774286b.png)

*expected behavior:*
Display a popup to force the librarian to operate a special operation. This popup should specify the library/location where this item need to go

**Comment by pronguen** [comment]
Currently transactions needing an action are highlighted with a red border. Another kind of highlight can be discussed.
We try to avoid modal windows for warnings.
**A flash message should be displayed in any case when the transaction has fees or requests!**

**Comment by iGormilhit** [comment]
Related to https://github.com/rero/rero-ils/issues/770.

**Comment by AoNoOokami** [comment]
> Currently transactions needing an action are highlighted with a red border. Another kind of highlight can be discussed.
> We try to avoid modal windows for warnings.
> **A flash message should be displayed in any case when the transaction has fees or requests!**

It's the case for the requests but not for the fees. I will address this issue.
