### ISSUE TITLE
Pickup name of location must be required

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#794]
**Describe the issue**
The pickup name is missing for pickup locations in pilot libraries.

**To Reproduce**
1. Edit [this location](https://ilspilot.test.rero.ch/professional/records/locations/detail/194) as a librarian of RBNJ
1. Try to save

**Expected behavior**
[Pickup name](https://github.com/rero/rero-ils/blob/master/rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json#L49) in JSON schema must be corrected to be required, so that we get an error if fixture data is not complete.

**Software version**
ilspilot
rero-ils version 647a7f3a
rero-ils-ui version 30e8cdd1

**Comment by BadrAly** [comment]
In `https://ils.rero.ch/schema/locations/location-v0.0.1.json `:

if `is_pickup == True` then the field `pickup_name` is mandatory
