### ISSUE TITLE
Item detailed view: missing circulation info

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#798]
**Describe the issue**
Some items are not available, but the item detailed view doesn't show why:
* Case 1: items with request and status "at desk"
* Case 2: items in transit without request

**To Reproduce**
Case 1
1. Your a librarian in library A
1. Loan an item for patron A
1. Request it as a patron B, with library A as pickup location
1. Checkin the item
1. Open the item detailed view

Case 2
1. Loan an item of another library
1. Checkin this item (it should go in transit without request)
1. Open the item detailed view

**Expected behavior**
The item detailed view is adapted as follows:
- [x] Case 1: box "Request" should be displayed
- [x] All cases: status (on loan, requested, in transit) should be displayed for all cases (as in the document detailed view)
- [x] For all items with requests: the field *Queue* is removed (the box "Request" already displays this information)

**Software version**
ilsdev
rero-ils version e2fbc6b
rero-ils-ui version 925ffabb

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/75252356-d10e0500-57dc-11ea-8650-205874816308.png)

**Comment by AoNoOokami** [comment]
@pronguen 'requested' is not an item status. As the requests are displayed below, I guess it's not needed to repeat the information, but I can display some thing like that:

(requested: [status])

if there are requests.

**Comment by pronguen** [comment]
@AoNoOokami 
* Either you display it exactly as specified in `documentation\projets\RERO21\specifications\interface\availability_v3.pdf`, so that you can re-use this display for the document detailed view (issue will be opened soon). In this case, there will be a repetition of information (requests, due until) with regard to what is in the box below, but at least availability will be showed the same way everywhere.
* Or you do a dedicated display: [availability button]+[status]. Indeed, "requested" is not a status, so don't display that. The user will see the list of requests below and understand that it holds requests.

**Comment by AoNoOokami** [comment]
Actually, @Garfield-fr has a WIP PR for document availability: https://github.com/rero/rero-ils-ui/pull/181. We could group this?
