### ISSUE TITLE
Checkin on item on shelf from other library

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#800]
**Describe the issue**
I do a checkin of an item on shelf from another library. The status stays on shelf, but if I just checked it in, it should be in my library (in transit).
This case happens sometimes, when an item get lost. It is not a classical use case.
This concerns the checkin and the checkout form.

**To Reproduce**
1. Checkin an item on shelf from another library, that does not hold request
1. See status

**Expected behavior**
The status should become "in transit" to the owning library

**Software version**
ilsdev + ilspilot
rero-ils version c236bc8
rero-ils-ui version 4fc4656d

**Comment by AoNoOokami** [comment]
@BadrAly This may need an adaptation in the backend, I think.

**Comment by BadrAly** [comment]
@pronguen:
- after the check-in of an `on_shelf` item of another library, the new status should be `at_desk` not `in_transit`
- In both cases, we do not have yet a `patron_pid`. so creating a virtua `loan` maybe not possible.  So possibly setting the item status to `on_shelf` is not a bad idea. To discuss when implementing this.

**Comment by pronguen** [comment]
@BadrAly 

> after the check-in of an on_shelf item of another library, the new status should be at_desk not in_transit

**Comment by pronguen** [comment]
@BadrAly 

> after the check-in of an on_shelf item of another library, the new status should be at_desk not in_transit

No. I checkin an item that is
* on shelf
* from another library
* with no request

So with no request, an item has never a status `at desk`, which is used only for pickup by patron.

> So possibly setting the item status to on_shelf is not a bad idea

I am sure that it is a good idea technically, but in the real world, if you scan an item outside of its owning library, the item is in transit. It is not anymore on shelf.

**Comment by AoNoOokami** [comment]
I close this issue, as it has been solved with the new circulation of release v0.12.0 (see scenario B and C)
