### ISSUE TITLE
Checkin of item on shelf, with request to validate

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#801]
**Describe the issue**
I have an item on shelf that has been requested and appears in the list of requests to validate. If I do a checkin, the item stays with status "on shelf". It should be automatically validated

**To Reproduce**
1. Checkin an item that is in the list of requests to validate
1. See status

**Expected behavior**
In the checkin form, any item that is on shelf and holds a request to validate should be automatically validated by a checkin.
It concerns items:
* of the librarian's library or not
* with request with pickup in the librarian's library or not

**Software version**
ilsdev + ilspilot
rero-ils version c236bc8
rero-ils-ui version 4fc4656d

**Comment by AoNoOokami** [comment]
@BadrAly This may need an adaptation in the backend, I think.

**Comment by BadrAly** [comment]
@AoNoOokami To discuss, if we need to something like `automatic_validation` or maybe you can handle that already now in the `UI`  ( you should have access to the list of requests for the checked-in item)

**Comment by AoNoOokami** [comment]
@pronguen This use case is not managed at all. After a discussion with @BadrAly, I suggest to address this issue when the state chart is reviewed. I also recommend to check if this will be corrected in a more recent version of invenio-circulation, in order to avoid to waste time on it.

**Comment by AoNoOokami** [comment]
I close this issue, as it has been fixed in v0.12.0
