### ISSUE TITLE
Checked in item from other library doesn't go in transit

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#813]
**Describe the issue**
I am librarian at library B. I return an item of library A for a patron. The item should go *in transit* to owning library, but it is *on shelf*. This is the case in the checkin and checkout form.

**To Reproduce**
1. Your at library B
1. Take an item of library A
1. Do a checkout for a patron
1. Do a checkin
1. See status

**Expected behavior**
The item should go *in transit* to owning library

**Software version**
ils.test.rero.ch
version 0.6.0

**Comment by BadrAly** [comment]
@pronguen  To discuss in details next week:

This problem related to two things:

1. `invenio-circulation` assigns the `in-transit` status by the comparison of item `location` and `pickup_location`. In this case, we possibly have no `pickup_location` or it is not set correctly.

2. theoretically, we can not have an item status = `in_transit` without a `loan`.

**Comment by AoNoOokami** [comment]
I close this issue, as it has been fixed with new circulation of v0.12.0
