### ISSUE TITLE
Improvement needed on the switch library menu

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#821]
**Describe the issue**
As a system librarian, I have a menu to switch libraries, but only on the homepage of the admin interface. Moreover, the active library is display on top of my screen and takes a lot of vertical space.

**To Reproduce**
1. Log in as a system librarian
1. See menu to switch library on homepage
1. Change to another page of the admin interface
1. Menu not displayed

**Expected behavior**
The menu "Switch library" is available from any page of the admin view. It is accessible through the user account menu, as only system librarians have access to it and it is related to log in.
The active library, as displayed in the top line (above header) is not displayed anymore. Instead, it is displayed as part of the user menu.

**Software version**
ilspilot, ils.test
version 0.6.0

**Screenshots**
Possibility to display the switch menu
![image](https://user-images.githubusercontent.com/8154915/75670404-f4253280-5c7c-11ea-933a-042b469ad0b9.png)

**Comment by JoelleDosimont** [comment]
It's seems important as a staff member to see right away the active library. We should see it permanently.
2 ideas :
- keep the top line with the active libray. By clicking on it, we can "switch library".
- put it somewhere else. Perhaps in the permanent menu (but it will soon be full).

**Comment by iGormilhit** [comment]
@JoelleDosimont With the work being done on the editor, the professional interface is going to be much wider (at least on large screens), thus allowing us to improve the navigation. Hopefully, we will have something like a dedicated menu for this, or something else.
