### ISSUE TITLE
Flash message for checkin with fees, requests or transit

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#829]
**Describe the issue**
When I do a checkin of an item with a request, I don't get a flash message.

**To Reproduce**
* Do a checkin of a requested item
* or, Do a checkin of an item that has fees
* or, Do a checkin of an item that goes in transit (item belonging to another library)

**Expected behavior**
For the 3 above mentioned cases, the transaction line is highligthed (already the case). Additionally, I get a flash message with the corresponding information.

**Software version**
ilspilot
v0.6.1

**Additional context**
There is already a flash message when the item has fees.

**Comment by pronguen** [comment]
@AoNoOokami If I checkin (in library A) an item on loan that holds a request with pickup in library A, I receive a flah message *The item is in_transit*. The status displayed in the table is correct: at desk.
Is it related to this issue?

**Comment by AoNoOokami** [comment]
> @AoNoOokami If I checkin (in library A) an item on loan that holds a request with pickup in library A, I receive a flah message _The item is in_transit_. The status displayed in the table is correct: at desk.
> Is it related to this issue?

It's related to the modifications we made in https://github.com/rero/rero-ils/pull/824. Good you saw that. It's corrected in https://github.com/rero/rero-ils-ui/pull/189.
