### ISSUE TITLE
No action is performed in checkin form

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#831]
**Describe the issue**
In checkin form, when I scan an item and no action is performed, I get the text "no".

**To Reproduce**
1. Scan an item that is either
   * already on shelf in your library
   * already at desk in your library
   * already in transit to another library
   * etc.
1. No action is performed by the system, but see text "no"

**Expected behavior**
Nothing is displayed.

**Software version**
ilspilot
v0.6.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/75766366-53e51180-5d41-11ea-8233-5c7e70f4401e.png)

**Comment by AoNoOokami** [comment]
I close this issue, as it has been fixed with new circulation of v0.12.0
