### ISSUE TITLE
Improve order editor/schema

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#851]
**Describe the issue**
1. The field "order date" and "order currency" are empty, but could be prefilled with default values.
1. The field "order number" should be renamed in "reference".
1.  All field titles can be renamed without the mention "order" (redondant).

**To Reproduce**
1. Create a new order
1. See editor

**Expected behavior**
1. Default value: current day for "date", organisation currency for "currency"
1. "order number" is renamed in "reference"
1. All field titles don't have the redondant mention "order"

**Software version**
ilsdev
rero-ils version 1332b2f1
rero-ils-ui version 225ebcab

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/76833466-adfad200-682b-11ea-9863-c6380c90fb0d.png)

**Comment by iGormilhit** [comment]
The title of the schema have been partially simplified already, but there's still work to do.
