### ISSUE TITLE
Translations of roles in patron editor

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#881]
**Describe the issue**
Roles not translated

**To Reproduce**
1. Open patron editor

**Expected behavior**
Should be translated

**Software version**
ilsdev (rero-ils version 0524143a, rero-ils-ui version 2a6a4f48)
ilspilot (phase 1 of tests)

**Comment by iGormilhit** [comment]
Fixed, at least in version `v0.12.0rc`.
