### ISSUE TITLE
Translations of actions realised in circulation UI

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#882]
**Describe the issue**
Actions realised not translated: "checkin", "receive", "checkout"

**To Reproduce**
1. Do an action in circ UI

**Expected behavior**
Should be translated

**Software version**
ilsdev (rero-ils version 0524143a, rero-ils-ui version 2a6a4f48)
ilspilot (phase 1 of tests)

**Screenshot**

![image](https://user-images.githubusercontent.com/8154915/78138214-dfc48900-7426-11ea-8dc1-bfc683684452.png)

**Comment by zannkukai** [comment]
Solved with `v.0.10.1`
![image](https://user-images.githubusercontent.com/10031585/86473630-8d567980-bd41-11ea-9da4-f59dada564bf.png)
