### ISSUE TITLE
Should ebooks records be editable ?

### ISSUE THREAD

**Issue by NicolasLabat** [rero/rero-ils#89]
If the librarian catalogues an ebook, he can't edit the record once it is created. 
Must some ebooks records be editable and others not (harvested ebooks) ?

**Comment by pronguen** [comment]
Yes, indeed. The records that cannot be edited should be determined according to their provenance (Ebook server) and not to their document type.

**Comment by iGormilhit** [comment]
@NicolasLabat @pronguen It's not a bug. It's a feature. So, it merely a wish to improve this feature, in the future, when some non-synched ebooks will, maybe, exist.

**Comment by pronguen** [comment]
Improvement wanted:
* All documents from e-book server should not be editable.
* Ebook should be editable if they don't come from e-book server.
