### ISSUE TITLE
document : staff can't indicate an eISBN or an eISSN as identifier

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#895]
**Describe the issue**
When a staff creates/edits a document, he can't indicate an eISBN or an eISSN as identifier

**To Reproduce**
1. Go to 'https://ilsdev.test.rero.ch'
1. Log in as 'Jean' (reroilstest+jean@gmail.com)
1. Go to the professional interface
1. Edit a document and try to add an  eISBN
1. You can't because it's not listed in the identifiers "dropdown list"

**Expected behavior**
The staff should be able to enter an electronic ISBN or an electronic ISSN as identifier.

**Software version**
v. 0.6.1

  * rero-ils : https://github.com/rero/rero-ils/commit/0524143a403fe72f56a6cebbc82eeb809b19b422
  * rero-ils-ui : https://github.com/rero/rero-ils-ui/commit/2a6a4f4803b5ef20c087e57170b484ea37aa77e0

**Additional context**
Please add eISBN and eISSN in the jsonchema of document.

**Comment by pronguen** [comment]
After reflection we decided not to address this issue, since
* there is no specific standard/format for e-ISBN
* ISBN of electronic resources (e-ISBN) are identified through the resource type
* different documents/manifestations have to be created for the electronic and the printed resource
