### ISSUE TITLE
Briew view display bug when quickly clicking from tab to tab

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#901]
**Describe the issue**
In the brief view of the public interface, I get a display bug in the brief view when I click quickly on the *person* tab.
Displayed are document PID; the links are persons links with documents PID (ex: "https://ils.test.rero.ch/global/persons/9915" where 9915 is actually a document). The document PIDs correpond to the documents displayed in tab *documents*.

**To Reproduce**
1. Open the public view
1. Do a search, for ex. "isabelle de chastonay"
1. Launch the search
1. Before the results are displayed, quickly click on the *person* tab
1. If the persons are displayed correctly, try again: click on the *document* tab, and right after on *person* tab
1. See display bug: see screenshot

**Expected behavior**
No display bug.

**Software version**
ils.test (v.0.6.1)
ilspilot (test phase 1)

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/78564794-42e65f00-781d-11ea-8647-8fca71e3735c.png)

**Comment by rerowep** [comment]
Fixed in ng-core
