### ISSUE TITLE
Saving a document with edition responsibility impossible

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#906]
**Describe the issue**
When I edit a document with an edition designation but no edition responsibility, I cannot save it. I have to remove the field for edition responsibility before.

**To Reproduce**
1. Open a document without edition designation
1. Add an edition designation, but no responsibility
1. Save it
1. Edit it again
1. Don't modify anything but try to save

**Expected behavior**
I can save the document, so
* Field for edition responsibility is optional
* Fields "language" for edition designation and responsibility are not opened by default in the editor when I add the field (it makes it easier)

**Software version**
ils.test.rero.ch (v.0.6.1)

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/78680255-8effd500-78eb-11ea-94ea-7871ca8ea7af.png)

**Comment by iGormilhit** [comment]
It's not related to this specific field.

**Comment by zannkukai** [comment]
With '6c9f7d832734e02e4eab8baa1564e6fda6693716', we can test with `documents/249`
