### ISSUE TITLE
Language facet behaviour (number of results)

### ISSUE THREAD

**Issue by NicolasLabat** [rero/rero-ils#91]
Launch an empty query.
Chose a language in the language facet, for example "Russian" (91 results).
The language facet presents at this stage entries with a number in brackets supposed to correspond to the results both in Russian and in the other languages.
Chose the language "English" (3 results). We expect to obtain 3 results for which language is Russian and English.
The behaviour is different. We obtain all documents in Russian or in English. The number in brackets for English is no more 3 but 1269.

**Comment by AoNoOokami** [comment]
@iGormilhit , @pronguen : Is this issue still relevant?

**Comment by pronguen** [comment]
@AoNoOokami It is a PO question: should facets be applied with AND or OR. I will address this question at next PO meeting on march 9th.

**Comment by pronguen** [comment]
Addressed by [US 1376](https://tree.taiga.io/project/rero21-reroils/us/1376)
