### ISSUE TITLE
Send notification "availability" some time after the item is checked in

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#913]
**Describe the issue**
The notification "availability" is sent right after the item is "at desk".

**To Reproduce**
1. Log in as a librarian of library X
1. Check out an item for patron A
1. Add a request on this item for patron B, with pick up location = X
1. Checkin the item: it becomes "at desk"
1. The availability notification has been sent directly

**Expected behavior**
The availability notification is sent 30 minutes after the item is "at desk". *(to be confirmed)*

**Software version**
ilspilot (test phase 1)

**Additional context**
Note from pilot libraries

> Par ailleurs, l'avis semble être envoyé très rapidement après la mise à disposition du document. C'est risqué : un problème quelconque pourrait survenir et empêcher la mise à disposition du document (ouvrage nécessitant un travail en interne avant la prochaine mise à disposition). Actuellement, dans ces cas-là on prête dans la journée à une carte de gestion. Mais il peut se passer plusieurs heures entre le retour et le moment où on a le temps de s'occuper du cas. Si l'avis part trop vite, c'est un problème. Actuellement dans Virtua, les avis sont envoyés le jour ouvrable suivant aux premières heures. Cela allonge le délai, mais est plus sûr. A évaluer

Note from Louvain:
Wait one day to send a notification delays the checkouts of highly requested items.

**Comment by iGormilhit** [comment]
@pronguen Should or could this be a user story, as it is some kind of a new feature, or a modified specification?

**Comment by pronguen** [comment]
@iGormilhit Yes eventually. It also depends on the effort. @BadrAly what do you think?

**Comment by pronguen** [comment]
@benerken Pilot library Neuchâtel wants a delay of 120 minutes before sending the notification, to be able to detect eventual problem in the physical document in the meantime.
I think 30 minutes could be a good "Swiss compromise" between *a lot of time to detect a problem* and *an immediate notification in case of bestsellers*.

**Comment by pronguen** [comment]
Will be solved as a configuration in [US 913](https://tree.taiga.io/project/rero21-reroils/us/1922?no-milestone=1).
