### ISSUE TITLE
Translate content field "Language" in document detailed view of public interface

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#916]
**Describe the issue**
Field "Language" in document detailed view of public interface is displayed as a 3 digits code. (In professional interface, it is ok!)

**To Reproduce**
1. Display any document in public interface

**Expected behavior**
Field "Language" in document detailed view of public interface is displayed in natural language.

**Software version**
ils.test.rero.ch (v0.6.1)
ilspilot (test phase 1)

**Comment by zannkukai** [comment]
Soved testing with `v.0.10.1`
