### ISSUE TITLE
Language switch does not work properly on the professional interface

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#925]
**Describe the issue**
When I change the language in the professional interface, it does not change all elements.

**To Reproduce**
1. Log in as a librarian and open the pro interface. You are in language X.
1. Open an item type and edit it
1. Change to language Y
1. See that the form label didn't change
1. Go to homepage of professional interface
1. See that it is only partially translated

**Expected behavior**
Change language works everywhere.

**Software version**
ils.test.rero.ch (0.7.0)
ils pilot (test phase 1)

**Screenshots**
In this screenshot, the selected language is English, but almost everything stays in Italian.
![image](https://user-images.githubusercontent.com/8154915/79239971-7bb3b300-7e71-11ea-87f1-8846e21b1a46.png)

**Comment by iGormilhit** [comment]
As @jma explained, it related to the translated JSON schema mechanism.

**Comment by iGormilhit** [comment]
This closes https://github.com/rero/rero-ils/issues/943 too.
