### ISSUE TITLE
Cancel button in patron profile

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#929]
**Describe the issue**
The cancel button ist not translated in patron profile (public).

**To Reproduce**
1. Open the patron profile in public  (as a patron)

**Expected behavior**
Cancel button is translated.

**Software version**
ils.test.rero.ch (v0.7.0)
ilspilot (test phase 1 - v0.6.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/79317887-92581980-7f06-11ea-98bd-84b9f6a0a1b0.png)

**Comment by zannkukai** [comment]
Problem solved in 0.8.0
