### ISSUE TITLE
Switch to professional interface at login

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#933]
**Describe the issue**
When I log in as a librarian from the public home page, I land on the public interface.

**To Reproduce**
1. Log in a as a librarian from the public homepage

**Expected behavior**
When I log in as a librarian from the public home page, I land on the professional interface.

Additionally:
- if you are in a search result screen, or a detail record view: **after authentication as a patron**, you should land on the page we you were before authentication (=search result screen, or a detail record view)
- if you are in a search result screen, or a detail record view: **after authentication as a librarian**, you should land on the page we you were before authentication, but in the **professional interface**
- if you are on a page of the public view as a librarian: **after switching to professional interface**, you should land on the page we you were before authentication, but in the **professional interface**
- if you are on a page of the professional view as a librarian: **after switching to public interface**, you should land on the page we you were before authentication, but in the **public interface**. If it doesn't exist, you land on the homepage.

**Software version**
ils.test.rero.ch (v0.7.0)
ilspilot (test, phase 1)

**Comment by iGormilhit** [comment]
As a workaround, the professionals could directly load the professional interface: [ils.test.rero.ch/professionnal](https://ils.test.rero.ch/professionnal). But still, something has to be done.

**Comment by iGormilhit** [comment]
> As a workaround, the professionals could directly load the professional interface: [ils.test.rero.ch/professionnal](https://ils.test.rero.ch/professionnal). But still, something has to be done.

@pronguen @rerowep I actually think that this is the way to go. If one wants to get to the professional interface directly, he/her need to log in directly in that interface. The switch button is just there to help.

**Comment by pronguen** [comment]
@iGormilhit Yes this was my opinion as well. Issue was initially proposed by @rerowyj and confirmed by pilot libraries (this suggestion was as is in their testing file, and they just had to write "I agree", which was actually an error from our side).

In my mind, it is not prioritary if it requires an effort. Indeed, the link ils.test.rero.ch/professionnal can be used instead. I think the librarian will save it once in his favorites and that's it. But no one knows this link. Should we make it more visible? For example:
* add it in the help pages
* add it in next to the login button in the public homepage

**Comment by iGormilhit** [comment]
@pronguen Ok, fine, because I know that @rerowep is struggling with this.

For the visibility, you are right, and I think that at least the URL to the professional interface should be in the help pages (as these are going to be written soon, hopefully). The link in the user menu is a good idea too, but it will be visible to any one. I don't think it is a big issue, so this could be done.

**Comment by iGormilhit** [comment]
As @PascalRepond modified the [help documentation][1] to suggest to professionals to bookmark the direct link to the professional interface, I'll close this issue.

[1]: https://ils.test.rero.ch/help/principles_fr/#interface-publiqueprofessionnelle
