### ISSUE TITLE
Check that all buttons (from UI) follow the circulation policy

### ISSUE THREAD

**Issue by blankoworld** [rero/rero-ils#936]
**Describe the issue**
We should check in rero-ils-ui that all buttons follow the circulation policy.

In example the renewal button use a method that don't use the "patron_pid".
If, for any reason, the new "blocking user" functionnality disallow renewals in circulation policy, without the patron_pid the renewal button will not know that it's forbidden for this user to renew the loan.

**Comment by iGormilhit** [comment]
@AoNoOokami Can you confirm that we can close this?

**Comment by AoNoOokami** [comment]
First we must decide if a blocked patron can renew an item or not. And I think that only the example mentioned by Olivier is concerned, the other buttons in rero-ils-ui observe the permissions implemented in backend.

**Comment by iGormilhit** [comment]
Yes, a blocked patron is able to renew its loans: https://tree.taiga.io/project/rero21-reroils/us/299

So, this is issue is considered as closed. Thanks.
