### ISSUE TITLE
Prediction pattern: add ability to use ordinal numbers

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#948]
**Describe the issue**
When the librarian creates a prediction pattern, he can't use ordinal numbers.
Ex: 1st issue, 2nd issue, etc.

**To Reproduce**
1. Go to ilsdev.test.rero.ch
1. Log in as Elena and go to the professional interface
1. Look for a journal and add a holding.
1. you can create an new prediction pattern but you can't use ordinal numbers 

**Expected behavior**
The librarian should be able use ordinal numbers.

**Software version**
ilsdev.test.rero.ch (V. 0.7.0 with  https://github.com/rero/rero-ils/pull/885)

**Comment by PascalRepond** [comment]
Is there really a specific use-case where this fonctionnality would be mandatory and where I couldn't use "issue 1, issue 2, etc.." in the label?

**Comment by JoelleDosimont** [comment]
Normally, we should record the designators as written on the ressource. I think it follows the RDA rules (1.8.5)...

**Comment by benerken** [comment]
Checked with v.0.14
It's fixed.
