### ISSUE TITLE
Results page: Unable to extend a search to all organisations in professional view.

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils#975]
**Describe the issue**
In the professional interface:
-  if I do a search on a term which returns a result, it's filtered on my organisation by default, but I'm able to extend the search to all organisations using the facet "Organisation" (OK)
-  if I do a search on a term which returns **no result** , I'm unable to extend the search to all organisations because the facet "Organisation" is not displayed.  

**To Reproduce**
1. Go to https://ilsdev.test.rero.ch
1. Log in as reroilstest+elena@gmail.com 
1. Go to the Professional interface
1. Do a search on "abcdefgh"
1. You should see "0 results" and the empty screen. How can I run the same search on all organisations ?  

**Expected behavior**
When I get a "0 result" for my search, I should be able to run the same search on all organisations to see if there is a book available anywhere else.

Solution 1: add a button to extend the search
Solution 2: automatically do the search on all organisations and display a message saying the search has been extended (to avoid 1 click by the user)

**Software version**
  * https://ilsdev.test.rero.ch
  * rero-ils https://github.com/rero/rero-ils/commit/28b731fc844385e5f946cc78e7a63451196757df
  * rero-ils-ui https://github.com/rero/rero-ils-ui/commit/85c9bc9992f854baa3d90ff4c3e30aaabe45983a

**Comment by iGormilhit** [comment]
This is fixed by https://github.com/rero/rero-ils-ui/pull/382.
