### ISSUE TITLE
Removing existing restriction on available pickup location prevents to save the record

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#988]
**Describe the issue**
When a location already defined some restrict pickup locations, If manager try to remove restrictions, the form cannot be saved.

**To Reproduce**
1. I have a location with pick up restriction (more than 1 pickup locations allowed)
2. I edit this location
3. I disable the button "Restrict pickup to"
4. I cannot save

**Expected behavior**
Save button should be active

**Software version**
rero-ils version 9fbc355d
rero-ils-ui version cf1a8517

**Comment by zannkukai** [comment]
The problem is due to "toggle wrapper" from ng-core.
When we toggle-off the restrict_pickup_to, the children are reset to 'blank' value. If there are more than one locations, then the reset cause multiple 'null' values and the value for 'restrict_location_to' array must be unique. 

**Expected behavior : **
When the restrict_pickup_to toggle switch is off, then the additional fields should be removed (keeping only the first location with null value)

**Comment by AoNoOokami** [comment]
I close this issue, as it has been fixed with new circulation of v0.12.0
